// [STAMPED] from FUN_00c80ca7.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x008c2e8c (VA 0x00cc2e8c)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xc80ca7 — SEH unwind helper (LEA ECX, [EBP-0x230]; JMP) — disp32
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 9 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8d 8d fffffdd0 e9 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void unwind_thunk() {
    __asm {
        lea ecx, [ebp - 560]
        jmp target
    }
}
