// [STAMPED] from FUN_00974140.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00574220 (VA 0x00974220)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x974140 — no-reloc cluster member (13B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 79 08 00 7e 04 8b 41 04 c3 33 c0 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x83
        _emit 0x79
        _emit 0x08
        _emit 0x00
        _emit 0x7e
        _emit 0x04
        _emit 0x8b
        _emit 0x41
        _emit 0x04
        _emit 0xc3
        _emit 0x33
        _emit 0xc0
        _emit 0xc3
    }
}
