// [STAMPED] from FUN_009f97a0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00607960 (VA 0x00a07960)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x9f97a0 — no-reloc cluster member (11B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 5 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 01 8b 50 20 ff d2 8b 40 18 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x01
        _emit 0x8b
        _emit 0x50
        _emit 0x20
        _emit 0xff
        _emit 0xd2
        _emit 0x8b
        _emit 0x40
        _emit 0x18
        _emit 0xc3
    }
}
