// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x567fea — unwind helper (MOV ECX, [EBP-0x18]; PUSH ECX; CALL)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 5 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 4d e8 51 e8 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void seh_push_ecx_local() {
    __asm {
        mov ecx, [ebp - 24]
        push ecx
        call target
    }
}
