// [STAMPED] from FUN_0071cb90.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0031e4d0 (VA 0x0071e4d0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x71cb90 — no-reloc cluster member (7B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: c7 01 f8 ca dc 00 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0xc7
        _emit 0x01
        _emit 0xf8
        _emit 0xca
        _emit 0xdc
        _emit 0x00
        _emit 0xc3
    }
}
