// [STAMPED] from FUN_005986e0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00425f40 (VA 0x00825f40)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5986e0 — return false (bool, 8-bit) — 3-arg
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 8 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 32 c0 c2 0c 00

class C { public: unsigned char no(int, int, int); };
unsigned char C::no(int, int, int) { unsigned char r = 0; return r; }
