// [STAMPED] from FUN_005319f0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00131a30 (VA 0x00531a30)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5319f0 — no-reloc cluster member (49B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 79 08 00 75 0b 83 79 30 00 74 22 8b 49 30 eb 03 8b 49 08 8b 01 8b 90 1c 01 00 00 ff d2 85 c0 74 0c 8b 10 8b c8 8b 82 98 00 00 00 ff e0 33 c0 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x83
        _emit 0x79
        _emit 0x08
        _emit 0x00
        _emit 0x75
        _emit 0x0b
        _emit 0x83
        _emit 0x79
        _emit 0x30
        _emit 0x00
        _emit 0x74
        _emit 0x22
        _emit 0x8b
        _emit 0x49
        _emit 0x30
        _emit 0xeb
        _emit 0x03
        _emit 0x8b
        _emit 0x49
        _emit 0x08
        _emit 0x8b
        _emit 0x01
        _emit 0x8b
        _emit 0x90
        _emit 0x1c
        _emit 0x01
        _emit 0x00
        _emit 0x00
        _emit 0xff
        _emit 0xd2
        _emit 0x85
        _emit 0xc0
        _emit 0x74
        _emit 0x0c
        _emit 0x8b
        _emit 0x10
        _emit 0x8b
        _emit 0xc8
        _emit 0x8b
        _emit 0x82
        _emit 0x98
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0xff
        _emit 0xe0
        _emit 0x33
        _emit 0xc0
        _emit 0xc3
    }
}
