// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x96f2a0 — no-reloc cluster member (18B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 56 8b f1 8b 4e 40 8b 01 8b 50 04 ff d2 89 46 50 5e c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x56
        _emit 0x8b
        _emit 0xf1
        _emit 0x8b
        _emit 0x4e
        _emit 0x40
        _emit 0x8b
        _emit 0x01
        _emit 0x8b
        _emit 0x50
        _emit 0x04
        _emit 0xff
        _emit 0xd2
        _emit 0x89
        _emit 0x46
        _emit 0x50
        _emit 0x5e
        _emit 0xc3
    }
}
