// [STAMPED] from FUN_005ea4d0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00300d30 (VA 0x00700d30)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5ea4d0 — multi-inheritance `this`-adjustor (SUB ECX, 0xe8; JMP)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 81 e9 000000e8 (LE) e9 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void adjustor_thunk() {
    __asm {
        sub ecx, 232
        jmp target
    }
}
