// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x9794d0 — no-reloc cluster member (3B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: d9 ee c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0xd9
        _emit 0xee
        _emit 0xc3
    }
}
