// [STAMPED] from FUN_00508b50.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0011acc0 (VA 0x0051acc0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x508b50 — member-vtable tail-jmp via EAX (slot 0x40)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 49 04 8b 01 8b 40 40 ff e0

extern "C" __declspec(naked) void member_vtable_tailjmp_eax() {
    __asm {
        mov ecx, [ecx + 4]
        mov eax, [ecx]
        mov eax, [eax + 0x40]
        jmp eax
    }
}
