// [STAMPED] from FUN_006f0db0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x006bb0c0 (VA 0x00abb0c0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x6f0db0 — int field setter at offset 0xec (disp32)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 44 24 04 89 81 NN NN NN NN c2 04 00  (offset=0xec)

class C {
    int padding[59];
    int field;
public:
    void set_field(int);
};

void C::set_field(int v) { field = v; }
