// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x9741e0 — predicate: field@0x8 > 0 (CMP-imm form)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 5 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 79 08 00 0f 9f c0 c3

extern "C" __declspec(naked) unsigned char field_gt_zero() {
    __asm {
        cmp dword ptr [ecx + 0x8], 0
        setg al
        ret
    }
}
