// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x9e1590 — no-reloc cluster member (32B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 56 8b f1 8b 06 8b 50 0c ff d2 8b 06 8b 50 0c 8b ce ff d2 8b 10 8b c8 8b 42 44 ff d0 8b 00 5e c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x56
        _emit 0x8b
        _emit 0xf1
        _emit 0x8b
        _emit 0x06
        _emit 0x8b
        _emit 0x50
        _emit 0x0c
        _emit 0xff
        _emit 0xd2
        _emit 0x8b
        _emit 0x06
        _emit 0x8b
        _emit 0x50
        _emit 0x0c
        _emit 0x8b
        _emit 0xce
        _emit 0xff
        _emit 0xd2
        _emit 0x8b
        _emit 0x10
        _emit 0x8b
        _emit 0xc8
        _emit 0x8b
        _emit 0x42
        _emit 0x44
        _emit 0xff
        _emit 0xd0
        _emit 0x8b
        _emit 0x00
        _emit 0x5e
        _emit 0xc3
    }
}
