// [STAMPED] from FUN_0088c450.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0048d0f0 (VA 0x0088d0f0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x88c450 — no-reloc cluster member (4B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: d9 41 4c c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0xd9
        _emit 0x41
        _emit 0x4c
        _emit 0xc3
    }
}
