// [STAMPED] from FUN_00c7dc7b.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0088c6b4 (VA 0x00c8c6b4)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xc7dc7b — SEH unwind helper (MOV ECX, [EBP-0xc4]; JMP) — disp32
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 15 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 8d ffffff3c e9 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void unwind_thunk() {
    __asm {
        mov ecx, [ebp - 196]
        jmp target
    }
}
