// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x55f250 — thiscall null-check member tail-jmp (this->[+0x4], skip if null)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 10 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 49 04 85 c9 74 05 e9 RR RR RR RR c2 04 00

extern "C" int target();

extern "C" __declspec(naked) void thiscall_null_check_jmp() {
    __asm {
        mov ecx, [ecx + 0x4]
        test ecx, ecx
        jz skip
        jmp target
    skip:
        ret 4
    }
}
