// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x9f0a90 — global == arg predicate (MOV EAX,[global]; CMP EAX,[ESP+4]; SETE AL; RET 4)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 19 byte-identical (or
// reloc-equivalent) members.
//
// Asm: a1 GG GG GG GG 3b 44 24 04 0f 94 c0 c2 04 00

extern "C" void *the_global;

extern "C" unsigned char __stdcall is_global(void *p);
extern "C" __declspec(naked) unsigned char __stdcall is_global(void *p) {
    __asm {
        mov eax, dword ptr [the_global]
        cmp eax, [esp + 4]
        sete al
        ret 4
    }
}
