// [STAMPED] from FUN_0053f890.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0021d2e0 (VA 0x0061d2e0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x53f890 — vtable-dispatch trampoline (~scalar-deleting forwarder)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 88 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 4c 24 04 85 c9 74 0e 8b 01 8b 10 c7 44 24 04 01 00 00 00 ff e2 c2 04 00

extern "C" __declspec(naked) void vtbl_forwarder() {
    __asm {
        mov ecx, [esp + 4]
        test ecx, ecx
        jz no_call
        mov eax, [ecx]
        mov edx, [eax]
        mov dword ptr [esp + 4], 1
        jmp edx
    no_call:
        ret 4
    }
}
