// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x906827 — call(imm8=12) — PUSH imm8; CALL; POP ECX; RET
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 5 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 6a 0c e8 RR RR RR RR 59 c3

extern "C" int target(int);

extern "C" __declspec(naked) void wrapper_imm8_call() {
    __asm {
        push 12
        call target
        pop ecx
        ret
    }
}
