// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x7927b0 — adjustor thunk imm32 (ADD ECX, 0xe8; JMP)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 81 c1 NN NN NN NN e9 RR RR RR RR  (offset=0xe8)

extern "C" int target();

extern "C" __declspec(naked) void adjustor_add_imm32() {
    __asm {
        add ecx, 0xe8
        jmp target
    }
}
