// [STAMPED] from FUN_00885a30.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00862ae0 (VA 0x00c62ae0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x885a30 — int field getter at offset 0x148 (disp32)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 81 NN NN NN NN c3  (offset=0x148)

class C {
    int padding[82];
    int field;
public:
    int get_field();
};

int C::get_field() { return field; }
