// [STAMPED] from FUN_00ad5b00.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x006dafd0 (VA 0x00adafd0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xad5b00 — no-reloc cluster member (22B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 49 54 85 c9 75 05 33 c0 c2 04 00 8b 01 8b 80 b0 00 00 00 ff e0

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x49
        _emit 0x54
        _emit 0x85
        _emit 0xc9
        _emit 0x75
        _emit 0x05
        _emit 0x33
        _emit 0xc0
        _emit 0xc2
        _emit 0x04
        _emit 0x00
        _emit 0x8b
        _emit 0x01
        _emit 0x8b
        _emit 0x80
        _emit 0xb0
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0xff
        _emit 0xe0
    }
}
