// [STAMPED] from FUN_00a5a300.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00859ec0 (VA 0x00c59ec0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xa5a300 — no-reloc cluster member (7B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 11 byte-identical (or
// reloc-equivalent) members.
//
// Asm: c7 01 e4 5d e6 00 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0xc7
        _emit 0x01
        _emit 0xe4
        _emit 0x5d
        _emit 0xe6
        _emit 0x00
        _emit 0xc3
    }
}
