// [STAMPED] from FUN_004ef1f0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00447f50 (VA 0x00847f50)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x4ef1f0 — float field getter at offset 0xc
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: d9 41 0c c3

class C {
    int padding[3];
    float field;
public:
    float get();
};

float C::get() { return field; }
