// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xc61af0 — empty `__thiscall` 16-arg method (RET 0x40)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: c2 40 00

class C { public: void empty16(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int); };
void C::empty16(int, int, int, int, int, int, int, int, int, int, int, int, int, int, int, int) {}
