// [STAMPED] from FUN_00cd83c0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x008d83ce (VA 0x00cd83ce)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xcd83c0 — single-arg cdecl wrapper (PUSH [EBP-0x1118]; CALL; POP ECX; RET) — disp32
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 85 NN NN NN NN 50 e8 RR RR RR RR 59 c3  (disp=-0x1118)

extern "C" int target();

extern "C" __declspec(naked) void wrapper_1arg_ebp_disp32() {
    __asm {
        mov eax, [ebp - 4376]
        push eax
        call target
        pop ecx
        ret
    }
}
