// [STAMPED] from FUN_00c774b3.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x008d39a3 (VA 0x00cd39a3)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xc774b3 — SEH unwind helper (MOV ECX, [EBP-0x10]; ADD ECX, 0x44; JMP)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 56 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 4d f0 83 c1 44 e9 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void unwind_thunk() {
    __asm {
        mov ecx, [ebp - 16]
        add ecx, 68
        jmp target
    }
}
