// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x6430b0 — no-reloc cluster member (42B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: f3 0f 10 05 60 b3 d7 00 33 c0 ba 03 00 00 00 88 41 20 89 41 04 89 41 08 f3 0f 11 41 0c 89 51 10 89 51 18 89 41 14 89 41 1c c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0xf3
        _emit 0x0f
        _emit 0x10
        _emit 0x05
        _emit 0x60
        _emit 0xb3
        _emit 0xd7
        _emit 0x00
        _emit 0x33
        _emit 0xc0
        _emit 0xba
        _emit 0x03
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x88
        _emit 0x41
        _emit 0x20
        _emit 0x89
        _emit 0x41
        _emit 0x04
        _emit 0x89
        _emit 0x41
        _emit 0x08
        _emit 0xf3
        _emit 0x0f
        _emit 0x11
        _emit 0x41
        _emit 0x0c
        _emit 0x89
        _emit 0x51
        _emit 0x10
        _emit 0x89
        _emit 0x51
        _emit 0x18
        _emit 0x89
        _emit 0x41
        _emit 0x14
        _emit 0x89
        _emit 0x41
        _emit 0x1c
        _emit 0xc3
    }
}
