// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x9fb0b0 — no-reloc cluster member (18B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 01 8b 50 20 ff d2 33 c9 39 48 1c 0f 9d c1 8a c1 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x01
        _emit 0x8b
        _emit 0x50
        _emit 0x20
        _emit 0xff
        _emit 0xd2
        _emit 0x33
        _emit 0xc9
        _emit 0x39
        _emit 0x48
        _emit 0x1c
        _emit 0x0f
        _emit 0x9d
        _emit 0xc1
        _emit 0x8a
        _emit 0xc1
        _emit 0xc3
    }
}
