// [STAMPED] from FUN_00c77e8f.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x008b2ea0 (VA 0x00cb2ea0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xc77e8f — unwind helper — 2-arg PUSH+PUSH+CALL ([EBP+0xc]+[EBP+0x8])
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 45 0c 50 8b 4d 08 51 e8 RR RR RR RR 83 c4 08 c3

extern "C" int target();

extern "C" __declspec(naked) void unwind_2arg() {
    __asm {
        mov eax, [ebp + 12]
        push eax
        mov ecx, [ebp + 8]
        push ecx
        call target
        add esp, 8
        ret
    }
}
