// [STAMPED] from FUN_00525a10.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00567570 (VA 0x00967570)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x525a10 — int field setter at offset 0x60
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 44 24 04 89 41 60 c2 04 00

class C {
    int padding[24];
    int field;
public:
    void set_field(int);
};

void C::set_field(int v) { field = v; }
