// [STAMPED] from FUN_009f46e0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x006069d0 (VA 0x00a069d0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x9f46e0 — global pointer getter (RET 4)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 11 byte-identical (or
// reloc-equivalent) members.
//
// Asm: a1 GG GG GG GG c2 04 00

extern "C" int the_global;

extern "C" __declspec(naked) void global_getter_ret4() {
    __asm {
        mov eax, dword ptr [the_global]
        ret 4
    }
}
