// [STAMPED] from FUN_00839a80.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0071d1a0 (VA 0x00b1d1a0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x839a80 — vtable tail-jmp via EDX (slot 0x34)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 6 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 01 8b 50 34 ff e2

extern "C" __declspec(naked) void vtable_tailjmp_edx() {
    __asm {
        mov eax, [ecx]
        mov edx, [eax + 0x34]
        jmp edx
    }
}
