// [STAMPED] from FUN_005db4d0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x001f96c0 (VA 0x005f96c0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5db4d0 — chained ptr getter (this->[+0x14]->field+0x14)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 5 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 41 14 8b 40 14 c3

class Inner {
    int padding[5];
public:
    int *field;
};

class Outer {
    int padding[5];
    Inner *inner;
public:
    int *get_inner_field();
};

int *Outer::get_inner_field() { return inner->field; }
