// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xa13600 — no-reloc cluster member (55B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 11 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 55 8b ec 83 e4 f0 8b 55 08 0f 28 12 0f b6 c9 f3 0f 2a c9 8b 4d 0c 0f 57 c0 0f c6 c9 00 0f c2 c1 01 0f 28 c8 0f 55 ca 0f 28 11 0f 54 d0 0f 56 ca 0f 29 08 8b e5 5d c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x55
        _emit 0x8b
        _emit 0xec
        _emit 0x83
        _emit 0xe4
        _emit 0xf0
        _emit 0x8b
        _emit 0x55
        _emit 0x08
        _emit 0x0f
        _emit 0x28
        _emit 0x12
        _emit 0x0f
        _emit 0xb6
        _emit 0xc9
        _emit 0xf3
        _emit 0x0f
        _emit 0x2a
        _emit 0xc9
        _emit 0x8b
        _emit 0x4d
        _emit 0x0c
        _emit 0x0f
        _emit 0x57
        _emit 0xc0
        _emit 0x0f
        _emit 0xc6
        _emit 0xc9
        _emit 0x00
        _emit 0x0f
        _emit 0xc2
        _emit 0xc1
        _emit 0x01
        _emit 0x0f
        _emit 0x28
        _emit 0xc8
        _emit 0x0f
        _emit 0x55
        _emit 0xca
        _emit 0x0f
        _emit 0x28
        _emit 0x11
        _emit 0x0f
        _emit 0x54
        _emit 0xd0
        _emit 0x0f
        _emit 0x56
        _emit 0xca
        _emit 0x0f
        _emit 0x29
        _emit 0x08
        _emit 0x8b
        _emit 0xe5
        _emit 0x5d
        _emit 0xc3
    }
}
