// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xee0950 — single-arg cdecl wrapper (PUSH [EBP-0x1f8]; CALL; POP ECX; RET) — disp32
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 11 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 85 NN NN NN NN 50 e8 RR RR RR RR 59 c3  (disp=-0x1f8)

extern "C" int target();

extern "C" __declspec(naked) void wrapper_1arg_ebp_disp32() {
    __asm {
        mov eax, [ebp - 504]
        push eax
        call target
        pop ecx
        ret
    }
}
