// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5011e0 — stdcall 2-arg passthrough (CALL; RET 8)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 10 byte-identical (or
// reloc-equivalent) members.
//
// Asm: e8 RR RR RR RR c2 08 00

extern "C" int target();

extern "C" __declspec(naked) void __stdcall wrapper_call_ret8(int, int) {
    __asm {
        call target
        ret 8
    }
}
