// [STAMPED] from FUN_00590800.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x005b78b0 (VA 0x009b78b0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x590800 — float field getter at offset 0x10
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 6 byte-identical (or
// reloc-equivalent) members.
//
// Asm: d9 41 10 c3

class C {
    int padding[4];
    float field;
public:
    float get();
};

float C::get() { return field; }
