// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xb77db0 — no-reloc cluster member (8B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8a 41 48 d0 e8 24 01 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8a
        _emit 0x41
        _emit 0x48
        _emit 0xd0
        _emit 0xe8
        _emit 0x24
        _emit 0x01
        _emit 0xc3
    }
}
