// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x00064480 — _ASN1_STRING_type_new
//           (__cdecl, 72 B / 0x48)
//
// OpenSSL ASN1_STRING_type_new: allocates a 16-byte ASN1_STRING via
// CRYPTO_malloc, zeroes length/data/flags, sets type from the argument.
// On allocation failure calls ERR_put_error(lib=0xd, func=0x82,
// reason=0x41, file=0xf6a2d4, line=0x1ac) and returns NULL.
//
// ASN1_STRING layout (16 bytes):
//   +0x00  int   length   (initialised to 0)
//   +0x04  int   type     (set to arg)
//   +0x08  void *data     (initialised to NULL)
//   +0x0c  long  flags    (initialised to 0)
//
// Calling convention: __cdecl — one stack arg (int type at [ESP+4]),
// no saved registers, plain RET.
//
// Register usage: EAX = CRYPTO_malloc return value (final return).
// ECX is XOR'd to 0 after the malloc call and kept zero for both the
// NULL check (CMP EAX,ECX) and the three zeroing stores to the struct.
// EDX is loaded from [ESP+4] (type arg) on the success path.
//
// PUSH 0xf6a2d4 (source-file string pointer in .rdata) emits as a raw
// immediate 68 d4 a2 f6 00 in both the orig binary and the new .obj —
// no relocation generated by the assembler — so the bytes match directly.
// The two CALL rel32 displacements are REL32 relocations masked by
// tools/compare.py.
//
// Reloc-bearing positions (masked by tools/compare.py):
//   off 0x0d  IMAGE_REL_I386_REL32 → FUN_00463150 (CALL CRYPTO_malloc)
//   off 0x2e  IMAGE_REL_I386_REL32 → FUN_0045c940 (CALL ERR_put_error)

extern "C" void FUN_00463150(); // CRYPTO_malloc(size, file, line)
extern "C" void FUN_0045c940(); // ERR_put_error(lib, func, reason, file, line)

extern "C" __declspec(naked) void FUN_00464480() {
    __asm {
        push    0x1a9
        push    0xf6a2d4
        push    0x10
        call    FUN_00463150
        xor     ecx, ecx
        add     esp, 0x0c
        cmp     eax, ecx
        jnz     success
        push    0x1ac
        push    0xf6a2d4
        push    0x41
        push    0x82
        push    0x0d
        call    FUN_0045c940
        add     esp, 0x14
        xor     eax, eax
        ret
    success:
        mov     edx, dword ptr [esp + 0x4]
        mov     dword ptr [eax], ecx
        mov     dword ptr [eax + 0x4], edx
        mov     dword ptr [eax + 0x8], ecx
        mov     dword ptr [eax + 0xc], ecx
        ret
    }
}
