// [STAMPED] from FUN_008526b0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x006035c0 (VA 0x00a035c0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x8526b0 — int field setter at offset 0xc
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 6 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 44 24 04 89 41 0c c2 04 00

class C {
    int padding[3];
    int field;
public:
    void set_field(int);
};

void C::set_field(int v) { field = v; }
