// [STAMPED] from FUN_00c027f0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00806c40 (VA 0x00c06c40)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xc027f0 — no-reloc cluster member (10B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 66 8b 44 24 04 66 c1 c0 08 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x66
        _emit 0x8b
        _emit 0x44
        _emit 0x24
        _emit 0x04
        _emit 0x66
        _emit 0xc1
        _emit 0xc0
        _emit 0x08
        _emit 0xc3
    }
}
