// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x514d80 — thiscall save-call-restore-jmp (PUSH ESI; MOV ESI,ECX; CALL A; MOV ECX,ESI; POP ESI; JMP B)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 11 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 56 8b f1 e8 RR RR RR RR 8b ce 5e e9 RR RR RR RR

extern "C" int call_a();
extern "C" int call_b();

extern "C" __declspec(naked) void save_call_restore_jmp() {
    __asm {
        push esi
        mov esi, ecx
        call call_a
        mov ecx, esi
        pop esi
        jmp call_b
    }
}
