// [STAMPED] from FUN_00a17510.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0062b1a0 (VA 0x00a2b1a0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xa17510 — chained ptr getter (this->[+0x4]->field+0x4)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 41 04 8b 40 04 c3

class Inner {
    int padding[1];
public:
    int *field;
};

class Outer {
    int padding[1];
    Inner *inner;
public:
    int *get_inner_field();
};

int *Outer::get_inner_field() { return inner->field; }
