// [STAMPED] from FUN_00d5e650.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0097efc0 (VA 0x00d7efc0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xd5e650 — no-reloc cluster member (66B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 ec 10 8b 44 24 14 f3 0f 7e 48 18 f3 0f 7e 40 10 8b 4c 24 18 8d 41 18 66 0f d6 4c 24 08 f3 0f 10 0d 70 4f f5 00 89 41 14 66 0f d6 00 f3 0f 11 4c 24 0c f3 0f 7e 44 24 08 66 0f d6 40 08 83 c4 10 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x83
        _emit 0xec
        _emit 0x10
        _emit 0x8b
        _emit 0x44
        _emit 0x24
        _emit 0x14
        _emit 0xf3
        _emit 0x0f
        _emit 0x7e
        _emit 0x48
        _emit 0x18
        _emit 0xf3
        _emit 0x0f
        _emit 0x7e
        _emit 0x40
        _emit 0x10
        _emit 0x8b
        _emit 0x4c
        _emit 0x24
        _emit 0x18
        _emit 0x8d
        _emit 0x41
        _emit 0x18
        _emit 0x66
        _emit 0x0f
        _emit 0xd6
        _emit 0x4c
        _emit 0x24
        _emit 0x08
        _emit 0xf3
        _emit 0x0f
        _emit 0x10
        _emit 0x0d
        _emit 0x70
        _emit 0x4f
        _emit 0xf5
        _emit 0x00
        _emit 0x89
        _emit 0x41
        _emit 0x14
        _emit 0x66
        _emit 0x0f
        _emit 0xd6
        _emit 0x00
        _emit 0xf3
        _emit 0x0f
        _emit 0x11
        _emit 0x4c
        _emit 0x24
        _emit 0x0c
        _emit 0xf3
        _emit 0x0f
        _emit 0x7e
        _emit 0x44
        _emit 0x24
        _emit 0x08
        _emit 0x66
        _emit 0x0f
        _emit 0xd6
        _emit 0x40
        _emit 0x08
        _emit 0x83
        _emit 0xc4
        _emit 0x10
        _emit 0xc3
    }
}
