// [STAMPED] from FUN_00416310.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00942d80 (VA 0x00d42d80)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x416310 — import thunk (JMP DWORD PTR [iat_slot])
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 54 byte-identical (or
// reloc-equivalent) members.
//
// Asm: ff 25 GG GG GG GG

extern "C" int (*target_iat_slot)();

extern "C" __declspec(naked) void import_thunk() {
    __asm {
        jmp dword ptr [target_iat_slot]
    }
}
