// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x665ff0 — no-reloc cluster member (69B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 56 57 8b f9 8b b7 94 2b 00 00 85 f6 74 16 8b 06 8b 90 c4 00 00 00 8b ce ff d2 c7 86 98 2b 00 00 00 00 00 00 85 f6 c7 87 94 2b 00 00 00 00 00 00 74 0e 8b 8f 18 01 00 00 8b 01 8b 50 08 56 ff d2 5f 8b c6 5e c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x56
        _emit 0x57
        _emit 0x8b
        _emit 0xf9
        _emit 0x8b
        _emit 0xb7
        _emit 0x94
        _emit 0x2b
        _emit 0x00
        _emit 0x00
        _emit 0x85
        _emit 0xf6
        _emit 0x74
        _emit 0x16
        _emit 0x8b
        _emit 0x06
        _emit 0x8b
        _emit 0x90
        _emit 0xc4
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x8b
        _emit 0xce
        _emit 0xff
        _emit 0xd2
        _emit 0xc7
        _emit 0x86
        _emit 0x98
        _emit 0x2b
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x85
        _emit 0xf6
        _emit 0xc7
        _emit 0x87
        _emit 0x94
        _emit 0x2b
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x74
        _emit 0x0e
        _emit 0x8b
        _emit 0x8f
        _emit 0x18
        _emit 0x01
        _emit 0x00
        _emit 0x00
        _emit 0x8b
        _emit 0x01
        _emit 0x8b
        _emit 0x50
        _emit 0x08
        _emit 0x56
        _emit 0xff
        _emit 0xd2
        _emit 0x5f
        _emit 0x8b
        _emit 0xc6
        _emit 0x5e
        _emit 0xc3
    }
}
