// [STAMPED] from FUN_0068b460.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x004d5350 (VA 0x008d5350)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x68b460 — adjustor thunk (ADD ECX, 0x4; JMP)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 44 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 c1 04 e9 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void adjustor_add() {
    __asm {
        add ecx, 4
        jmp target
    }
}
