// [STAMPED] from FUN_0040f5e0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00011480 (VA 0x00411480)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x40f5e0 — member-adjusted vtable tail-jmp (slot 0xc)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 5 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 49 04 8b 41 04 8b 50 0c 83 c1 04 ff e2

extern "C" __declspec(naked) void member_adjust_vtable_tailjmp() {
    __asm {
        mov ecx, [ecx + 4]
        mov eax, [ecx + 4]
        mov edx, [eax + 0xc]
        add ecx, 4
        jmp edx
    }
}
