// [STAMPED] from FUN_00546690.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0035aed0 (VA 0x0075aed0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x546690 — no-reloc cluster member (4B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 7 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 c8 ff c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x83
        _emit 0xc8
        _emit 0xff
        _emit 0xc3
    }
}
