// [STAMPED] from FUN_00b36620.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00a36250 (VA 0x00e36250)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xb36620 — int field setter at offset 0x24
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 44 24 04 89 41 24 c2 04 00

class C {
    int padding[9];
    int field;
public:
    void set_field(int);
};

void C::set_field(int v) { field = v; }
