// [STAMPED] from FUN_00e69b23.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00aa63f6 (VA 0x00ea63f6)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xe69b23 — SEH unwind helper (MOV ECX, [EBP+0x4]; ADD ECX, 0x54; JMP)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 11 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 4d 04 83 c1 54 e9 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void unwind_thunk() {
    __asm {
        mov ecx, [ebp + 4]
        add ecx, 84
        jmp target
    }
}
