// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x546690 — return -1 (int) — encoded as OR EAX, 0xff (sign-ext)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 7 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 c8 ff c3

class C { public: int neg_one(); };

int C::neg_one() { return -1; }
