// [STAMPED] from FUN_00e98c49.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00a99788 (VA 0x00e99788)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xe98c49 — unwind helper (MOV EAX, [EBP-0x28]; PUSH EAX; CALL)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 45 d8 50 e8 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void push_call_helper() {
    __asm {
        mov eax, [ebp - 40]
        push eax
        call target
    }
}
