// [STAMPED] from FUN_005a1e60.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x001a2180 (VA 0x005a2180)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5a1e60 — no-reloc cluster member (21B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 49 04 8b 01 8b 50 40 6a 65 ff d2 8b 10 8b c8 8b 42 1c ff e0

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x49
        _emit 0x04
        _emit 0x8b
        _emit 0x01
        _emit 0x8b
        _emit 0x50
        _emit 0x40
        _emit 0x6a
        _emit 0x65
        _emit 0xff
        _emit 0xd2
        _emit 0x8b
        _emit 0x10
        _emit 0x8b
        _emit 0xc8
        _emit 0x8b
        _emit 0x42
        _emit 0x1c
        _emit 0xff
        _emit 0xe0
    }
}
