// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xf2e470 — store const ptr to global, set ECX to global, tail-JMP (20B)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 10 byte-identical (or
// reloc-equivalent) members.
//
// Asm: c7 05 RR RR RR RR RR RR RR RR b9 RR RR RR RR e9 RR RR RR RR

extern void *g_dest;
extern void *g_value;
extern "C" void __cdecl tail_helper();

extern "C" __declspec(naked) void __cdecl store_ptr_to_global_then_tail_jmp() {
    __asm {
        mov dword ptr [g_dest], offset g_value
        mov ecx, offset g_dest
        jmp tail_helper
    }
}
