// [STAMPED] from FUN_00401020.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0079baf0 (VA 0x00b9baf0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x00001020 — 5-byte JMP-thunk forwarder.
// Reloc-aware cluster template — primary of a 617-member cluster.
// Each member is a single 5-byte JMP to a different target;
// auto-generated by the linker under /INCREMENTAL or by cl.exe under
// /O2 tail-call optimisation.
//
// Asm (5 bytes):
//   e9 ?? ?? ?? ??  JMP target
//
// Source pattern: free function that returns the result of another
// free function with the same signature, no locals, no other work.
// /O2 tail-call optimises the CALL+RET pair into a single JMP.

extern int target();

int forwarder() {
    return target();
}
