// [STAMPED] from FUN_00a27340.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00627e90 (VA 0x00a27e90)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xa27340 — no-reloc cluster member (8B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 5 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 79 08 00 0f 9f c0 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x83
        _emit 0x79
        _emit 0x08
        _emit 0x00
        _emit 0x0f
        _emit 0x9f
        _emit 0xc0
        _emit 0xc3
    }
}
