// [STAMPED] from FUN_00e5d020.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00aa5ed0 (VA 0x00ea5ed0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xe5d020 — unwind helper — 2-arg PUSH+PUSH+CALL ([EBP-0x14]+[EBP-0x1c])
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 55 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 45 ec 50 8b 4d e4 51 e8 RR RR RR RR 83 c4 08 c3

extern "C" int target();

extern "C" __declspec(naked) void unwind_2arg() {
    __asm {
        mov eax, [ebp - 20]
        push eax
        mov ecx, [ebp - 28]
        push ecx
        call target
        add esp, 8
        ret
    }
}
