// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5dc1d0 — thiscall→cdecl (this + 0x4) wrapper (ADD ECX,N; PUSH; CALL; POP; RET)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 c1 04 51 e8 RR RR RR RR 59 c3

extern "C" int target();

extern "C" __declspec(naked) void thiscall_advance_call() {
    __asm {
        add ecx, 4
        push ecx
        call target
        pop ecx
        ret
    }
}
