// [STAMPED] from FUN_00567270.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x007b03b0 (VA 0x00bb03b0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x567270 — byte field getter (AL) at offset 0x4
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8a 41 04 c3

class C {
    char padding[4];
    unsigned char field;
public:
    unsigned char get();
};

unsigned char C::get() { return field; }
