// [STAMPED] from FUN_00a6d8e0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x007837c0 (VA 0x00b837c0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xa6d8e0 — no-reloc cluster member (5B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: c6 41 28 01 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0xc6
        _emit 0x41
        _emit 0x28
        _emit 0x01
        _emit 0xc3
    }
}
