// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xc88530 — push-imm32 + call + ADD EAX,0x10 + ret
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 11 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 68 II II II II e8 RR RR RR RR 83 c0 10 c3

extern "C" int target(int);
extern "C" int the_imm;

extern "C" __declspec(naked) void wrapper_push_call_addret() {
    __asm {
        push offset the_imm
        call target
        add eax, 16
        ret
    }
}
