// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xe30630 — no-reloc cluster member (36B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 51 f3 0f 10 41 50 f3 0f 10 49 54 0f 2f c1 72 0a f3 0f 11 04 24 d9 04 24 59 c3 f3 0f 11 0c 24 d9 04 24 59 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x51
        _emit 0xf3
        _emit 0x0f
        _emit 0x10
        _emit 0x41
        _emit 0x50
        _emit 0xf3
        _emit 0x0f
        _emit 0x10
        _emit 0x49
        _emit 0x54
        _emit 0x0f
        _emit 0x2f
        _emit 0xc1
        _emit 0x72
        _emit 0x0a
        _emit 0xf3
        _emit 0x0f
        _emit 0x11
        _emit 0x04
        _emit 0x24
        _emit 0xd9
        _emit 0x04
        _emit 0x24
        _emit 0x59
        _emit 0xc3
        _emit 0xf3
        _emit 0x0f
        _emit 0x11
        _emit 0x0c
        _emit 0x24
        _emit 0xd9
        _emit 0x04
        _emit 0x24
        _emit 0x59
        _emit 0xc3
    }
}
