// [STAMPED] from FUN_00695390.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x008cca20 (VA 0x00ccca20)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x695390 — vtable tail-jmp via EAX (slot 0x28)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 01 8b 40 28 ff e0

extern "C" __declspec(naked) void vtable_tailjmp_eax() {
    __asm {
        mov eax, [ecx]
        mov eax, [eax + 0x28]
        jmp eax
    }
}
