// [STAMPED] from FUN_00e5b2df.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00a77768 (VA 0x00e77768)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xe5b2df — SEH unwind helper (MOV ECX, [EBP-0x14]; ADD ECX, 0x28; JMP)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 12 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 4d ec 83 c1 28 e9 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void unwind_thunk() {
    __asm {
        mov ecx, [ebp - 20]
        add ecx, 40
        jmp target
    }
}
