// [STAMPED] from FUN_00abecc0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00a31c40 (VA 0x00e31c40)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xabecc0 — no-reloc cluster member (42B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 8 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 55 8b ec 83 e4 f0 8b 55 08 0f 28 0a 0f 28 01 0f 59 c1 0f 28 c8 0f c6 c8 aa 0f 58 c8 0f c6 c0 55 0f 58 c8 0f 29 08 8b e5 5d c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x55
        _emit 0x8b
        _emit 0xec
        _emit 0x83
        _emit 0xe4
        _emit 0xf0
        _emit 0x8b
        _emit 0x55
        _emit 0x08
        _emit 0x0f
        _emit 0x28
        _emit 0x0a
        _emit 0x0f
        _emit 0x28
        _emit 0x01
        _emit 0x0f
        _emit 0x59
        _emit 0xc1
        _emit 0x0f
        _emit 0x28
        _emit 0xc8
        _emit 0x0f
        _emit 0xc6
        _emit 0xc8
        _emit 0xaa
        _emit 0x0f
        _emit 0x58
        _emit 0xc8
        _emit 0x0f
        _emit 0xc6
        _emit 0xc0
        _emit 0x55
        _emit 0x0f
        _emit 0x58
        _emit 0xc8
        _emit 0x0f
        _emit 0x29
        _emit 0x08
        _emit 0x8b
        _emit 0xe5
        _emit 0x5d
        _emit 0xc3
    }
}
