// [STAMPED] from FUN_00a58930.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00658d60 (VA 0x00a58d60)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xa58930 — member-at-+0x10 vcall[+0x18] tail-JMP into EAX+0x30 (18B)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 10 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 49 10 8b 01 8b 50 18 ff d2 8d 48 30 e9 RR RR RR RR

extern "C" void __cdecl tail_helper();

extern "C" __declspec(naked) void __cdecl member10_vcall6_then_tail_jmp_eax30() {
    __asm {
        mov ecx, dword ptr [ecx + 0x10]
        mov eax, dword ptr [ecx]
        mov edx, dword ptr [eax + 0x18]
        call edx
        lea ecx, [eax + 0x30]
        jmp tail_helper
    }
}
