// [STAMPED] from FUN_005a0220.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x001a0c60 (VA 0x005a0c60)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5a0220 — member-vtable tail-jmp via EAX (slot 0x44)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 6 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 49 04 8b 01 8b 40 44 ff e0

extern "C" __declspec(naked) void member_vtable_tailjmp_eax() {
    __asm {
        mov ecx, [ecx + 4]
        mov eax, [ecx]
        mov eax, [eax + 0x44]
        jmp eax
    }
}
