// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xa2c670 — global SSO accessor (size>=0x10 ? heap_data : inline_buf)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 14 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 3d GG GG GG GG 10 a1 GG GG GG GG 73 05 b8 GG GG GG GG c3

extern "C" int the_size;
extern "C" int the_data;
extern "C" int the_inline;

extern "C" __declspec(naked) void sso_accessor() {
    __asm {
        cmp dword ptr [the_size], 0x10
        mov eax, dword ptr [the_data]
        jnb is_heap
        mov eax, offset the_inline
    is_heap:
        ret
    }
}
