// [STAMPED] from FUN_007a42f0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00579f80 (VA 0x00979f80)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x7a42f0 — no-reloc cluster member (7B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: d9 81 8c 05 00 00 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0xd9
        _emit 0x81
        _emit 0x8c
        _emit 0x05
        _emit 0x00
        _emit 0x00
        _emit 0xc3
    }
}
