// [STAMPED] from FUN_007a37a0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x003a37e0 (VA 0x007a37e0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x7a37a0 — no-reloc cluster member (60B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: f3 0f 10 05 d4 7d fb 00 33 c0 f3 0f 11 41 1c ba 03 00 00 00 88 41 30 89 41 04 89 41 18 89 51 20 89 51 28 89 41 24 89 41 2c 66 0f ef c0 66 0f d6 41 08 66 0f ef c0 66 0f d6 41 10 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0xf3
        _emit 0x0f
        _emit 0x10
        _emit 0x05
        _emit 0xd4
        _emit 0x7d
        _emit 0xfb
        _emit 0x00
        _emit 0x33
        _emit 0xc0
        _emit 0xf3
        _emit 0x0f
        _emit 0x11
        _emit 0x41
        _emit 0x1c
        _emit 0xba
        _emit 0x03
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x88
        _emit 0x41
        _emit 0x30
        _emit 0x89
        _emit 0x41
        _emit 0x04
        _emit 0x89
        _emit 0x41
        _emit 0x18
        _emit 0x89
        _emit 0x51
        _emit 0x20
        _emit 0x89
        _emit 0x51
        _emit 0x28
        _emit 0x89
        _emit 0x41
        _emit 0x24
        _emit 0x89
        _emit 0x41
        _emit 0x2c
        _emit 0x66
        _emit 0x0f
        _emit 0xef
        _emit 0xc0
        _emit 0x66
        _emit 0x0f
        _emit 0xd6
        _emit 0x41
        _emit 0x08
        _emit 0x66
        _emit 0x0f
        _emit 0xef
        _emit 0xc0
        _emit 0x66
        _emit 0x0f
        _emit 0xd6
        _emit 0x41
        _emit 0x10
        _emit 0xc3
    }
}
