// [STAMPED] from FUN_0089d210.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0049d260 (VA 0x0089d260)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x89d210 — no-reloc cluster member (15B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 49 08 33 c0 3b 0d 78 c7 30 01 0f 95 c0 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x49
        _emit 0x08
        _emit 0x33
        _emit 0xc0
        _emit 0x3b
        _emit 0x0d
        _emit 0x78
        _emit 0xc7
        _emit 0x30
        _emit 0x01
        _emit 0x0f
        _emit 0x95
        _emit 0xc0
        _emit 0xc3
    }
}
