// [STAMPED] from FUN_0075b180.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00925c50 (VA 0x00d25c50)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x75b180 — empty `__thiscall` 7-arg method (RET 0x1c)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 6 byte-identical (or
// reloc-equivalent) members.
//
// Asm: c2 1c 00

class C { public: void empty7(int, int, int, int, int, int, int); };
void C::empty7(int, int, int, int, int, int, int) {}
