// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xb29a40 — push-imm32 + indirect-CALL [import] + ret (Win32 API trampoline)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 10 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 68 II II II II ff 15 GG GG GG GG c3

extern "C" __declspec(dllimport) void __stdcall import_target(int);
extern "C" int the_imm;

extern "C" __declspec(naked) void api_trampoline() {
    __asm {
        push offset the_imm
        call dword ptr [import_target]
        ret
    }
}
