// [STAMPED] from FUN_0044e1d0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00a37ca0 (VA 0x00e37ca0)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x44e1d0 — 2-arg passthrough wrapper (PUSH arg2; PUSH arg1; CALL; ADD ESP,8; RET 8)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 44 24 08 8b 4c 24 04 50 51 e8 RR RR RR RR 83 c4 08 c2 08 00

extern "C" int target();

extern "C" __declspec(naked) void wrapper_2arg_passthrough() {
    __asm {
        mov eax, [esp + 8]
        mov ecx, [esp + 4]
        push eax
        push ecx
        call target
        add esp, 8
        ret 8
    }
}
