// [STAMPED] from FUN_004048a0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x005af130 (VA 0x009af130)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x4048a0 — __stdcall arg-shuffler (3 dword args + 1 byte)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 51 8b 54 24 10 c6 04 24 00 8b 04 24 50 8b 44 24 14 52 8b 54 24 10 51 8b 4c 24 18 50 51 52 e8 RR RR RR RR 83 c4 1c c2 0c 00

extern "C" int target();

extern "C" __declspec(naked) void arg_shuffler() {
    __asm {
        push ecx
        mov edx, [esp + 0x10]
        mov byte ptr [esp], 0
        mov eax, [esp]
        push eax
        mov eax, [esp + 0x14]
        push edx
        mov edx, [esp + 0x10]
        push ecx
        mov ecx, [esp + 0x18]
        push eax
        push ecx
        push edx
        call target
        add esp, 0x1c
        ret 12
    }
}
