// [STAMPED] from FUN_00c1f3c0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x009e8a30 (VA 0x00de8a30)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xc1f3c0 — address-of-member getter at offset 0x1c (LEA)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8d 41 1c c3

class C {
    char padding[28];
    int field;
public:
    int *get_field_addr();
};

int *C::get_field_addr() { return &field; }
