// [STAMPED] from FUN_00e89a9b.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00ab9948 (VA 0x00eb9948)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xe89a9b — SEH unwind helper (MOV ECX, [EBP-0x10]; ADD ECX, 0x2c0; JMP)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 4d f0 81 c1 000002c0 e9 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void unwind_thunk() {
    __asm {
        mov ecx, [ebp - 16]
        add ecx, 704
        jmp target
    }
}
