// [STAMPED] from FUN_00830fc0.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x009f4990 (VA 0x00df4990)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x830fc0 — no-reloc cluster member (60B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 6 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 41 14 56 57 0f b6 78 10 85 ff be 14 00 00 00 8d 50 14 7e 1b 53 8b 59 3c 8d a4 24 00 00 00 00 0f b6 42 04 03 c3 03 f0 03 d0 83 ef 01 75 f1 5b 8d 46 03 83 e0 fc 03 41 14 5f 5e c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x41
        _emit 0x14
        _emit 0x56
        _emit 0x57
        _emit 0x0f
        _emit 0xb6
        _emit 0x78
        _emit 0x10
        _emit 0x85
        _emit 0xff
        _emit 0xbe
        _emit 0x14
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x8d
        _emit 0x50
        _emit 0x14
        _emit 0x7e
        _emit 0x1b
        _emit 0x53
        _emit 0x8b
        _emit 0x59
        _emit 0x3c
        _emit 0x8d
        _emit 0xa4
        _emit 0x24
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x0f
        _emit 0xb6
        _emit 0x42
        _emit 0x04
        _emit 0x03
        _emit 0xc3
        _emit 0x03
        _emit 0xf0
        _emit 0x03
        _emit 0xd0
        _emit 0x83
        _emit 0xef
        _emit 0x01
        _emit 0x75
        _emit 0xf1
        _emit 0x5b
        _emit 0x8d
        _emit 0x46
        _emit 0x03
        _emit 0x83
        _emit 0xe0
        _emit 0xfc
        _emit 0x03
        _emit 0x41
        _emit 0x14
        _emit 0x5f
        _emit 0x5e
        _emit 0xc3
    }
}
