// [STAMPED] from FUN_0082f860.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x009e9660 (VA 0x00de9660)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x82f860 — no-reloc cluster member (25B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 41 04 8b 88 d4 01 00 00 85 c9 75 05 33 c0 c2 08 00 8b 11 8b 52 40 ff e2

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x41
        _emit 0x04
        _emit 0x8b
        _emit 0x88
        _emit 0xd4
        _emit 0x01
        _emit 0x00
        _emit 0x00
        _emit 0x85
        _emit 0xc9
        _emit 0x75
        _emit 0x05
        _emit 0x33
        _emit 0xc0
        _emit 0xc2
        _emit 0x08
        _emit 0x00
        _emit 0x8b
        _emit 0x11
        _emit 0x8b
        _emit 0x52
        _emit 0x40
        _emit 0xff
        _emit 0xe2
    }
}
