// [STAMPED] from FUN_005a0240.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00672590 (VA 0x00a72590)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5a0240 — no-reloc cluster member (10B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 7 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 49 04 8b 01 8b 40 4c ff e0

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x49
        _emit 0x04
        _emit 0x8b
        _emit 0x01
        _emit 0x8b
        _emit 0x40
        _emit 0x4c
        _emit 0xff
        _emit 0xe0
    }
}
