// [STAMPED] from FUN_004dee40.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x005c9f60 (VA 0x009c9f60)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x4dee40 — multi-inheritance `this`-adjustor (SUB ECX, 0xb4; JMP)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 13 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 81 e9 000000b4 (LE) e9 RR RR RR RR

extern "C" int target();

extern "C" __declspec(naked) void adjustor_thunk() {
    __asm {
        sub ecx, 180
        jmp target
    }
}
