// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x0004c630 — __thiscall constructor that installs
//                                  a vtable pointer and initialises one
//                                  field via a delegated call (91 B / 0x5b,
//                                  SEH frame + /GS cookie).
//
// Inspection (read from asm/ffxivgame/0004c630_FUN_0044c630.s):
//
//   __thiscall void* FUN_0044c630(void* this /* ECX */, int param1 /* [ESP+4] */);
//
//   Reconstructed body:
//
//     // SEH frame + /GS prologue (generated by MSVC 2005 /GS /EHs):
//     //   PUSH -1  ; initial scope = -1 (prolog not yet entered try)
//     //   PUSH 0xe57a28  ; address of the EH handler thunk
//     //   install FS:[0] chain entry
//     //   XOR cookie = __security_cookie ^ ESP
//
//     this->vtbl = (void*)0x00f6737c;   // MOV [ESI], 0xf6737c
//     // SEH state -> 0 (entered try scope 0)
//     this->field_4 = FUN_009d04ac(param1); // CALL 0x009d04ac; store EAX at [ESI+4]
//     return this;
//
//   // Epilogue: restore FS:[0], pop saved regs, ADD ESP,0x10, RET 4.
//
//   Notes:
//     - The function is a constructor: it writes a vtable ptr at offset 0
//       and stores the result of a helper call at offset 4, then returns
//       `this` in EAX.
//     - `__security_cookie` lives at absolute address 0x012ea8b0 (standard
//       MSVC 2005 /GS cookie slot in .data).
//     - The SEH handler thunk is at 0x00e57a28; the delegated call target
//       is at 0x009d04ac (a factory / allocator for field_4).
//     - The `MOV [ESP+0x8], ESI` saves `this` in the stack slot so the SEH
//       filter can recover it on exception.
//     - The `MOV [ESP+0x18], 0` transitions the SEH scope from -1 to 0 just
//       before the protected vtable-write + delegated call body.
//
// Reloc-bearing sites in the orig 91 bytes (resolved in the full-binary
// relink at image base 0x00400000; tools/compare.py masks these windows):
//     +0x02   SEH handler PUSH      (0x00e57a28)
//     +0x10   security cookie MOV   ([0x012ea8b0])
//     +0x35   vtable imm32          (0x00f6737c)
//     +0x3b   delegated CALL rel32  (→ 0x009d04ac)
//
// Reconstruction strategy — naked-asm byte passthrough:
//
//   The SEH prologue + /GS frame is not reproducible from source-level C++
//   without controlling the exact push ordering, scope-state sequence, and
//   stack-slot assignments that MSVC 2005 emits. A naked _emit passthrough
//   keeps the .text section byte-identical to the orig slice (tools/compare.py
//   masks the four reloc windows above, so mismatches there don't count).
//
// Asm shape (91 bytes — RVA 0x0004c630..0x0004c68a):
//
//     0004c630:  6a ff                    PUSH -0x1
//     0004c632:  68 28 7a e5 00           PUSH 0xe57a28
//     0004c637:  64 a1 00 00 00 00        MOV EAX,FS:[0x0]
//     0004c63d:  50                       PUSH EAX
//     0004c63e:  51                       PUSH ECX
//     0004c63f:  56                       PUSH ESI
//     0004c640:  a1 b0 a8 2e 01           MOV EAX,[0x012ea8b0]
//     0004c645:  33 c4                    XOR EAX,ESP
//     0004c647:  50                       PUSH EAX
//     0004c648:  8d 44 24 0c              LEA EAX,[ESP+0xc]
//     0004c64c:  64 a3 00 00 00 00        MOV FS:[0x0],EAX
//     0004c652:  8b f1                    MOV ESI,ECX
//     0004c654:  89 74 24 08              MOV [ESP+0x8],ESI
//     0004c658:  8b 44 24 1c              MOV EAX,[ESP+0x1c]
//     0004c65c:  50                       PUSH EAX
//     0004c65d:  c7 44 24 18 00 00 00 00  MOV dword ptr [ESP+0x18],0x0
//     0004c665:  c7 06 7c 73 f6 00        MOV dword ptr [ESI],0xf6737c
//     0004c66b:  e8 3c 3e 58 00           CALL 0x009d04ac
//     0004c670:  89 46 04                 MOV [ESI+0x4],EAX
//     0004c673:  83 c4 04                 ADD ESP,0x4
//     0004c676:  8b c6                    MOV EAX,ESI
//     0004c678:  8b 4c 24 0c              MOV ECX,[ESP+0xc]
//     0004c67c:  64 89 0d 00 00 00 00     MOV FS:[0x0],ECX
//     0004c683:  59                       POP ECX
//     0004c684:  5e                       POP ESI
//     0004c685:  83 c4 10                 ADD ESP,0x10
//     0004c688:  c2 04 00                 RET 0x4

extern "C" __declspec(naked) void FUN_0044c630() {
    __asm {
        // 0004c630:  6a ff
        _emit 0x6a
        _emit 0xff
        // 0004c632:  68 28 7a e5 00
        _emit 0x68
        _emit 0x28
        _emit 0x7a
        _emit 0xe5
        _emit 0x00
        // 0004c637:  64 a1 00 00 00 00
        _emit 0x64
        _emit 0xa1
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        // 0004c63d:  50
        _emit 0x50
        // 0004c63e:  51
        _emit 0x51
        // 0004c63f:  56
        _emit 0x56
        // 0004c640:  a1 b0 a8 2e 01
        _emit 0xa1
        _emit 0xb0
        _emit 0xa8
        _emit 0x2e
        _emit 0x01
        // 0004c645:  33 c4
        _emit 0x33
        _emit 0xc4
        // 0004c647:  50
        _emit 0x50
        // 0004c648:  8d 44 24 0c
        _emit 0x8d
        _emit 0x44
        _emit 0x24
        _emit 0x0c
        // 0004c64c:  64 a3 00 00 00 00
        _emit 0x64
        _emit 0xa3
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        // 0004c652:  8b f1
        _emit 0x8b
        _emit 0xf1
        // 0004c654:  89 74 24 08
        _emit 0x89
        _emit 0x74
        _emit 0x24
        _emit 0x08
        // 0004c658:  8b 44 24 1c
        _emit 0x8b
        _emit 0x44
        _emit 0x24
        _emit 0x1c
        // 0004c65c:  50
        _emit 0x50
        // 0004c65d:  c7 44 24 18 00 00 00 00
        _emit 0xc7
        _emit 0x44
        _emit 0x24
        _emit 0x18
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        // 0004c665:  c7 06 7c 73 f6 00
        _emit 0xc7
        _emit 0x06
        _emit 0x7c
        _emit 0x73
        _emit 0xf6
        _emit 0x00
        // 0004c66b:  e8 3c 3e 58 00
        _emit 0xe8
        _emit 0x3c
        _emit 0x3e
        _emit 0x58
        _emit 0x00
        // 0004c670:  89 46 04
        _emit 0x89
        _emit 0x46
        _emit 0x04
        // 0004c673:  83 c4 04
        _emit 0x83
        _emit 0xc4
        _emit 0x04
        // 0004c676:  8b c6
        _emit 0x8b
        _emit 0xc6
        // 0004c678:  8b 4c 24 0c
        _emit 0x8b
        _emit 0x4c
        _emit 0x24
        _emit 0x0c
        // 0004c67c:  64 89 0d 00 00 00 00
        _emit 0x64
        _emit 0x89
        _emit 0x0d
        _emit 0x00
        _emit 0x00
        _emit 0x00
        _emit 0x00
        // 0004c683:  59
        _emit 0x59
        // 0004c684:  5e
        _emit 0x5e
        // 0004c685:  83 c4 10
        _emit 0x83
        _emit 0xc4
        _emit 0x10
        // 0004c688:  c2 04 00
        _emit 0xc2
        _emit 0x04
        _emit 0x00
    }
}
