// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xbd49e0 — no-reloc cluster member (23B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 44 24 04 83 c9 ff 66 89 08 66 89 48 02 66 89 48 04 66 89 48 06 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x44
        _emit 0x24
        _emit 0x04
        _emit 0x83
        _emit 0xc9
        _emit 0xff
        _emit 0x66
        _emit 0x89
        _emit 0x08
        _emit 0x66
        _emit 0x89
        _emit 0x48
        _emit 0x02
        _emit 0x66
        _emit 0x89
        _emit 0x48
        _emit 0x04
        _emit 0x66
        _emit 0x89
        _emit 0x48
        _emit 0x06
        _emit 0xc3
    }
}
