// [STAMPED] from FUN_00874590.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x00a23850 (VA 0x00e23850)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x874590 — no-reloc cluster member (4B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8a 41 14 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8a
        _emit 0x41
        _emit 0x14
        _emit 0xc3
    }
}
