// [STAMPED] from FUN_00b09d10.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0070f310 (VA 0x00b0f310)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0xb09d10 — no-reloc cluster member (25B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 55 8b ec 83 e4 f0 8b 55 08 0f 28 01 0f 28 0a 0f 5f c1 0f 29 00 8b e5 5d c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x55
        _emit 0x8b
        _emit 0xec
        _emit 0x83
        _emit 0xe4
        _emit 0xf0
        _emit 0x8b
        _emit 0x55
        _emit 0x08
        _emit 0x0f
        _emit 0x28
        _emit 0x01
        _emit 0x0f
        _emit 0x28
        _emit 0x0a
        _emit 0x0f
        _emit 0x5f
        _emit 0xc1
        _emit 0x0f
        _emit 0x29
        _emit 0x00
        _emit 0x8b
        _emit 0xe5
        _emit 0x5d
        _emit 0xc3
    }
}
