// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x5386b0 — push-arg + push-imm32 + call + ret4 (1-arg stdcall wrapper, prepended literal)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 12 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 44 24 04 50 68 II II II II e8 RR RR RR RR c2 04 00

extern "C" void __stdcall target(void *, int);
extern "C" int the_imm;

extern "C" __declspec(naked) void __stdcall wrapper_push_imm32(int) {
    __asm {
        mov eax, [esp + 4]
        push eax
        push offset the_imm
        call target
        ret 4
    }
}
