// [STAMPED] from FUN_0041d1b1.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x000208b8 (VA 0x004208b8)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x41d1b1 — set global value (from arg1)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 5 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 44 24 04 a3 GG GG GG GG c3

extern "C" int the_global;

extern "C" void set_global(int v) { the_global = v; }
