// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by tools/build_struct_layouts.py — do not edit by hand.
// Field layout sourced from FFXIVLegacyClientStructs (MIT), joined to this
// binary by RTTI vtable name. Addresses there are from a different build, so
// only the *layout* (offsets/names/types) is authoritative here. Fields are
// offset-sorted with explicit padding so member offsets are exact (x86, 4-byte
// pointers); undocumented gaps are `_padNN` filler. Fields the source places at
// an already-occupied offset are emitted as comments to keep the layout valid.
//
// Class:   Application::Scene::Actor::System::TargetActor
// Size:    2496 (0x9c0)
// vtable:  0xbb83cc
#pragma once
#include <cstdint>

// Application::Scene::Actor::System::TargetActor
struct Application_Scene_Actor_System_TargetActor {
    /* 0x0     */ uint32_t   VTable;
    /* 0x4     */ float      BaseFieldA;
    /* 0x8     */ float      BaseFieldB;
    /* 0xc     */ float      BaseFieldC;
    // @0xf byte InitFlag  (overlaps prior field; not emitted)
    /* 0x10    */ int32_t    InvalidId;
    uint8_t _pad0[0xbc];
    /* 0xd0    */ float      TransformFloat;
    uint8_t _pad1[0x50];
    /* 0x124   */ uint32_t   ReferenceA;
    /* 0x128   */ uint32_t   ReferenceB;
    /* 0x12c   */ uint32_t   ReferenceC;
    /* 0x130   */ uint32_t   ReferenceD;
    /* 0x134   */ uint32_t   ReferenceE;
    /* 0x138   */ uint32_t   ReferenceF;
    /* 0x13c   */ uint32_t   ReferenceG;
    /* 0x140   */ uint32_t   SubObject_0140;
    uint8_t _pad2[0x24];
    /* 0x168   */ uint8_t    StateFlags;
    /* 0x169   */ uint8_t    StateCleared;
    uint8_t _pad3[0xa];
    /* 0x174   */ uint32_t   Field_0174;
    uint8_t _pad4[0xc];
    /* 0x184   */ uint32_t   ResourceA;
    uint8_t _pad5[0x4];
    /* 0x18c   */ uint32_t   ResourceB;
    uint8_t _pad6[0x18];
    /* 0x1a8   */ uint32_t   Field_01A8;
    uint8_t _pad7[0xc];
    /* 0x1b8   */ uint32_t   TimingA;
    uint8_t _pad8[0x8];
    /* 0x1c4   */ uint32_t   TimingB;
    /* 0x1c8   */ uint32_t   TimingC;
    /* 0x1cc   */ float      TimingFloatA;
    /* 0x1d0   */ float      TimingFloatB;
    /* 0x1d4   */ float      TimingFloatC;
    /* 0x1d8   */ float      TimingFloatD;
    uint8_t _pad9[0x4];
    /* 0x1e0   */ uint32_t   TimingD;
    uint8_t _pad10[0x8];
    /* 0x1ec   */ uint32_t   TimingE;
    uint8_t _pad11[0x8];
    /* 0x1f8   */ uint32_t   TimingF;
    uint8_t _pad12[0x34];
    /* 0x230   */ float      RenderFloat;
    uint8_t _pad13[0xc];
    /* 0x240   */ uint8_t    RenderFlag;
    uint8_t _pad14[0x6b];
    /* 0x2ac   */ float      VisualFloat;
    uint8_t _pad15[0x134];
    /* 0x3e4   */ float      ActionFloat;
    /* 0x3e8   */ uint32_t   ActionState;
    uint8_t _pad16[0x4];
    /* 0x3f0   */ uint32_t   ActionConfig;
    uint8_t _pad17[0x8c];
    /* 0x480   */ uint8_t    TaskFlag;
    uint8_t _pad18[0x48f];
    /* 0x910   */ uint32_t   PropertyArrayBase;
    /* 0x914   */ uint32_t   PropertyArray;
    uint8_t _pad19[0xa8];
};
