// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// GENERATED by tools/build_struct_layouts.py — do not edit by hand.
// Field layout sourced from FFXIVLegacyClientStructs (MIT), joined to this
// binary by RTTI vtable name. Addresses there are from a different build, so
// only the *layout* (offsets/names/types) is authoritative here. Fields are
// offset-sorted with explicit padding so member offsets are exact (x86, 4-byte
// pointers); undocumented gaps are `_padNN` filler. Fields the source places at
// an already-occupied offset are emitted as comments to keep the layout valid.
//
// Class:   SQEX::CDev::Engine::Fw::SceneObject::Actor
// Size:    256 (0x100)
// vtable:  0xc9ca94
#pragma once
#include <cstdint>

// SQEX::CDev::Engine::Fw::SceneObject::Actor
struct SQEX_CDev_Engine_Fw_SceneObject_Actor {
    /* 0x0     */ uint32_t   VTable;
    uint8_t _pad0[0x44];
    /* 0x48    */ uint32_t   SubObject;
    uint8_t _pad1[0xb4];
};
