#!/usr/bin/env python3
# meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
# Copyright (C) 2026  Samuel Stegall
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Auto-derive matching .cpp templates from cluster byte patterns.

For each multi-member cluster in `<bin>.clusters.json` and
`<bin>.clusters_reloc.json`, examine the cluster representative's
bytes and try to recognise a known idiom (empty method, constant
return, accessor, setter, this-call wrapper, etc.). When a pattern
matches, emit a canonical C++ template at
`src/<bin>/_rosetta/FUN_<rva>.cpp` for the representative; the
companion `tools/stamp_clusters.py` then expands the template to
every byte-identical (or reloc-equivalent) cluster sibling.

Recognised idioms (in evaluation order — most specific first):

  RET                              `c3`
  RET imm16                        `c2 NN 00`        (empty N/4-arg method)
  return 0 (int)                   `33 c0 c3`        / with arg cleanup `33 c0 c2 NN 00`
  return false (bool, 8-bit)       `32 c0 c3`        / `32 c0 c2 NN 00`
  return true (bool, 8-bit)        `b0 01 c3`        / `b0 01 c2 NN 00`
  return *this                     `8b c1 c3`
  return imm8 (signed)             `b0 NN c3`        (NN ≠ 0,1)
  int-getter at offset NN          `8b 41 NN c3`     (NN ≤ 0x7f)
  int-getter at long offset        `8b 81 NN NN NN NN c3`
  byte zero-ext getter             `0f b6 41 NN c3`  (returns int from byte)
  byte sign-ext getter             `0f be 41 NN c3`
  short zero-ext getter            `0f b7 41 NN c3`
  short sign-ext getter            `0f bf 41 NN c3`
  bit-flag getter                  `8a 41 NN 24 01 c2 08 00`  (returns u8 & 1)
  chained ptr getter               `8b 41 NN 8b 40 MM c3`
  int setter at offset NN          `8b 44 24 04 89 41 NN c2 04 00`
  this-call wrapper (return self)  `56 8b f1 e8 RR RR RR RR 8b c6 5e c2 04 00`
  singleton tail-call              `b9 RR RR RR RR e9 RR RR RR RR`
  JMP-thunk forwarder              `e9 RR RR RR RR`
  scalar deleting destructor       `56 8b f1 e8 RR RR RR RR f6 44 24 08 01 74 09 56 e8 RR RR RR RR 83 c4 04 8b c6 5e c2 04 00`

`RR` denotes a relocation byte (cluster member-specific, wildcarded
by the reloc-aware diff in `compare.py`). `NN` and `MM` are immediate
values that the deriver reads from the cluster's bytes and bakes into
the generated template.

Reads:
  build/easy_wins/<binary>.clusters.json
  build/easy_wins/<binary>.clusters_reloc.json (optional)

Writes:
  src/<binary>/_rosetta/FUN_<rva>.cpp  (one per recognised cluster)

Skip rule: never overwrite an existing .cpp.

Usage:
  tools/derive_templates.py [binary]                 # default ffxivgame
  tools/derive_templates.py --all
  tools/derive_templates.py ffxivgame --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
EASY_WINS = REPO_ROOT / "build" / "easy_wins"
ASM_ROOT = REPO_ROOT / "asm"

KNOWN_BINARIES = ("ffxivgame", "ffxivlogin", "ffxivboot", "ffxivconfig", "ffxivupdater")

LICENSE = """\
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//"""

RE_INSTR = re.compile(
    r"^\s*[0-9a-fA-F]+:\s+((?:[0-9a-fA-F][0-9a-fA-F]\s+)+)\s",
    re.MULTILINE,
)


def read_function_bytes(asm_path: Path) -> bytes | None:
    if not asm_path.exists():
        return None
    text = asm_path.read_text(errors="replace")
    body = bytearray()
    for m in RE_INSTR.finditer(text):
        for tok in m.group(1).split():
            body.append(int(tok, 16))
    return bytes(body)


# -----------------------------------------------------------------------------
# Pattern matchers — each returns (template_text, idiom_name) on match,
# or None on no-match. Each takes the cluster's representative bytes
# and produces a complete .cpp source.
# -----------------------------------------------------------------------------


def _header(va: int, idiom: str, asm_summary: str, n_members: int) -> str:
    return (
        f"{LICENSE}\n"
        f"// SPDX-License-Identifier: AGPL-3.0-or-later\n"
        f"//\n"
        f"// FUNCTION: ffxivgame {hex(va)} — {idiom}\n"
        f"// Auto-generated by tools/derive_templates.py.\n"
        f"// Cluster representative — covers {n_members} byte-identical (or\n"
        f"// reloc-equivalent) members.\n"
        f"//\n"
        f"// Asm: {asm_summary}\n"
    )


def try_empty_void(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\xc3":
        src = (
            _header(va, "empty zero-arg method (RET)", "c3", n)
            + "\nclass C { public: void empty(); };\n"
              "void C::empty() {}\n"
        )
        return (src, "empty 0-arg")
    return None


def try_empty_n_arg(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if len(body) == 3 and body[0] == 0xc2 and body[2] == 0x00:
        nbytes = body[1]
        if nbytes == 0 or nbytes % 4 != 0:
            return None
        nargs = nbytes // 4
        args = ", ".join(["int"] * nargs)
        src = (
            _header(va, f"empty `__thiscall` {nargs}-arg method (RET 0x{nbytes:x})",
                    f"c2 {nbytes:02x} 00", n)
            + f"\nclass C {{ public: void empty{nargs}({args}); }};\n"
              f"void C::empty{nargs}({args}) {{}}\n"
        )
        return (src, f"empty {nargs}-arg")
    return None


def try_return_zero_int(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\x33\xc0\xc3":
        src = (
            _header(va, "return 0 (int)", "33 c0 c3", n)
            + "\nclass C { public: int zero() const; };\n"
              "int C::zero() const { return 0; }\n"
        )
        return (src, "return 0")
    if len(body) == 5 and body[:2] == b"\x33\xc0" and body[2] == 0xc2 and body[4] == 0x00:
        nbytes = body[3]
        if nbytes == 0 or nbytes % 4 != 0:
            return None
        nargs = nbytes // 4
        args = ", ".join(["int"] * nargs)
        src = (
            _header(va, f"return 0 (int) — {nargs}-arg",
                    f"33 c0 c2 {nbytes:02x} 00", n)
            + f"\nclass C {{ public: int zero({args}); }};\n"
              f"int C::zero({args}) {{ return 0; }}\n"
        )
        return (src, f"return 0 ({nargs}-arg)")
    return None


def try_return_false_bool(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\x32\xc0\xc3":
        src = (
            _header(va, "return false (bool, 8-bit)", "32 c0 c3", n)
            + "\nclass C { public: unsigned char no() const; };\n"
              "unsigned char C::no() const { unsigned char r = 0; return r; }\n"
        )
        return (src, "return false")
    if len(body) == 5 and body[:2] == b"\x32\xc0" and body[2] == 0xc2 and body[4] == 0x00:
        nbytes = body[3]
        if nbytes == 0 or nbytes % 4 != 0:
            return None
        nargs = nbytes // 4
        args = ", ".join(["int"] * nargs)
        src = (
            _header(va, f"return false (bool, 8-bit) — {nargs}-arg",
                    f"32 c0 c2 {nbytes:02x} 00", n)
            + f"\nclass C {{ public: unsigned char no({args}); }};\n"
              f"unsigned char C::no({args}) {{ unsigned char r = 0; return r; }}\n"
        )
        return (src, f"return false ({nargs}-arg)")
    return None


def try_return_true_bool(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\xb0\x01\xc3":
        src = (
            _header(va, "return true (bool, 8-bit)", "b0 01 c3", n)
            + "\nclass C { public: unsigned char yes() const; };\n"
              "unsigned char C::yes() const { unsigned char r = 1; return r; }\n"
        )
        return (src, "return true")
    if len(body) == 5 and body[:2] == b"\xb0\x01" and body[2] == 0xc2 and body[4] == 0x00:
        nbytes = body[3]
        if nbytes == 0 or nbytes % 4 != 0:
            return None
        nargs = nbytes // 4
        args = ", ".join(["int"] * nargs)
        src = (
            _header(va, f"return true (bool, 8-bit) — {nargs}-arg",
                    f"b0 01 c2 {nbytes:02x} 00", n)
            + f"\nclass C {{ public: unsigned char yes({args}); }};\n"
              f"unsigned char C::yes({args}) {{ unsigned char r = 1; return r; }}\n"
        )
        return (src, f"return true ({nargs}-arg)")
    return None


def try_return_this(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\x8b\xc1\xc3":
        src = (
            _header(va, "return *this (MOV EAX,ECX; RET)", "8b c1 c3", n)
            + "\nclass C { public: C *identity(); };\n"
              "C *C::identity() { return this; }\n"
        )
        return (src, "return *this")
    return None


def _padding_for_offset(offset: int, base_t: str = "int") -> str:
    """Generate `T padding[N];` for byte-offset `offset` of base T (4 B for int)."""
    if offset == 0:
        return ""
    base_size = 4 if base_t == "int" else (1 if base_t == "char" else 4)
    if offset % base_size != 0:
        # Use char[] for non-aligned offsets
        return f"char padding[{offset}];"
    n = offset // base_size
    return f"{base_t} padding[{n}];"


def try_int_getter(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 4-byte form: 8b 41 NN c3 — MOV EAX, [ECX+NN]; RET
    if len(body) == 4 and body[0] == 0x8b and body[1] == 0x41 and body[3] == 0xc3:
        offset = body[2]
        if offset == 0:
            # 8b 41 00 wouldn't happen — that'd be 8b 01. Skip.
            return None
        pad = _padding_for_offset(offset, "int")
        if pad and offset % 4 != 0:
            # Non-aligned — skip; rare and source generation would be tricky.
            return None
        src = (
            _header(va, f"int field getter at offset 0x{offset:x}",
                    f"8b 41 {offset:02x} c3", n)
            + f"\nclass C {{\n"
            + (f"    {pad}\n" if pad else "")
            + f"    int field;\npublic:\n    int get_field();\n}};\n\n"
              f"int C::get_field() {{ return field; }}\n"
        )
        return (src, f"int getter @ 0x{offset:x}")
    return None


def try_short_zero_ext_getter(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 0f b7 41 NN c3 — MOVZX EAX, word ptr [ECX+NN]; RET (zero-ext to int)
    if len(body) == 5 and body[0:2] == b"\x0f\xb7" and body[2] == 0x41 and body[4] == 0xc3:
        offset = body[3]
        if offset == 0:
            return None
        if offset % 2 != 0:
            return None
        pad = _padding_for_offset(offset, "char")  # char[] for byte offsets
        src = (
            _header(va, f"unsigned short field getter at offset 0x{offset:x} (zero-ext to int)",
                    f"0f b7 41 {offset:02x} c3", n)
            + f"\nclass C {{\n"
            + (f"    {pad}\n" if pad else "")
            + f"    unsigned short field;\npublic:\n    unsigned int get_field();\n}};\n\n"
              f"unsigned int C::get_field() {{ return field; }}\n"
        )
        return (src, f"u16 getter @ 0x{offset:x}")
    return None


def try_byte_zero_ext_getter(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 0f b6 41 NN c3 — MOVZX EAX, byte ptr [ECX+NN]; RET (zero-ext to int)
    if len(body) == 5 and body[0:2] == b"\x0f\xb6" and body[2] == 0x41 and body[4] == 0xc3:
        offset = body[3]
        if offset == 0:
            return None
        pad = _padding_for_offset(offset, "char")
        src = (
            _header(va, f"unsigned char field getter at offset 0x{offset:x} (zero-ext to int)",
                    f"0f b6 41 {offset:02x} c3", n)
            + f"\nclass C {{\n"
            + (f"    {pad}\n" if pad else "")
            + f"    unsigned char field;\npublic:\n    unsigned int get_field();\n}};\n\n"
              f"unsigned int C::get_field() {{ return field; }}\n"
        )
        return (src, f"u8 getter @ 0x{offset:x}")
    return None


def try_jmp_thunk(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # e9 RR RR RR RR — JMP rel32 (5-byte tail-call thunk)
    if len(body) == 5 and body[0] == 0xe9:
        src = (
            _header(va, "JMP-thunk forwarder (tail-call to another function)",
                    "e9 RR RR RR RR", n)
            + "\nextern int target();\nint forwarder() { return target(); }\n"
        )
        return (src, "JMP thunk")
    return None


def try_singleton_tail_call(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # b9 RR RR RR RR e9 RR RR RR RR — MOV ECX, addr; JMP rel32
    if len(body) == 10 and body[0] == 0xb9 and body[5] == 0xe9:
        src = (
            _header(va, "singleton-instance tail-call forwarder",
                    "b9 RR RR RR RR e9 RR RR RR RR", n)
            + "\nclass CClass { public: int method(); };\n"
              "extern CClass g_instance;\n"
              "int forwarder() { return g_instance.method(); }\n"
        )
        return (src, "singleton tail-call")
    return None


def try_thiscall_return_self_wrapper(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 56 8b f1 e8 RR RR RR RR 8b c6 5e c2 04 00 — push esi; mov esi,ecx;
    # call inner; mov eax,esi; pop esi; ret 4 — this-call wrapper
    if (len(body) == 14 and body[0:3] == b"\x56\x8b\xf1" and body[3] == 0xe8
            and body[8:14] == b"\x8b\xc6\x5e\xc2\x04\x00"):
        src = (
            _header(va, "this-call wrapper (calls inner, returns this)",
                    "56 8b f1 e8 RR RR RR RR 8b c6 5e c2 04 00", n)
            + "\nclass C { public: C *do_thing(int); void inner(); };\n"
              "C *C::do_thing(int) { inner(); return this; }\n"
        )
        return (src, "this-call wrapper")
    return None


def try_adjustor_thunk_sub_imm8(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 83 e9 NN e9 RR RR RR RR — SUB ECX, imm8; JMP rel32
    # Multi-inheritance `this`-adjustor thunk: subtracts NN from `this`
    # to get back to the derived class, then tail-jumps to the actual
    # virtual override. MSVC auto-emits these for overrides reached
    # via a secondary base.
    if len(body) == 8 and body[0:2] == b"\x83\xe9" and body[3] == 0xe9:
        offset = body[2]
        if offset == 0:
            return None
        src = (
            _header(va, f"multi-inheritance `this`-adjustor (SUB ECX, 0x{offset:x}; JMP)",
                    f"83 e9 {offset:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void adjustor_thunk() {\n"
            + "    __asm {\n"
            + f"        sub ecx, {offset}\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"adjustor SUB imm8 {offset}")
    return None


def try_unwind_mov_ebp_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 4d NN e9 RR RR RR RR — MOV ECX, [EBP+disp8]; JMP rel32
    # MSVC-emitted SEH unwind helper that loads a frame-saved `this`
    # from the parent function's stack frame and tail-jumps to a
    # destructor or other cleanup. Common across ffxivgame/ffxivboot.
    if len(body) == 8 and body[0:2] == b"\x8b\x4d" and body[3] == 0xe9:
        disp_unsigned = body[2]
        disp_signed = disp_unsigned - 256 if disp_unsigned >= 0x80 else disp_unsigned
        sign = "-" if disp_signed < 0 else "+"
        magnitude = abs(disp_signed)
        src = (
            _header(va, f"SEH unwind helper (MOV ECX, [EBP{sign}0x{magnitude:x}]; JMP)",
                    f"8b 4d {disp_unsigned:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        mov ecx, [ebp {sign} {magnitude}]\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind MOV ECX,[EBP{sign}{magnitude}]")
    return None


def try_unwind_lea_ebp_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8d 4d NN e9 RR RR RR RR — LEA ECX, [EBP+disp8]; JMP rel32
    # SEH unwind helper that takes the ADDRESS of a stack-frame
    # local (rather than loading a pointer from one). Used when
    # the parent's local IS the object being destructed (vs a
    # pointer to it).
    if len(body) == 8 and body[0:2] == b"\x8d\x4d" and body[3] == 0xe9:
        disp_unsigned = body[2]
        disp_signed = disp_unsigned - 256 if disp_unsigned >= 0x80 else disp_unsigned
        sign = "-" if disp_signed < 0 else "+"
        magnitude = abs(disp_signed)
        src = (
            _header(va, f"SEH unwind helper (LEA ECX, [EBP{sign}0x{magnitude:x}]; JMP)",
                    f"8d 4d {disp_unsigned:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        lea ecx, [ebp {sign} {magnitude}]\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind LEA ECX,[EBP{sign}{magnitude}]")
    return None


def try_unwind_lea_ebp_disp32_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8d 8d NN NN NN NN e9 RR RR RR RR (11 bytes)
    # LEA ECX, [EBP+disp32]; JMP rel32 — disp32 form, used when the
    # frame offset is outside int8 range.
    if len(body) == 11 and body[0:2] == b"\x8d\x8d" and body[6] == 0xe9:
        disp_u = int.from_bytes(body[2:6], "little", signed=False)
        disp_s = int.from_bytes(body[2:6], "little", signed=True)
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"SEH unwind helper (LEA ECX, [EBP{sign}0x{mag:x}]; JMP) — disp32",
                    f"8d 8d {disp_u:08x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        lea ecx, [ebp {sign} {mag}]\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind LEA ECX,[EBP{sign}{mag}] disp32")
    return None


def try_unwind_mov_ebp_disp32_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 8d NN NN NN NN e9 RR RR RR RR (11 bytes)
    # MOV ECX, [EBP+disp32]; JMP rel32 — disp32 form.
    if len(body) == 11 and body[0:2] == b"\x8b\x8d" and body[6] == 0xe9:
        disp_u = int.from_bytes(body[2:6], "little", signed=False)
        disp_s = int.from_bytes(body[2:6], "little", signed=True)
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"SEH unwind helper (MOV ECX, [EBP{sign}0x{mag:x}]; JMP) — disp32",
                    f"8b 8d {disp_u:08x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        mov ecx, [ebp {sign} {mag}]\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind MOV ECX,[EBP{sign}{mag}] disp32")
    return None


def try_clear_flag_in_global(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # a1 GG GG GG GG 83 e0 MM a3 GG GG GG GG c3   (14 bytes)
    # MOV EAX, [global]; AND EAX, imm8 (sign-extended); MOV [global], EAX; RET
    # Same global address loaded and stored — clears bits in a global flag.
    if (len(body) == 14 and body[0] == 0xa1 and body[5:7] == b"\x83\xe0"
            and body[8] == 0xa3 and body[13] == 0xc3):
        global_load = int.from_bytes(body[1:5], "little")
        global_store = int.from_bytes(body[9:13], "little")
        if global_load != global_store:
            return None
        mask = body[7]
        # The 0x83 e0 encoding takes a *signed* int8 immediate that
        # sign-extends to 32 bits. We must express the C++ source value
        # the same way, otherwise MSVC's inline assembler picks the
        # 32-bit imm encoding (`25 imm32`) which is 16 bytes total —
        # we want 14. Use the signed decimal form so the assembler
        # recognises it as a signed byte.
        mask_signed = mask - 256 if mask >= 0x80 else mask
        src = (
            _header(va, f"global flag clear (AND imm8 0x{mask:x} = {mask_signed})",
                    f"a1 GG GG GG GG 83 e0 {mask:02x} a3 GG GG GG GG c3", n)
            + "\nextern \"C\" int the_global;\n\n"
            + "extern \"C\" __declspec(naked) void clear_flag() {\n"
            + "    __asm {\n"
            + "        mov eax, dword ptr [the_global]\n"
            + f"        and eax, {mask_signed}\n"
            + "        mov dword ptr [the_global], eax\n"
            + "        ret\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"global AND-clear 0x{mask:x}")
    return None


def try_push_load_call(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 45 NN 50 e8 RR RR RR RR (9 bytes)
    # MOV EAX, [EBP+disp8]; PUSH EAX; CALL rel32
    # Common SEH unwind helper — push a stack-saved object pointer and
    # call its destructor / cleanup function. Falls through (no RET) so
    # caller's RET drives control flow.
    if len(body) == 9 and body[0:2] == b"\x8b\x45" and body[3] == 0x50 and body[4] == 0xe8:
        disp_u = body[2]
        disp_s = disp_u - 256 if disp_u >= 0x80 else disp_u
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"unwind helper (MOV EAX, [EBP{sign}0x{mag:x}]; PUSH EAX; CALL)",
                    f"8b 45 {disp_u:02x} 50 e8 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void push_call_helper() {\n"
            + "    __asm {\n"
            + f"        mov eax, [ebp {sign} {mag}]\n"
            + "        push eax\n"
            + "        call target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"push-call EBP{sign}{mag}")
    return None


def try_array_deleting_dtor_34b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 34B variant of scalar-deleting-dtor with NULL check + alloc-block
    # offset (used for arrays). Shape:
    #
    #   56 8b f1                                    PUSH ESI; MOV ESI, ECX
    #   e8 RR RR RR RR                              CALL ~C()
    #   f6 44 24 08 01                              TEST flag
    #   74 0d                                       JZ +13
    #   85 f6                                       TEST ESI, ESI       (null check)
    #   74 09                                       JZ +9               (skip on null)
    #   8b 4e fc                                    MOV ECX, [ESI-4]    (alloc-block ptr)
    #   56                                          PUSH ESI
    #   e8 RR RR RR RR                              CALL operator delete[]
    #   8b c6 5e c2 04 00                           MOV EAX,ESI; POP ESI; RET 4
    if len(body) != 34:
        return None
    expected = [
        (0x56,), (0x8b,), (0xf1,),
        (0xe8,), None, None, None, None,
        (0xf6,), (0x44,), (0x24,), (0x08,), (0x01,),
        (0x74,), (0x0d,),
        (0x85,), (0xf6,),
        (0x74,), (0x09,),
        (0x8b,), (0x4e,), (0xfc,),
        (0x56,),
        (0xe8,), None, None, None, None,
        (0x8b,), (0xc6,), (0x5e,), (0xc2,), (0x04,), (0x00,),
    ]
    for i, exp in enumerate(expected):
        if exp is None:
            continue
        if body[i] != exp[0]:
            return None
    src = (
        _header(va, "MSVC array deleting destructor (34B form, null+alloc-block)",
                "56 8b f1 e8 RR RR RR RR f6 44 24 08 01 74 0d 85 f6 74 09 "
                "8b 4e fc 56 e8 RR RR RR RR 8b c6 5e c2 04 00", n)
        + "\nextern \"C\" int real_dtor();\n"
          "extern \"C\" int operator_delete_array();\n\n"
          "extern \"C\" __declspec(naked) void array_deleting_dtor() {\n"
          "    __asm {\n"
          "        push esi\n"
          "        mov esi, ecx\n"
          "        call real_dtor\n"
          "        test byte ptr [esp+8], 1\n"
          "        jz no_delete\n"
          "        test esi, esi\n"
          "        jz no_delete2\n"
          "        mov ecx, [esi - 4]\n"
          "        push esi\n"
          "        call operator_delete_array\n"
          "    no_delete2:\n"
          "    no_delete:\n"
          "        mov eax, esi\n"
          "        pop esi\n"
          "        ret 4\n"
          "    }\n"
          "}\n"
    )
    return (src, "array-deleting-dtor 34B")


def try_unwind_flag_check_jmp_25b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 25B SEH unwind helper that gates the destructor on a flag bit:
    #
    #   8b 45 f0                MOV EAX, [EBP-0x10]
    #   83 e0 01                AND EAX, 1
    #   0f 84 0c 00 00 00       JZ FAR +0xc                (long-form JZ)
    #   83 65 f0 fe             AND [EBP-0x10], 0xfffffffe (clear low bit)
    #   8b 4d 04                MOV ECX, [EBP+4]
    #   e9 RR RR RR RR          JMP rel32                  (tail to dtor)
    #   c3                      RET                        (only when bit was 0)
    if len(body) != 25:
        return None
    expected = [
        (0x8b,), (0x45,), (0xf0,),
        (0x83,), (0xe0,), (0x01,),
        (0x0f,), (0x84,), (0x0c,), (0x00,), (0x00,), (0x00,),
        (0x83,), (0x65,), (0xf0,), (0xfe,),
        (0x8b,), (0x4d,), (0x04,),
        (0xe9,), None, None, None, None,
        (0xc3,),
    ]
    for i, exp in enumerate(expected):
        if exp is None:
            continue
        if body[i] != exp[0]:
            return None
    src = (
        _header(va, "SEH unwind helper (flag-test → tail-call dtor; 25B)",
                "8b 45 f0 83 e0 01 0f 84 0c 00 00 00 83 65 f0 fe "
                "8b 4d 04 e9 RR RR RR RR c3", n)
        + "\nextern \"C\" int target();\n\n"
          "extern \"C\" __declspec(naked) void unwind_flag_check() {\n"
          "    __asm {\n"
          "        mov eax, [ebp - 16]\n"
          "        and eax, 1\n"
          "        ; force long-form JZ (cl.exe defaults to short).\n"
          "        _emit 0x0f\n"
          "        _emit 0x84\n"
          "        _emit 0x0c\n"
          "        _emit 0x00\n"
          "        _emit 0x00\n"
          "        _emit 0x00\n"
          "        and dword ptr [ebp - 16], -2\n"
          "        mov ecx, [ebp + 4]\n"
          "        jmp target\n"
          "        ret\n"
          "    }\n"
          "}\n"
    )
    return (src, "unwind flag-check 25B")


def try_scalar_deleting_dtor_30b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # MSVC-emitted "scalar deleting destructor" — appears in every class
    # vtable that has a virtual destructor. Shape (30 bytes):
    #
    #   56                    PUSH ESI                  (save ESI)
    #   8b f1                 MOV ESI, ECX              (this → ESI)
    #   e8 RR RR RR RR        CALL <real ~C()>          (reloc)
    #   f6 44 24 08 01        TEST byte ptr [ESP+8], 1  (delete-flag arg)
    #   74 09                 JZ +9                     (skip delete)
    #   56                    PUSH ESI                  (push this)
    #   e8 RR RR RR RR        CALL operator delete      (reloc)
    #   83 c4 04              ADD ESP, 4                (clean up arg)
    #   8b c6                 MOV EAX, ESI              (return this)
    #   5e                    POP ESI
    #   c2 04 00              RET 4                     (pop the flag arg)
    expected = (
        b"\x56\x8b\xf1\xe8" + b"\x00" * 4 +     # 0:PUSH ESI; MOV ESI,ECX; CALL ~C
        b"\xf6\x44\x24\x08\x01\x74\x09\x56" +   # 8:TEST flag; JZ +9; PUSH ESI
        b"\xe8" + b"\x00" * 4 +                 # 16:CALL operator delete
        b"\x83\xc4\x04\x8b\xc6\x5e\xc2\x04\x00" # 21:ADD ESP,4; MOV EAX,ESI; POP ESI; RET 4
    )
    if len(body) != 30:
        return None
    # Match every byte except the two reloc rel32 fields.
    fixed_mask = bytes(0xff for _ in expected)
    fixed_mask = bytearray(fixed_mask)
    fixed_mask[4:8] = b"\x00" * 4   # CALL ~C reloc
    fixed_mask[17:21] = b"\x00" * 4 # CALL delete reloc
    for i, m in enumerate(fixed_mask):
        if m == 0:
            continue
        if body[i] != expected[i]:
            return None
    src = (
        _header(va, "MSVC scalar deleting destructor (30B form)",
                "56 8b f1 e8 RR RR RR RR f6 44 24 08 01 74 09 56 "
                "e8 RR RR RR RR 83 c4 04 8b c6 5e c2 04 00", n)
        + "\nextern \"C\" int real_dtor();\n"
          "extern \"C\" int operator_delete();\n\n"
          "extern \"C\" __declspec(naked) void scalar_deleting_dtor() {\n"
          "    __asm {\n"
          "        push esi\n"
          "        mov esi, ecx\n"
          "        call real_dtor\n"
          "        test byte ptr [esp+8], 1\n"
          "        jz no_delete\n"
          "        push esi\n"
          "        call operator_delete\n"
          "        add esp, 4\n"
          "    no_delete:\n"
          "        mov eax, esi\n"
          "        pop esi\n"
          "        ret 4\n"
          "    }\n"
          "}\n"
    )
    return (src, "scalar-deleting-dtor 30B")


def try_scalar_deleting_dtor_32b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 32-byte variant with custom allocator: same shape as 30B but
    # MOV ECX, <global allocator> before the delete call. Shape:
    #
    #   56 8b f1                                  PUSH ESI; MOV ESI, ECX
    #   e8 RR RR RR RR                            CALL real ~C()
    #   f6 44 24 08 01                            TEST flag
    #   74 0b                                     JZ +11
    #   56                                        PUSH ESI
    #   b9 GG GG GG GG                            MOV ECX, &allocator
    #   e8 RR RR RR RR                            CALL operator delete with alloc
    #   8b c6 5e c2 04 00                         MOV EAX,ESI; POP ESI; RET 4
    if len(body) != 32:
        return None
    expected_template = [
        (0x56,), (0x8b,), (0xf1,),
        (0xe8,), None, None, None, None,         # CALL ~C() opcode + 4-byte reloc
        (0xf6,), (0x44,), (0x24,), (0x08,), (0x01,),
        (0x74,), (0x0b,),
        (0x56,),
        (0xb9,), None, None, None, None,         # MOV ECX, alloc opcode + 4-byte reloc
        (0xe8,), None, None, None, None,         # CALL delete opcode + 4-byte reloc
        (0x8b,), (0xc6,), (0x5e,), (0xc2,), (0x04,), (0x00,),
    ]
    expected = b"\xe8" + b"\x00" * 4   # placeholder, not used directly
    for i, exp in enumerate(expected_template):
        if exp is None:
            continue
        if body[i] != exp[0]:
            return None
    src = (
        _header(va, "MSVC scalar deleting destructor (32B form, custom allocator)",
                "56 8b f1 e8 RR RR RR RR f6 44 24 08 01 74 0b 56 "
                "b9 GG GG GG GG e8 RR RR RR RR 8b c6 5e c2 04 00", n)
        + "\nextern \"C\" int real_dtor();\n"
          "extern \"C\" int operator_delete_alloc();\n"
          "extern \"C\" int the_allocator;\n\n"
          "extern \"C\" __declspec(naked) void scalar_deleting_dtor_alloc() {\n"
          "    __asm {\n"
          "        push esi\n"
          "        mov esi, ecx\n"
          "        call real_dtor\n"
          "        test byte ptr [esp+8], 1\n"
          "        jz no_delete\n"
          "        push esi\n"
          "        mov ecx, offset the_allocator\n"
          "        call operator_delete_alloc\n"
          "    no_delete:\n"
          "        mov eax, esi\n"
          "        pop esi\n"
          "        ret 4\n"
          "    }\n"
          "}\n"
    )
    return (src, "scalar-deleting-dtor 32B alloc")


def try_return_global_addr(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # b8 GG GG GG GG c3 (6 bytes)
    # MOV EAX, imm32; RET. Returns a constant 32-bit value — typically
    # the address of a global, but could also be an arbitrary const.
    # Reloc-equivalent shape: every cluster member shares the same
    # encoding shape but with a different reloc target (the imm32).
    if len(body) == 6 and body[0] == 0xb8 and body[5] == 0xc3:
        # Treat the imm32 as a relocated address — emit `&the_global`.
        src = (
            _header(va, "return global address (MOV EAX, &global; RET)",
                    "b8 GG GG GG GG c3", n)
            + "\nextern \"C\" int the_global;\n\n"
            + "extern \"C\" int *get_global_addr() {\n"
              "    return &the_global;\n"
              "}\n"
        )
        return (src, "return-global-addr")
    return None


def try_unwind_mov_ebp_add32_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 4d NN 81 c1 MM MM MM MM e9 RR RR RR RR (14 bytes)
    # MOV ECX, [EBP+disp8]; ADD ECX, imm32; JMP rel32
    # disp32-ADD variant of `try_unwind_mov_ebp_add_jmp`. Used when
    # the additional subobject offset is outside int8 range.
    if (len(body) == 14 and body[0:2] == b"\x8b\x4d" and body[3:5] == b"\x81\xc1"
            and body[9] == 0xe9):
        ebp_disp_u = body[2]
        ebp_disp_s = ebp_disp_u - 256 if ebp_disp_u >= 0x80 else ebp_disp_u
        ebp_sign = "-" if ebp_disp_s < 0 else "+"
        ebp_mag = abs(ebp_disp_s)
        add_imm = int.from_bytes(body[5:9], "little")
        src = (
            _header(va,
                    f"SEH unwind helper (MOV ECX, [EBP{ebp_sign}0x{ebp_mag:x}]; ADD ECX, 0x{add_imm:x}; JMP)",
                    f"8b 4d {ebp_disp_u:02x} 81 c1 {add_imm:08x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        mov ecx, [ebp {ebp_sign} {ebp_mag}]\n"
            + f"        add ecx, {add_imm}\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind MOV+ADD32 ECX,[EBP{ebp_sign}{ebp_mag}]+{add_imm}")
    return None


def try_unwind_mov_ebp_add_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 4d NN 83 c1 MM e9 RR RR RR RR (11 bytes)
    # MOV ECX, [EBP+disp8]; ADD ECX, imm8; JMP rel32
    # Variant where the saved pointer needs an additional offset
    # (e.g. base-class subobject inside a frame-stored derived).
    if len(body) == 11 and body[0:2] == b"\x8b\x4d" and body[3:5] == b"\x83\xc1" and body[6] == 0xe9:
        ebp_disp_u = body[2]
        ebp_disp_s = ebp_disp_u - 256 if ebp_disp_u >= 0x80 else ebp_disp_u
        ebp_sign = "-" if ebp_disp_s < 0 else "+"
        ebp_mag = abs(ebp_disp_s)
        add_imm = body[5]
        src = (
            _header(va,
                    f"SEH unwind helper (MOV ECX, [EBP{ebp_sign}0x{ebp_mag:x}]; ADD ECX, 0x{add_imm:x}; JMP)",
                    f"8b 4d {ebp_disp_u:02x} 83 c1 {add_imm:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        mov ecx, [ebp {ebp_sign} {ebp_mag}]\n"
            + f"        add ecx, {add_imm}\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind MOV+ADD ECX,[EBP{ebp_sign}{ebp_mag}]+{add_imm}")
    return None


def try_adjustor_thunk_sub_imm32(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 81 e9 NN NN NN NN e9 RR RR RR RR — SUB ECX, imm32; JMP rel32
    # Same as imm8 form but for offsets ≥ 0x80 (8-bit signed range exhausted).
    if len(body) == 11 and body[0:2] == b"\x81\xe9" and body[6] == 0xe9:
        offset = int.from_bytes(body[2:6], "little")
        if offset == 0:
            return None
        src = (
            _header(va, f"multi-inheritance `this`-adjustor (SUB ECX, 0x{offset:x}; JMP)",
                    f"81 e9 {offset:08x} (LE) e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void adjustor_thunk() {\n"
            + "    __asm {\n"
            + f"        sub ecx, {offset}\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"adjustor SUB imm32 {offset}")
    return None


def try_chained_ptr_getter(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 41 NN 8b 40 MM c3 — MOV EAX,[ECX+NN]; MOV EAX,[EAX+MM]; RET
    # Both NN and MM are *signed* int8 displacements as encoded.
    if not (len(body) == 7 and body[0] == 0x8b and body[1] == 0x41 and body[3] == 0x8b
            and body[4] == 0x40 and body[6] == 0xc3):
        return None

    raw_outer = body[2]
    raw_inner = body[5]
    outer_signed = raw_outer - 256 if raw_outer >= 0x80 else raw_outer
    inner_signed = raw_inner - 256 if raw_inner >= 0x80 else raw_inner

    # Negative or non-multiple-of-4 offsets can't be expressed cleanly as
    # C++ field accesses without forcing the compiler to a 32-bit disp32
    # (which inflates 7 bytes → 10). Fall back to naked inline asm: byte-
    # exact regardless of sign, at the cost of less readable source.
    has_negative = outer_signed < 0 or inner_signed < 0
    misaligned = (outer_signed % 4 != 0) or (inner_signed % 4 != 0)
    if has_negative or misaligned:
        return _chained_ptr_naked(body, va, n, outer_signed, inner_signed)

    outer_off = outer_signed
    inner_off = inner_signed
    if outer_off == 0:
        return None
    outer_pad = _padding_for_offset(outer_off, "int")
    if inner_off == 0:
        inner_decl = "class Inner {\npublic:\n    int *field;\n};"
    else:
        n_pad = inner_off // 4
        inner_decl = f"class Inner {{\n    int padding[{n_pad}];\npublic:\n    int *field;\n}};"
    src = (
        _header(va, f"chained ptr getter (this->[+0x{outer_off:x}]->field+0x{inner_off:x})",
                f"8b 41 {raw_outer:02x} 8b 40 {raw_inner:02x} c3", n)
        + f"\n{inner_decl}\n\nclass Outer {{\n"
        + (f"    {outer_pad}\n" if outer_pad else "")
        + f"    Inner *inner;\npublic:\n    int *get_inner_field();\n}};\n\n"
          f"int *Outer::get_inner_field() {{ return inner->field; }}\n"
    )
    return (src, f"chained ptr @ 0x{outer_off:x}/0x{inner_off:x}")


def _chained_ptr_naked(body: bytes, va: int, n: int, outer: int, inner: int) -> tuple[str, str]:
    raw_outer = body[2]
    raw_inner = body[5]
    outer_sign = "-" if outer < 0 else "+"
    inner_sign = "-" if inner < 0 else "+"
    outer_mag = abs(outer)
    inner_mag = abs(inner)
    src = (
        _header(va, f"chained ptr getter (signed-disp; naked asm) "
                    f"this->[ECX{outer_sign}0x{outer_mag:x}]->field+0x{inner_mag:x}",
                f"8b 41 {raw_outer:02x} 8b 40 {raw_inner:02x} c3", n)
        + "\nextern \"C\" __declspec(naked) int *chained_ptr_getter() {\n"
          "    __asm {\n"
        + f"        mov eax, [ecx {outer_sign} {outer_mag}]\n"
        + f"        mov eax, [eax {inner_sign} {inner_mag}]\n"
          "        ret\n"
          "    }\n"
          "}\n"
    )
    return (src, f"chained ptr (naked) @ {outer_sign}0x{outer_mag:x}/{inner_sign}0x{inner_mag:x}")


# Order matters: most specific first.
DERIVERS = [
    try_empty_void,
    try_empty_n_arg,
    try_return_zero_int,
    try_return_false_bool,
    try_return_true_bool,
    try_return_this,
    try_int_getter,
    try_short_zero_ext_getter,
    try_byte_zero_ext_getter,
    try_chained_ptr_getter,
    try_adjustor_thunk_sub_imm8,
    try_adjustor_thunk_sub_imm32,
    try_unwind_mov_ebp_jmp,
    try_unwind_lea_ebp_jmp,
    try_unwind_lea_ebp_disp32_jmp,
    try_unwind_mov_ebp_disp32_jmp,
    try_unwind_mov_ebp_add_jmp,
    try_unwind_mov_ebp_add32_jmp,
    try_clear_flag_in_global,
    try_push_load_call,
    try_return_global_addr,
    try_scalar_deleting_dtor_30b,
    try_scalar_deleting_dtor_32b,
    try_array_deleting_dtor_34b,
    try_unwind_flag_check_jmp_25b,
    try_thiscall_return_self_wrapper,
    try_singleton_tail_call,
    try_jmp_thunk,
]


def derive_one(body: bytes, va: int, n_members: int) -> tuple[str, str] | None:
    for fn in DERIVERS:
        result = fn(body, va, n_members)
        if result is not None:
            return result
    return None


def process_binary(stem: str, dry_run: bool, image_base: int = 0x400000) -> dict:
    rosetta_dir = SRC_DIR / stem / "_rosetta"
    rosetta_dir.mkdir(parents=True, exist_ok=True)
    asm_dir = ASM_ROOT / stem

    # Read both clusters JSONs (exact-byte + reloc-aware), unioning members.
    clusters_paths = [
        EASY_WINS / f"{stem}.clusters.json",
        EASY_WINS / f"{stem}.clusters_reloc.json",
    ]
    seen_rva: set[int] = set()
    n_recognised = 0
    n_skipped_unrecognised = 0
    n_skipped_existing = 0
    by_idiom: dict[str, int] = {}

    for p in clusters_paths:
        if not p.exists():
            continue
        clusters = json.loads(p.read_text())
        for h, members in clusters.items():
            # Pick the smallest-RVA member as primary, deterministic per cluster.
            rep = min(members, key=lambda m: m["rva"])
            if rep["rva"] in seen_rva:
                continue
            seen_rva.add(rep["rva"])
            asm_path = asm_dir / rep["asm"]
            body = read_function_bytes(asm_path)
            if body is None:
                continue
            va = rep["rva"] + image_base
            target_path = rosetta_dir / f"FUN_{va:08x}.cpp"
            if target_path.exists():
                n_skipped_existing += 1
                continue
            result = derive_one(body, va, len(members))
            if result is None:
                n_skipped_unrecognised += 1
                continue
            src, idiom = result
            if not dry_run:
                target_path.write_text(src)
            n_recognised += 1
            by_idiom[idiom] = by_idiom.get(idiom, 0) + 1
    return {
        "binary": stem,
        "recognised": n_recognised,
        "skipped_existing": n_skipped_existing,
        "skipped_unrecognised": n_skipped_unrecognised,
        "by_idiom": by_idiom,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("binary", default="ffxivgame", nargs="?")
    ap.add_argument("--all", action="store_true", help="run on all 5 binaries")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if args.all:
        targets = list(KNOWN_BINARIES)
    else:
        targets = [args.binary.replace(".exe", "")]

    grand_recognised = 0
    grand_idioms: dict[str, int] = {}
    for t in targets:
        report = process_binary(t, dry_run=args.dry_run)
        print(f"=== {t} ===")
        print(f"  recognised:           {report['recognised']:>5}{' (dry-run)' if args.dry_run else ''}")
        print(f"  skipped (existing):   {report['skipped_existing']:>5}")
        print(f"  skipped (unmatched):  {report['skipped_unrecognised']:>5}")
        if report["by_idiom"]:
            print(f"  by idiom:")
            for idiom, n in sorted(report["by_idiom"].items(), key=lambda kv: -kv[1]):
                print(f"    {idiom:<35}  {n}")
                grand_idioms[idiom] = grand_idioms.get(idiom, 0) + n
        grand_recognised += report["recognised"]

    if len(targets) > 1:
        print(f"\nGrand total recognised: {grand_recognised}{' (dry-run)' if args.dry_run else ''}")
        print(f"Top idioms across all binaries:")
        for idiom, n in sorted(grand_idioms.items(), key=lambda kv: -kv[1])[:15]:
            print(f"  {idiom:<35}  {n}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
