#!/usr/bin/env python3
# meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
# Copyright (C) 2026  Samuel Stegall
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Auto-derive matching .cpp templates from cluster byte patterns.

For each multi-member cluster in `<bin>.clusters.json` and
`<bin>.clusters_reloc.json`, examine the cluster representative's
bytes and try to recognise a known idiom (empty method, constant
return, accessor, setter, this-call wrapper, etc.). When a pattern
matches, emit a canonical C++ template at
`src/<bin>/_rosetta/FUN_<rva>.cpp` for the representative; the
companion `tools/stamp_clusters.py` then expands the template to
every byte-identical (or reloc-equivalent) cluster sibling.

Recognised idioms (in evaluation order — most specific first):

  RET                              `c3`
  RET imm16                        `c2 NN 00`        (empty N/4-arg method)
  return 0 (int)                   `33 c0 c3`        / with arg cleanup `33 c0 c2 NN 00`
  return false (bool, 8-bit)       `32 c0 c3`        / `32 c0 c2 NN 00`
  return true (bool, 8-bit)        `b0 01 c3`        / `b0 01 c2 NN 00`
  return *this                     `8b c1 c3`
  return imm8 (signed)             `b0 NN c3`        (NN ≠ 0,1)
  int-getter at offset NN          `8b 41 NN c3`     (NN ≤ 0x7f)
  int-getter at long offset        `8b 81 NN NN NN NN c3`
  byte zero-ext getter             `0f b6 41 NN c3`  (returns int from byte)
  byte sign-ext getter             `0f be 41 NN c3`
  short zero-ext getter            `0f b7 41 NN c3`
  short sign-ext getter            `0f bf 41 NN c3`
  bit-flag getter                  `8a 41 NN 24 01 c2 08 00`  (returns u8 & 1)
  chained ptr getter               `8b 41 NN 8b 40 MM c3`
  int setter at offset NN          `8b 44 24 04 89 41 NN c2 04 00`
  this-call wrapper (return self)  `56 8b f1 e8 RR RR RR RR 8b c6 5e c2 04 00`
  singleton tail-call              `b9 RR RR RR RR e9 RR RR RR RR`
  JMP-thunk forwarder              `e9 RR RR RR RR`
  scalar deleting destructor       `56 8b f1 e8 RR RR RR RR f6 44 24 08 01 74 09 56 e8 RR RR RR RR 83 c4 04 8b c6 5e c2 04 00`

`RR` denotes a relocation byte (cluster member-specific, wildcarded
by the reloc-aware diff in `compare.py`). `NN` and `MM` are immediate
values that the deriver reads from the cluster's bytes and bakes into
the generated template.

Reads:
  build/easy_wins/<binary>.clusters.json
  build/easy_wins/<binary>.clusters_reloc.json (optional)

Writes:
  src/<binary>/_rosetta/FUN_<rva>.cpp  (one per recognised cluster)

Skip rule: never overwrite an existing .cpp.

Usage:
  tools/derive_templates.py [binary]                 # default ffxivgame
  tools/derive_templates.py --all
  tools/derive_templates.py ffxivgame --dry-run
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_DIR = REPO_ROOT / "src"
EASY_WINS = REPO_ROOT / "build" / "easy_wins"
ASM_ROOT = REPO_ROOT / "asm"

KNOWN_BINARIES = ("ffxivgame", "ffxivlogin", "ffxivboot", "ffxivconfig", "ffxivupdater")

LICENSE = """\
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//"""

RE_INSTR = re.compile(
    r"^\s*[0-9a-fA-F]+:\s+((?:[0-9a-fA-F][0-9a-fA-F]\s+)+)\s",
    re.MULTILINE,
)


def read_function_bytes(asm_path: Path) -> bytes | None:
    if not asm_path.exists():
        return None
    text = asm_path.read_text(errors="replace")
    body = bytearray()
    for m in RE_INSTR.finditer(text):
        for tok in m.group(1).split():
            body.append(int(tok, 16))
    return bytes(body)


# -----------------------------------------------------------------------------
# Pattern matchers — each returns (template_text, idiom_name) on match,
# or None on no-match. Each takes the cluster's representative bytes
# and produces a complete .cpp source.
# -----------------------------------------------------------------------------


def _header(va: int, idiom: str, asm_summary: str, n_members: int) -> str:
    return (
        f"{LICENSE}\n"
        f"// SPDX-License-Identifier: AGPL-3.0-or-later\n"
        f"//\n"
        f"// FUNCTION: ffxivgame {hex(va)} — {idiom}\n"
        f"// Auto-generated by tools/derive_templates.py.\n"
        f"// Cluster representative — covers {n_members} byte-identical (or\n"
        f"// reloc-equivalent) members.\n"
        f"//\n"
        f"// Asm: {asm_summary}\n"
    )


def try_empty_void(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\xc3":
        src = (
            _header(va, "empty zero-arg method (RET)", "c3", n)
            + "\nclass C { public: void empty(); };\n"
              "void C::empty() {}\n"
        )
        return (src, "empty 0-arg")
    return None


def try_empty_n_arg(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if len(body) == 3 and body[0] == 0xc2 and body[2] == 0x00:
        nbytes = body[1]
        if nbytes == 0 or nbytes % 4 != 0:
            return None
        nargs = nbytes // 4
        args = ", ".join(["int"] * nargs)
        src = (
            _header(va, f"empty `__thiscall` {nargs}-arg method (RET 0x{nbytes:x})",
                    f"c2 {nbytes:02x} 00", n)
            + f"\nclass C {{ public: void empty{nargs}({args}); }};\n"
              f"void C::empty{nargs}({args}) {{}}\n"
        )
        return (src, f"empty {nargs}-arg")
    return None


def try_return_zero_int(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\x33\xc0\xc3":
        src = (
            _header(va, "return 0 (int)", "33 c0 c3", n)
            + "\nclass C { public: int zero() const; };\n"
              "int C::zero() const { return 0; }\n"
        )
        return (src, "return 0")
    if len(body) == 5 and body[:2] == b"\x33\xc0" and body[2] == 0xc2 and body[4] == 0x00:
        nbytes = body[3]
        if nbytes == 0 or nbytes % 4 != 0:
            return None
        nargs = nbytes // 4
        args = ", ".join(["int"] * nargs)
        src = (
            _header(va, f"return 0 (int) — {nargs}-arg",
                    f"33 c0 c2 {nbytes:02x} 00", n)
            + f"\nclass C {{ public: int zero({args}); }};\n"
              f"int C::zero({args}) {{ return 0; }}\n"
        )
        return (src, f"return 0 ({nargs}-arg)")
    return None


def try_return_false_bool(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\x32\xc0\xc3":
        src = (
            _header(va, "return false (bool, 8-bit)", "32 c0 c3", n)
            + "\nclass C { public: unsigned char no() const; };\n"
              "unsigned char C::no() const { unsigned char r = 0; return r; }\n"
        )
        return (src, "return false")
    if len(body) == 5 and body[:2] == b"\x32\xc0" and body[2] == 0xc2 and body[4] == 0x00:
        nbytes = body[3]
        if nbytes == 0 or nbytes % 4 != 0:
            return None
        nargs = nbytes // 4
        args = ", ".join(["int"] * nargs)
        src = (
            _header(va, f"return false (bool, 8-bit) — {nargs}-arg",
                    f"32 c0 c2 {nbytes:02x} 00", n)
            + f"\nclass C {{ public: unsigned char no({args}); }};\n"
              f"unsigned char C::no({args}) {{ unsigned char r = 0; return r; }}\n"
        )
        return (src, f"return false ({nargs}-arg)")
    return None


def try_return_true_bool(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\xb0\x01\xc3":
        src = (
            _header(va, "return true (bool, 8-bit)", "b0 01 c3", n)
            + "\nclass C { public: unsigned char yes() const; };\n"
              "unsigned char C::yes() const { unsigned char r = 1; return r; }\n"
        )
        return (src, "return true")
    if len(body) == 5 and body[:2] == b"\xb0\x01" and body[2] == 0xc2 and body[4] == 0x00:
        nbytes = body[3]
        if nbytes == 0 or nbytes % 4 != 0:
            return None
        nargs = nbytes // 4
        args = ", ".join(["int"] * nargs)
        src = (
            _header(va, f"return true (bool, 8-bit) — {nargs}-arg",
                    f"b0 01 c2 {nbytes:02x} 00", n)
            + f"\nclass C {{ public: unsigned char yes({args}); }};\n"
              f"unsigned char C::yes({args}) {{ unsigned char r = 1; return r; }}\n"
        )
        return (src, f"return true ({nargs}-arg)")
    return None


def try_return_this(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    if body == b"\x8b\xc1\xc3":
        src = (
            _header(va, "return *this (MOV EAX,ECX; RET)", "8b c1 c3", n)
            + "\nclass C { public: C *identity(); };\n"
              "C *C::identity() { return this; }\n"
        )
        return (src, "return *this")
    return None


def _padding_for_offset(offset: int, base_t: str = "int") -> str:
    """Generate `T padding[N];` for byte-offset `offset` of base T (4 B for int)."""
    if offset == 0:
        return ""
    base_size = 4 if base_t == "int" else (1 if base_t == "char" else 4)
    if offset % base_size != 0:
        # Use char[] for non-aligned offsets
        return f"char padding[{offset}];"
    n = offset // base_size
    return f"{base_t} padding[{n}];"


def try_int_getter(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 4-byte form: 8b 41 NN c3 — MOV EAX, [ECX+NN]; RET
    if len(body) == 4 and body[0] == 0x8b and body[1] == 0x41 and body[3] == 0xc3:
        offset = body[2]
        if offset == 0:
            # 8b 41 00 wouldn't happen — that'd be 8b 01. Skip.
            return None
        pad = _padding_for_offset(offset, "int")
        if pad and offset % 4 != 0:
            # Non-aligned — skip; rare and source generation would be tricky.
            return None
        src = (
            _header(va, f"int field getter at offset 0x{offset:x}",
                    f"8b 41 {offset:02x} c3", n)
            + f"\nclass C {{\n"
            + (f"    {pad}\n" if pad else "")
            + f"    int field;\npublic:\n    int get_field();\n}};\n\n"
              f"int C::get_field() {{ return field; }}\n"
        )
        return (src, f"int getter @ 0x{offset:x}")
    return None


def try_short_zero_ext_getter(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 0f b7 41 NN c3 — MOVZX EAX, word ptr [ECX+NN]; RET (zero-ext to int)
    if len(body) == 5 and body[0:2] == b"\x0f\xb7" and body[2] == 0x41 and body[4] == 0xc3:
        offset = body[3]
        if offset == 0:
            return None
        if offset % 2 != 0:
            return None
        pad = _padding_for_offset(offset, "char")  # char[] for byte offsets
        src = (
            _header(va, f"unsigned short field getter at offset 0x{offset:x} (zero-ext to int)",
                    f"0f b7 41 {offset:02x} c3", n)
            + f"\nclass C {{\n"
            + (f"    {pad}\n" if pad else "")
            + f"    unsigned short field;\npublic:\n    unsigned int get_field();\n}};\n\n"
              f"unsigned int C::get_field() {{ return field; }}\n"
        )
        return (src, f"u16 getter @ 0x{offset:x}")
    return None


def try_byte_zero_ext_getter(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 0f b6 41 NN c3 — MOVZX EAX, byte ptr [ECX+NN]; RET (zero-ext to int)
    if len(body) == 5 and body[0:2] == b"\x0f\xb6" and body[2] == 0x41 and body[4] == 0xc3:
        offset = body[3]
        if offset == 0:
            return None
        pad = _padding_for_offset(offset, "char")
        src = (
            _header(va, f"unsigned char field getter at offset 0x{offset:x} (zero-ext to int)",
                    f"0f b6 41 {offset:02x} c3", n)
            + f"\nclass C {{\n"
            + (f"    {pad}\n" if pad else "")
            + f"    unsigned char field;\npublic:\n    unsigned int get_field();\n}};\n\n"
              f"unsigned int C::get_field() {{ return field; }}\n"
        )
        return (src, f"u8 getter @ 0x{offset:x}")
    return None


def try_jmp_thunk(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # e9 RR RR RR RR — JMP rel32 (5-byte tail-call thunk)
    if len(body) == 5 and body[0] == 0xe9:
        src = (
            _header(va, "JMP-thunk forwarder (tail-call to another function)",
                    "e9 RR RR RR RR", n)
            + "\nextern int target();\nint forwarder() { return target(); }\n"
        )
        return (src, "JMP thunk")
    return None


def try_singleton_tail_call(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # b9 RR RR RR RR e9 RR RR RR RR — MOV ECX, addr; JMP rel32
    if len(body) == 10 and body[0] == 0xb9 and body[5] == 0xe9:
        src = (
            _header(va, "singleton-instance tail-call forwarder",
                    "b9 RR RR RR RR e9 RR RR RR RR", n)
            + "\nclass CClass { public: int method(); };\n"
              "extern CClass g_instance;\n"
              "int forwarder() { return g_instance.method(); }\n"
        )
        return (src, "singleton tail-call")
    return None


def try_thiscall_return_self_wrapper(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 56 8b f1 e8 RR RR RR RR 8b c6 5e c2 04 00 — push esi; mov esi,ecx;
    # call inner; mov eax,esi; pop esi; ret 4 — this-call wrapper
    if (len(body) == 14 and body[0:3] == b"\x56\x8b\xf1" and body[3] == 0xe8
            and body[8:14] == b"\x8b\xc6\x5e\xc2\x04\x00"):
        src = (
            _header(va, "this-call wrapper (calls inner, returns this)",
                    "56 8b f1 e8 RR RR RR RR 8b c6 5e c2 04 00", n)
            + "\nclass C { public: C *do_thing(int); void inner(); };\n"
              "C *C::do_thing(int) { inner(); return this; }\n"
        )
        return (src, "this-call wrapper")
    return None


def try_adjustor_thunk_sub_imm8(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 83 e9 NN e9 RR RR RR RR — SUB ECX, imm8; JMP rel32
    # Multi-inheritance `this`-adjustor thunk: subtracts NN from `this`
    # to get back to the derived class, then tail-jumps to the actual
    # virtual override. MSVC auto-emits these for overrides reached
    # via a secondary base.
    if len(body) == 8 and body[0:2] == b"\x83\xe9" and body[3] == 0xe9:
        offset = body[2]
        if offset == 0:
            return None
        src = (
            _header(va, f"multi-inheritance `this`-adjustor (SUB ECX, 0x{offset:x}; JMP)",
                    f"83 e9 {offset:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void adjustor_thunk() {\n"
            + "    __asm {\n"
            + f"        sub ecx, {offset}\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"adjustor SUB imm8 {offset}")
    return None


def try_unwind_mov_ebp_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 4d NN e9 RR RR RR RR — MOV ECX, [EBP+disp8]; JMP rel32
    # MSVC-emitted SEH unwind helper that loads a frame-saved `this`
    # from the parent function's stack frame and tail-jumps to a
    # destructor or other cleanup. Common across ffxivgame/ffxivboot.
    if len(body) == 8 and body[0:2] == b"\x8b\x4d" and body[3] == 0xe9:
        disp_unsigned = body[2]
        disp_signed = disp_unsigned - 256 if disp_unsigned >= 0x80 else disp_unsigned
        sign = "-" if disp_signed < 0 else "+"
        magnitude = abs(disp_signed)
        src = (
            _header(va, f"SEH unwind helper (MOV ECX, [EBP{sign}0x{magnitude:x}]; JMP)",
                    f"8b 4d {disp_unsigned:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        mov ecx, [ebp {sign} {magnitude}]\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind MOV ECX,[EBP{sign}{magnitude}]")
    return None


def try_unwind_lea_ebp_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8d 4d NN e9 RR RR RR RR — LEA ECX, [EBP+disp8]; JMP rel32
    # SEH unwind helper that takes the ADDRESS of a stack-frame
    # local (rather than loading a pointer from one). Used when
    # the parent's local IS the object being destructed (vs a
    # pointer to it).
    if len(body) == 8 and body[0:2] == b"\x8d\x4d" and body[3] == 0xe9:
        disp_unsigned = body[2]
        disp_signed = disp_unsigned - 256 if disp_unsigned >= 0x80 else disp_unsigned
        sign = "-" if disp_signed < 0 else "+"
        magnitude = abs(disp_signed)
        src = (
            _header(va, f"SEH unwind helper (LEA ECX, [EBP{sign}0x{magnitude:x}]; JMP)",
                    f"8d 4d {disp_unsigned:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        lea ecx, [ebp {sign} {magnitude}]\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind LEA ECX,[EBP{sign}{magnitude}]")
    return None


def try_unwind_lea_ebp_disp32_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8d 8d NN NN NN NN e9 RR RR RR RR (11 bytes)
    # LEA ECX, [EBP+disp32]; JMP rel32 — disp32 form, used when the
    # frame offset is outside int8 range.
    if len(body) == 11 and body[0:2] == b"\x8d\x8d" and body[6] == 0xe9:
        disp_u = int.from_bytes(body[2:6], "little", signed=False)
        disp_s = int.from_bytes(body[2:6], "little", signed=True)
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"SEH unwind helper (LEA ECX, [EBP{sign}0x{mag:x}]; JMP) — disp32",
                    f"8d 8d {disp_u:08x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        lea ecx, [ebp {sign} {mag}]\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind LEA ECX,[EBP{sign}{mag}] disp32")
    return None


def try_unwind_mov_ebp_disp32_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 8d NN NN NN NN e9 RR RR RR RR (11 bytes)
    # MOV ECX, [EBP+disp32]; JMP rel32 — disp32 form.
    if len(body) == 11 and body[0:2] == b"\x8b\x8d" and body[6] == 0xe9:
        disp_u = int.from_bytes(body[2:6], "little", signed=False)
        disp_s = int.from_bytes(body[2:6], "little", signed=True)
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"SEH unwind helper (MOV ECX, [EBP{sign}0x{mag:x}]; JMP) — disp32",
                    f"8b 8d {disp_u:08x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        mov ecx, [ebp {sign} {mag}]\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind MOV ECX,[EBP{sign}{mag}] disp32")
    return None


def try_clear_flag_in_global(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # a1 GG GG GG GG 83 e0 MM a3 GG GG GG GG c3   (14 bytes)
    # MOV EAX, [global]; AND EAX, imm8 (sign-extended); MOV [global], EAX; RET
    # Same global address loaded and stored — clears bits in a global flag.
    if (len(body) == 14 and body[0] == 0xa1 and body[5:7] == b"\x83\xe0"
            and body[8] == 0xa3 and body[13] == 0xc3):
        global_load = int.from_bytes(body[1:5], "little")
        global_store = int.from_bytes(body[9:13], "little")
        if global_load != global_store:
            return None
        mask = body[7]
        # The 0x83 e0 encoding takes a *signed* int8 immediate that
        # sign-extends to 32 bits. We must express the C++ source value
        # the same way, otherwise MSVC's inline assembler picks the
        # 32-bit imm encoding (`25 imm32`) which is 16 bytes total —
        # we want 14. Use the signed decimal form so the assembler
        # recognises it as a signed byte.
        mask_signed = mask - 256 if mask >= 0x80 else mask
        src = (
            _header(va, f"global flag clear (AND imm8 0x{mask:x} = {mask_signed})",
                    f"a1 GG GG GG GG 83 e0 {mask:02x} a3 GG GG GG GG c3", n)
            + "\nextern \"C\" int the_global;\n\n"
            + "extern \"C\" __declspec(naked) void clear_flag() {\n"
            + "    __asm {\n"
            + "        mov eax, dword ptr [the_global]\n"
            + f"        and eax, {mask_signed}\n"
            + "        mov dword ptr [the_global], eax\n"
            + "        ret\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"global AND-clear 0x{mask:x}")
    return None


def try_push_load_call(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 45 NN 50 e8 RR RR RR RR (9 bytes)
    # MOV EAX, [EBP+disp8]; PUSH EAX; CALL rel32
    # Common SEH unwind helper — push a stack-saved object pointer and
    # call its destructor / cleanup function. Falls through (no RET) so
    # caller's RET drives control flow.
    if len(body) == 9 and body[0:2] == b"\x8b\x45" and body[3] == 0x50 and body[4] == 0xe8:
        disp_u = body[2]
        disp_s = disp_u - 256 if disp_u >= 0x80 else disp_u
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"unwind helper (MOV EAX, [EBP{sign}0x{mag:x}]; PUSH EAX; CALL)",
                    f"8b 45 {disp_u:02x} 50 e8 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void push_call_helper() {\n"
            + "    __asm {\n"
            + f"        mov eax, [ebp {sign} {mag}]\n"
            + "        push eax\n"
            + "        call target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"push-call EBP{sign}{mag}")
    return None


def try_unwind_2arg_call_17b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 17B 2-arg call helper:
    #   8b 45 e4              MOV EAX, [EBP-0x1c]
    #   50                    PUSH EAX
    #   8b 4d e8              MOV ECX, [EBP-0x18]
    #   51                    PUSH ECX
    #   e8 RR RR RR RR        CALL extern
    #   83 c4 08              ADD ESP, 8
    #   c3                    RET
    if len(body) != 17:
        return None
    expected = [
        (0x8b,), (0x45,), None,             # disp8 varies between cluster members? no — fixed
        (0x50,),
        (0x8b,), (0x4d,), None,             # ditto
        (0x51,),
        (0xe8,), None, None, None, None,
        (0x83,), (0xc4,), (0x08,),
        (0xc3,),
    ]
    # The disp8 bytes ARE part of the cluster identity (not relocs), so
    # they're constant across the cluster — read them from this rep.
    if not (body[0] == 0x8b and body[1] == 0x45
            and body[3] == 0x50
            and body[4] == 0x8b and body[5] == 0x4d
            and body[7] == 0x51 and body[8] == 0xe8
            and body[13:17] == b"\x83\xc4\x08\xc3"):
        return None
    arg1_disp_u = body[2]
    arg2_disp_u = body[6]
    arg1_signed = arg1_disp_u - 256 if arg1_disp_u >= 0x80 else arg1_disp_u
    arg2_signed = arg2_disp_u - 256 if arg2_disp_u >= 0x80 else arg2_disp_u
    a1_sign = "-" if arg1_signed < 0 else "+"
    a2_sign = "-" if arg2_signed < 0 else "+"
    a1_mag = abs(arg1_signed)
    a2_mag = abs(arg2_signed)
    src = (
        _header(va, f"unwind helper — 2-arg PUSH+PUSH+CALL "
                    f"([EBP{a1_sign}0x{a1_mag:x}]+[EBP{a2_sign}0x{a2_mag:x}])",
                f"8b 45 {arg1_disp_u:02x} 50 8b 4d {arg2_disp_u:02x} 51 "
                f"e8 RR RR RR RR 83 c4 08 c3", n)
        + "\nextern \"C\" int target();\n\n"
          "extern \"C\" __declspec(naked) void unwind_2arg() {\n"
          "    __asm {\n"
        + f"        mov eax, [ebp {a1_sign} {a1_mag}]\n"
          "        push eax\n"
        + f"        mov ecx, [ebp {a2_sign} {a2_mag}]\n"
          "        push ecx\n"
          "        call target\n"
          "        add esp, 8\n"
          "        ret\n"
          "    }\n"
          "}\n"
    )
    return (src, f"unwind 2-arg-call EBP{a1_sign}{a1_mag},EBP{a2_sign}{a2_mag}")


def try_vtbl_dispatch_25b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 25B vtable-dispatch trampoline (MSVC scalar deleting destructor
    # forwarder). Shape:
    #
    #   8b 4c 24 04                  MOV ECX, [ESP+4]
    #   85 c9                        TEST ECX, ECX
    #   74 0e                        JZ +14
    #   8b 01                        MOV EAX, [ECX]      (vtable ptr)
    #   8b 10                        MOV EDX, [EAX]      (slot 0 = ~)
    #   c7 44 24 04 01 00 00 00      MOV [ESP+4], 1     (set delete flag)
    #   ff e2                        JMP EDX            (tail to dtor)
    #   c2 04 00                     RET 4
    expected = bytes.fromhex(
        "8b4c2404 85c9 740e 8b01 8b10 c7442404 01000000 ffe2 c20400".replace(" ", "")
    )
    if body == expected:
        src = (
            _header(va, "vtable-dispatch trampoline (~scalar-deleting forwarder)",
                    "8b 4c 24 04 85 c9 74 0e 8b 01 8b 10 c7 44 24 04 "
                    "01 00 00 00 ff e2 c2 04 00", n)
            + "\nextern \"C\" __declspec(naked) void vtbl_forwarder() {\n"
              "    __asm {\n"
              "        mov ecx, [esp + 4]\n"
              "        test ecx, ecx\n"
              "        jz no_call\n"
              "        mov eax, [ecx]\n"
              "        mov edx, [eax]\n"
              "        mov dword ptr [esp + 4], 1\n"
              "        jmp edx\n"
              "    no_call:\n"
              "        ret 4\n"
              "    }\n"
              "}\n"
        )
        return (src, "vtbl-forwarder 25B")
    return None


def try_arg_shuffler_41b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 41B __stdcall arg-shuffler that reorders 3 dword args + 1 byte
    # arg before tail-calling another function. Shape:
    #
    #   51                    PUSH ECX                  (slot for byte arg)
    #   8b 54 24 10           MOV EDX, [ESP+0x10]       (arg3 → EDX)
    #   c6 04 24 00           MOV byte ptr [ESP], 0     (zero the byte slot)
    #   8b 04 24              MOV EAX, [ESP]
    #   50                    PUSH EAX                  (push the byte arg)
    #   8b 44 24 14           MOV EAX, [ESP+0x14]
    #   52                    PUSH EDX
    #   8b 54 24 10           MOV EDX, [ESP+0x10]
    #   51                    PUSH ECX
    #   8b 4c 24 18           MOV ECX, [ESP+0x18]
    #   50                    PUSH EAX
    #   51                    PUSH ECX
    #   52                    PUSH EDX
    #   e8 RR RR RR RR        CALL <target>
    #   83 c4 1c              ADD ESP, 0x1c
    #   c2 0c 00              RET 12
    if len(body) != 41:
        return None
    expected = [
        (0x51,),
        (0x8b,), (0x54,), (0x24,), (0x10,),
        (0xc6,), (0x04,), (0x24,), (0x00,),
        (0x8b,), (0x04,), (0x24,),
        (0x50,),
        (0x8b,), (0x44,), (0x24,), (0x14,),
        (0x52,),
        (0x8b,), (0x54,), (0x24,), (0x10,),
        (0x51,),
        (0x8b,), (0x4c,), (0x24,), (0x18,),
        (0x50,),
        (0x51,),
        (0x52,),
        (0xe8,), None, None, None, None,
        (0x83,), (0xc4,), (0x1c,),
        (0xc2,), (0x0c,), (0x00,),
    ]
    for i, exp in enumerate(expected):
        if exp is None:
            continue
        if body[i] != exp[0]:
            return None
    src = (
        _header(va, "__stdcall arg-shuffler (3 dword args + 1 byte)",
                "51 8b 54 24 10 c6 04 24 00 8b 04 24 50 8b 44 24 14 "
                "52 8b 54 24 10 51 8b 4c 24 18 50 51 52 e8 RR RR RR RR "
                "83 c4 1c c2 0c 00", n)
        + "\nextern \"C\" int target();\n\n"
          "extern \"C\" __declspec(naked) void arg_shuffler() {\n"
          "    __asm {\n"
          "        push ecx\n"
          "        mov edx, [esp + 0x10]\n"
          "        mov byte ptr [esp], 0\n"
          "        mov eax, [esp]\n"
          "        push eax\n"
          "        mov eax, [esp + 0x14]\n"
          "        push edx\n"
          "        mov edx, [esp + 0x10]\n"
          "        push ecx\n"
          "        mov ecx, [esp + 0x18]\n"
          "        push eax\n"
          "        push ecx\n"
          "        push edx\n"
          "        call target\n"
          "        add esp, 0x1c\n"
          "        ret 12\n"
          "    }\n"
          "}\n"
    )
    return (src, "arg-shuffler 41B")


def try_catch_all_push_call_9b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 9B SEH Catch_All handler:
    #   6a 00 6a 00 e8 RR RR RR RR
    #   PUSH 0; PUSH 0; CALL rel32 — fall-through (no RET; unwinder
    #   takes over after the called function returns).
    if len(body) == 9 and body[0:4] == b"\x6a\x00\x6a\x00" and body[4] == 0xe8:
        src = (
            _header(va, "SEH Catch_All handler (PUSH 0; PUSH 0; CALL ...)",
                    "6a 00 6a 00 e8 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void catch_all_handler() {\n"
              "    __asm {\n"
              "        push 0\n"
              "        push 0\n"
              "        call target\n"
              "    }\n"
              "}\n"
        )
        return (src, "catch-all PUSH 0; PUSH 0; CALL")
    return None


def try_array_deleting_dtor_34b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 34B variant of scalar-deleting-dtor with NULL check + alloc-block
    # offset (used for arrays). Shape:
    #
    #   56 8b f1                                    PUSH ESI; MOV ESI, ECX
    #   e8 RR RR RR RR                              CALL ~C()
    #   f6 44 24 08 01                              TEST flag
    #   74 0d                                       JZ +13
    #   85 f6                                       TEST ESI, ESI       (null check)
    #   74 09                                       JZ +9               (skip on null)
    #   8b 4e fc                                    MOV ECX, [ESI-4]    (alloc-block ptr)
    #   56                                          PUSH ESI
    #   e8 RR RR RR RR                              CALL operator delete[]
    #   8b c6 5e c2 04 00                           MOV EAX,ESI; POP ESI; RET 4
    if len(body) != 34:
        return None
    expected = [
        (0x56,), (0x8b,), (0xf1,),
        (0xe8,), None, None, None, None,
        (0xf6,), (0x44,), (0x24,), (0x08,), (0x01,),
        (0x74,), (0x0d,),
        (0x85,), (0xf6,),
        (0x74,), (0x09,),
        (0x8b,), (0x4e,), (0xfc,),
        (0x56,),
        (0xe8,), None, None, None, None,
        (0x8b,), (0xc6,), (0x5e,), (0xc2,), (0x04,), (0x00,),
    ]
    for i, exp in enumerate(expected):
        if exp is None:
            continue
        if body[i] != exp[0]:
            return None
    src = (
        _header(va, "MSVC array deleting destructor (34B form, null+alloc-block)",
                "56 8b f1 e8 RR RR RR RR f6 44 24 08 01 74 0d 85 f6 74 09 "
                "8b 4e fc 56 e8 RR RR RR RR 8b c6 5e c2 04 00", n)
        + "\nextern \"C\" int real_dtor();\n"
          "extern \"C\" int operator_delete_array();\n\n"
          "extern \"C\" __declspec(naked) void array_deleting_dtor() {\n"
          "    __asm {\n"
          "        push esi\n"
          "        mov esi, ecx\n"
          "        call real_dtor\n"
          "        test byte ptr [esp+8], 1\n"
          "        jz no_delete\n"
          "        test esi, esi\n"
          "        jz no_delete2\n"
          "        mov ecx, [esi - 4]\n"
          "        push esi\n"
          "        call operator_delete_array\n"
          "    no_delete2:\n"
          "    no_delete:\n"
          "        mov eax, esi\n"
          "        pop esi\n"
          "        ret 4\n"
          "    }\n"
          "}\n"
    )
    return (src, "array-deleting-dtor 34B")


def try_unwind_flag_check_jmp_25b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 25B SEH unwind helper that gates the destructor on a flag bit:
    #
    #   8b 45 f0                MOV EAX, [EBP-0x10]
    #   83 e0 01                AND EAX, 1
    #   0f 84 0c 00 00 00       JZ FAR +0xc                (long-form JZ)
    #   83 65 f0 fe             AND [EBP-0x10], 0xfffffffe (clear low bit)
    #   8b 4d 04                MOV ECX, [EBP+4]
    #   e9 RR RR RR RR          JMP rel32                  (tail to dtor)
    #   c3                      RET                        (only when bit was 0)
    if len(body) != 25:
        return None
    expected = [
        (0x8b,), (0x45,), (0xf0,),
        (0x83,), (0xe0,), (0x01,),
        (0x0f,), (0x84,), (0x0c,), (0x00,), (0x00,), (0x00,),
        (0x83,), (0x65,), (0xf0,), (0xfe,),
        (0x8b,), (0x4d,), (0x04,),
        (0xe9,), None, None, None, None,
        (0xc3,),
    ]
    for i, exp in enumerate(expected):
        if exp is None:
            continue
        if body[i] != exp[0]:
            return None
    src = (
        _header(va, "SEH unwind helper (flag-test → tail-call dtor; 25B)",
                "8b 45 f0 83 e0 01 0f 84 0c 00 00 00 83 65 f0 fe "
                "8b 4d 04 e9 RR RR RR RR c3", n)
        + "\nextern \"C\" int target();\n\n"
          "extern \"C\" __declspec(naked) void unwind_flag_check() {\n"
          "    __asm {\n"
          "        mov eax, [ebp - 16]\n"
          "        and eax, 1\n"
          "        ; force long-form JZ (cl.exe defaults to short).\n"
          "        _emit 0x0f\n"
          "        _emit 0x84\n"
          "        _emit 0x0c\n"
          "        _emit 0x00\n"
          "        _emit 0x00\n"
          "        _emit 0x00\n"
          "        and dword ptr [ebp - 16], -2\n"
          "        mov ecx, [ebp + 4]\n"
          "        jmp target\n"
          "        ret\n"
          "    }\n"
          "}\n"
    )
    return (src, "unwind flag-check 25B")


def try_scalar_deleting_dtor_30b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # MSVC-emitted "scalar deleting destructor" — appears in every class
    # vtable that has a virtual destructor. Shape (30 bytes):
    #
    #   56                    PUSH ESI                  (save ESI)
    #   8b f1                 MOV ESI, ECX              (this → ESI)
    #   e8 RR RR RR RR        CALL <real ~C()>          (reloc)
    #   f6 44 24 08 01        TEST byte ptr [ESP+8], 1  (delete-flag arg)
    #   74 09                 JZ +9                     (skip delete)
    #   56                    PUSH ESI                  (push this)
    #   e8 RR RR RR RR        CALL operator delete      (reloc)
    #   83 c4 04              ADD ESP, 4                (clean up arg)
    #   8b c6                 MOV EAX, ESI              (return this)
    #   5e                    POP ESI
    #   c2 04 00              RET 4                     (pop the flag arg)
    expected = (
        b"\x56\x8b\xf1\xe8" + b"\x00" * 4 +     # 0:PUSH ESI; MOV ESI,ECX; CALL ~C
        b"\xf6\x44\x24\x08\x01\x74\x09\x56" +   # 8:TEST flag; JZ +9; PUSH ESI
        b"\xe8" + b"\x00" * 4 +                 # 16:CALL operator delete
        b"\x83\xc4\x04\x8b\xc6\x5e\xc2\x04\x00" # 21:ADD ESP,4; MOV EAX,ESI; POP ESI; RET 4
    )
    if len(body) != 30:
        return None
    # Match every byte except the two reloc rel32 fields.
    fixed_mask = bytes(0xff for _ in expected)
    fixed_mask = bytearray(fixed_mask)
    fixed_mask[4:8] = b"\x00" * 4   # CALL ~C reloc
    fixed_mask[17:21] = b"\x00" * 4 # CALL delete reloc
    for i, m in enumerate(fixed_mask):
        if m == 0:
            continue
        if body[i] != expected[i]:
            return None
    src = (
        _header(va, "MSVC scalar deleting destructor (30B form)",
                "56 8b f1 e8 RR RR RR RR f6 44 24 08 01 74 09 56 "
                "e8 RR RR RR RR 83 c4 04 8b c6 5e c2 04 00", n)
        + "\nextern \"C\" int real_dtor();\n"
          "extern \"C\" int operator_delete();\n\n"
          "extern \"C\" __declspec(naked) void scalar_deleting_dtor() {\n"
          "    __asm {\n"
          "        push esi\n"
          "        mov esi, ecx\n"
          "        call real_dtor\n"
          "        test byte ptr [esp+8], 1\n"
          "        jz no_delete\n"
          "        push esi\n"
          "        call operator_delete\n"
          "        add esp, 4\n"
          "    no_delete:\n"
          "        mov eax, esi\n"
          "        pop esi\n"
          "        ret 4\n"
          "    }\n"
          "}\n"
    )
    return (src, "scalar-deleting-dtor 30B")


def try_scalar_deleting_dtor_32b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 32-byte variant with custom allocator: same shape as 30B but
    # MOV ECX, <global allocator> before the delete call. Shape:
    #
    #   56 8b f1                                  PUSH ESI; MOV ESI, ECX
    #   e8 RR RR RR RR                            CALL real ~C()
    #   f6 44 24 08 01                            TEST flag
    #   74 0b                                     JZ +11
    #   56                                        PUSH ESI
    #   b9 GG GG GG GG                            MOV ECX, &allocator
    #   e8 RR RR RR RR                            CALL operator delete with alloc
    #   8b c6 5e c2 04 00                         MOV EAX,ESI; POP ESI; RET 4
    if len(body) != 32:
        return None
    expected_template = [
        (0x56,), (0x8b,), (0xf1,),
        (0xe8,), None, None, None, None,         # CALL ~C() opcode + 4-byte reloc
        (0xf6,), (0x44,), (0x24,), (0x08,), (0x01,),
        (0x74,), (0x0b,),
        (0x56,),
        (0xb9,), None, None, None, None,         # MOV ECX, alloc opcode + 4-byte reloc
        (0xe8,), None, None, None, None,         # CALL delete opcode + 4-byte reloc
        (0x8b,), (0xc6,), (0x5e,), (0xc2,), (0x04,), (0x00,),
    ]
    expected = b"\xe8" + b"\x00" * 4   # placeholder, not used directly
    for i, exp in enumerate(expected_template):
        if exp is None:
            continue
        if body[i] != exp[0]:
            return None
    src = (
        _header(va, "MSVC scalar deleting destructor (32B form, custom allocator)",
                "56 8b f1 e8 RR RR RR RR f6 44 24 08 01 74 0b 56 "
                "b9 GG GG GG GG e8 RR RR RR RR 8b c6 5e c2 04 00", n)
        + "\nextern \"C\" int real_dtor();\n"
          "extern \"C\" int operator_delete_alloc();\n"
          "extern \"C\" int the_allocator;\n\n"
          "extern \"C\" __declspec(naked) void scalar_deleting_dtor_alloc() {\n"
          "    __asm {\n"
          "        push esi\n"
          "        mov esi, ecx\n"
          "        call real_dtor\n"
          "        test byte ptr [esp+8], 1\n"
          "        jz no_delete\n"
          "        push esi\n"
          "        mov ecx, offset the_allocator\n"
          "        call operator_delete_alloc\n"
          "    no_delete:\n"
          "        mov eax, esi\n"
          "        pop esi\n"
          "        ret 4\n"
          "    }\n"
          "}\n"
    )
    return (src, "scalar-deleting-dtor 32B alloc")


def try_return_global_addr(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # b8 GG GG GG GG c3 (6 bytes)
    # MOV EAX, imm32; RET. Returns a constant 32-bit value — typically
    # the address of a global, but could also be an arbitrary const.
    # Reloc-equivalent shape: every cluster member shares the same
    # encoding shape but with a different reloc target (the imm32).
    if len(body) == 6 and body[0] == 0xb8 and body[5] == 0xc3:
        # Treat the imm32 as a relocated address — emit `&the_global`.
        src = (
            _header(va, "return global address (MOV EAX, &global; RET)",
                    "b8 GG GG GG GG c3", n)
            + "\nextern \"C\" int the_global;\n\n"
            + "extern \"C\" int *get_global_addr() {\n"
              "    return &the_global;\n"
              "}\n"
        )
        return (src, "return-global-addr")
    return None


def try_unwind_mov_ebp_add32_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 4d NN 81 c1 MM MM MM MM e9 RR RR RR RR (14 bytes)
    # MOV ECX, [EBP+disp8]; ADD ECX, imm32; JMP rel32
    # disp32-ADD variant of `try_unwind_mov_ebp_add_jmp`. Used when
    # the additional subobject offset is outside int8 range.
    if (len(body) == 14 and body[0:2] == b"\x8b\x4d" and body[3:5] == b"\x81\xc1"
            and body[9] == 0xe9):
        ebp_disp_u = body[2]
        ebp_disp_s = ebp_disp_u - 256 if ebp_disp_u >= 0x80 else ebp_disp_u
        ebp_sign = "-" if ebp_disp_s < 0 else "+"
        ebp_mag = abs(ebp_disp_s)
        add_imm = int.from_bytes(body[5:9], "little")
        src = (
            _header(va,
                    f"SEH unwind helper (MOV ECX, [EBP{ebp_sign}0x{ebp_mag:x}]; ADD ECX, 0x{add_imm:x}; JMP)",
                    f"8b 4d {ebp_disp_u:02x} 81 c1 {add_imm:08x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        mov ecx, [ebp {ebp_sign} {ebp_mag}]\n"
            + f"        add ecx, {add_imm}\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind MOV+ADD32 ECX,[EBP{ebp_sign}{ebp_mag}]+{add_imm}")
    return None


def try_unwind_mov_ebp_add_jmp(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 4d NN 83 c1 MM e9 RR RR RR RR (11 bytes)
    # MOV ECX, [EBP+disp8]; ADD ECX, imm8; JMP rel32
    # Variant where the saved pointer needs an additional offset
    # (e.g. base-class subobject inside a frame-stored derived).
    if len(body) == 11 and body[0:2] == b"\x8b\x4d" and body[3:5] == b"\x83\xc1" and body[6] == 0xe9:
        ebp_disp_u = body[2]
        ebp_disp_s = ebp_disp_u - 256 if ebp_disp_u >= 0x80 else ebp_disp_u
        ebp_sign = "-" if ebp_disp_s < 0 else "+"
        ebp_mag = abs(ebp_disp_s)
        add_imm = body[5]
        src = (
            _header(va,
                    f"SEH unwind helper (MOV ECX, [EBP{ebp_sign}0x{ebp_mag:x}]; ADD ECX, 0x{add_imm:x}; JMP)",
                    f"8b 4d {ebp_disp_u:02x} 83 c1 {add_imm:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void unwind_thunk() {\n"
            + "    __asm {\n"
            + f"        mov ecx, [ebp {ebp_sign} {ebp_mag}]\n"
            + f"        add ecx, {add_imm}\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"unwind MOV+ADD ECX,[EBP{ebp_sign}{ebp_mag}]+{add_imm}")
    return None


def try_adjustor_thunk_sub_imm32(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 81 e9 NN NN NN NN e9 RR RR RR RR — SUB ECX, imm32; JMP rel32
    # Same as imm8 form but for offsets ≥ 0x80 (8-bit signed range exhausted).
    if len(body) == 11 and body[0:2] == b"\x81\xe9" and body[6] == 0xe9:
        offset = int.from_bytes(body[2:6], "little")
        if offset == 0:
            return None
        src = (
            _header(va, f"multi-inheritance `this`-adjustor (SUB ECX, 0x{offset:x}; JMP)",
                    f"81 e9 {offset:08x} (LE) e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
            + "extern \"C\" __declspec(naked) void adjustor_thunk() {\n"
            + "    __asm {\n"
            + f"        sub ecx, {offset}\n"
            + "        jmp target\n"
            + "    }\n"
            + "}\n"
        )
        return (src, f"adjustor SUB imm32 {offset}")
    return None


def try_chained_ptr_getter(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8b 41 NN 8b 40 MM c3 — MOV EAX,[ECX+NN]; MOV EAX,[EAX+MM]; RET
    # Both NN and MM are *signed* int8 displacements as encoded.
    if not (len(body) == 7 and body[0] == 0x8b and body[1] == 0x41 and body[3] == 0x8b
            and body[4] == 0x40 and body[6] == 0xc3):
        return None

    raw_outer = body[2]
    raw_inner = body[5]
    outer_signed = raw_outer - 256 if raw_outer >= 0x80 else raw_outer
    inner_signed = raw_inner - 256 if raw_inner >= 0x80 else raw_inner

    # Negative or non-multiple-of-4 offsets can't be expressed cleanly as
    # C++ field accesses without forcing the compiler to a 32-bit disp32
    # (which inflates 7 bytes → 10). Fall back to naked inline asm: byte-
    # exact regardless of sign, at the cost of less readable source.
    has_negative = outer_signed < 0 or inner_signed < 0
    misaligned = (outer_signed % 4 != 0) or (inner_signed % 4 != 0)
    if has_negative or misaligned:
        return _chained_ptr_naked(body, va, n, outer_signed, inner_signed)

    outer_off = outer_signed
    inner_off = inner_signed
    if outer_off == 0:
        return None
    outer_pad = _padding_for_offset(outer_off, "int")
    if inner_off == 0:
        inner_decl = "class Inner {\npublic:\n    int *field;\n};"
    else:
        n_pad = inner_off // 4
        inner_decl = f"class Inner {{\n    int padding[{n_pad}];\npublic:\n    int *field;\n}};"
    src = (
        _header(va, f"chained ptr getter (this->[+0x{outer_off:x}]->field+0x{inner_off:x})",
                f"8b 41 {raw_outer:02x} 8b 40 {raw_inner:02x} c3", n)
        + f"\n{inner_decl}\n\nclass Outer {{\n"
        + (f"    {outer_pad}\n" if outer_pad else "")
        + f"    Inner *inner;\npublic:\n    int *get_inner_field();\n}};\n\n"
          f"int *Outer::get_inner_field() {{ return inner->field; }}\n"
    )
    return (src, f"chained ptr @ 0x{outer_off:x}/0x{inner_off:x}")


def _chained_ptr_naked(body: bytes, va: int, n: int, outer: int, inner: int) -> tuple[str, str]:
    raw_outer = body[2]
    raw_inner = body[5]
    outer_sign = "-" if outer < 0 else "+"
    inner_sign = "-" if inner < 0 else "+"
    outer_mag = abs(outer)
    inner_mag = abs(inner)
    src = (
        _header(va, f"chained ptr getter (signed-disp; naked asm) "
                    f"this->[ECX{outer_sign}0x{outer_mag:x}]->field+0x{inner_mag:x}",
                f"8b 41 {raw_outer:02x} 8b 40 {raw_inner:02x} c3", n)
        + "\nextern \"C\" __declspec(naked) int *chained_ptr_getter() {\n"
          "    __asm {\n"
        + f"        mov eax, [ecx {outer_sign} {outer_mag}]\n"
        + f"        mov eax, [eax {inner_sign} {inner_mag}]\n"
          "        ret\n"
          "    }\n"
          "}\n"
    )
    return (src, f"chained ptr (naked) @ {outer_sign}0x{outer_mag:x}/{inner_sign}0x{inner_mag:x}")


def try_return_global_value_6b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 6B `a1 RR RR RR RR c3` — returns the *value* of a global int.
    # Distinct from `b8 RR RR RR RR c3` (return-global-ADDR) handled by
    # try_return_global_addr.
    if len(body) == 6 and body[0] == 0xa1 and body[5] == 0xc3:
        src = (
            _header(va, "return global value (MOV EAX, [&global]; RET)",
                    "a1 GG GG GG GG c3", n)
            + "\nextern \"C\" int the_global;\n\n"
              "extern \"C\" int get_global_value() { return the_global; }\n"
        )
        return (src, "return-global-val")
    return None


def try_store_arg_to_global_10b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 10B `8b 44 24 04 a3 RR RR RR RR c3` —
    # MOV EAX, [ESP+4]; MOV [&global], EAX; RET.
    # Pure setter for a global int.
    expected = b"\x8b\x44\x24\x04\xa3"
    if len(body) == 10 and body[0:5] == expected and body[9] == 0xc3:
        src = (
            _header(va, "set global value (from arg1)",
                    "8b 44 24 04 a3 GG GG GG GG c3", n)
            + "\nextern \"C\" int the_global;\n\n"
              "extern \"C\" void set_global(int v) { the_global = v; }\n"
        )
        return (src, "set-global-val")
    return None


def try_import_thunk_jmp_m32(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 6B `ff 25 RR RR RR RR` — JMP DWORD PTR [imm32]. Import-table thunk
    # that forwards to a DLL function via the IAT slot. Falls through
    # (no RET — JMP is the terminator).
    #
    # Source must declare the target as a *function pointer variable*
    # (not a function), otherwise MSVC compiles `jmp [target]` as
    # `jmp NEAR target` (`e9 RR RR RR RR`, 5 bytes — relative jump to
    # the function), which doesn't match the IAT-indirect 6-byte form.
    # `jmp dword ptr [func_ptr]` correctly emits `ff 25 RR RR RR RR`.
    if len(body) == 6 and body[0:2] == b"\xff\x25":
        src = (
            _header(va, "import thunk (JMP DWORD PTR [iat_slot])",
                    "ff 25 GG GG GG GG", n)
            + "\nextern \"C\" int (*target_iat_slot)();\n\n"
              "extern \"C\" __declspec(naked) void import_thunk() {\n"
              "    __asm {\n"
              "        jmp dword ptr [target_iat_slot]\n"
              "    }\n"
              "}\n"
        )
        return (src, "import-thunk JMP[iat]")
    return None


def try_load_this_jmp_indirect_7b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 7B `8b 09 e9 RR RR RR RR` — MOV ECX, [ECX]; JMP rel32.
    # Loads `*this` into ECX (typically: turn `this` from a wrapper to
    # the inner pointer at offset 0) and tail-calls another method.
    # No RET; JMP is the terminator.
    if len(body) == 7 and body[0:3] == b"\x8b\x09\xe9":
        src = (
            _header(va, "deref-this then JMP",
                    "8b 09 e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void deref_then_jmp() {\n"
              "    __asm {\n"
              "        mov ecx, [ecx]\n"
              "        jmp target\n"
              "    }\n"
              "}\n"
        )
        return (src, "deref-this JMP")
    return None


def try_push_local_call_pop_11b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 11B `8b 45 NN 50 e8 RR RR RR RR 59 c3` —
    # MOV EAX, [EBP+disp8]; PUSH EAX; CALL extern; POP ECX; RET.
    # Variation of try_push_load_call but with a RET instead of fall-
    # through. The POP ECX cleans up the pushed arg.
    if (len(body) == 11 and body[0:2] == b"\x8b\x45" and body[3] == 0x50
            and body[4] == 0xe8 and body[9] == 0x59 and body[10] == 0xc3):
        disp_u = body[2]
        disp_s = disp_u - 256 if disp_u >= 0x80 else disp_u
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"push-local-call-pop ([EBP{sign}0x{mag:x}]; CALL; POP ECX; RET)",
                    f"8b 45 {disp_u:02x} 50 e8 RR RR RR RR 59 c3", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void push_call_pop() {\n"
              "    __asm {\n"
            + f"        mov eax, [ebp {sign} {mag}]\n"
              "        push eax\n"
              "        call target\n"
              "        pop ecx\n"
              "        ret\n"
              "    }\n"
              "}\n"
        )
        return (src, f"push-call-pop EBP{sign}{mag}")
    return None


def try_release_then_free_22b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 22B "if non-null, release-then-stdcall-free" wrapper. The free
    # function is __stdcall (callee cleans up the pushed arg), so no
    # POP ECX between CALL and POP ESI:
    #   56                    PUSH ESI
    #   8b 31                 MOV ESI, [ECX]      (load resource ptr)
    #   85 f6                 TEST ESI, ESI
    #   74 0e                 JZ +0x0e
    #   8b ce                 MOV ECX, ESI
    #   e8 RR RR RR RR        CALL release        (thiscall)
    #   56                    PUSH ESI
    #   e8 RR RR RR RR        CALL free__stdcall
    #   5e                    POP ESI
    #   c3                    RET
    if len(body) != 22:
        return None
    # Match positions explicitly — last 2 bytes are POP ESI; RET (no
    # POP ECX, since the second CALL is __stdcall-cleanup).
    if not (body[0] == 0x56 and body[1] == 0x8b and body[2] == 0x31
            and body[3] == 0x85 and body[4] == 0xf6
            and body[5] == 0x74
            and body[7] == 0x8b and body[8] == 0xce
            and body[9] == 0xe8
            and body[14] == 0x56
            and body[15] == 0xe8
            and body[20] == 0x5e and body[21] == 0xc3):
        return None
    src = (
        _header(va, "release-then-free wrapper (TEST [this]; CALL release; CALL stdcall-free)",
                "56 8b 31 85 f6 74 NN 8b ce e8 RR RR RR RR 56 e8 RR RR RR RR 5e c3", n)
        + "\nextern \"C\" int release();\n"
          "extern \"C\" int free_resource();\n\n"
          "extern \"C\" __declspec(naked) void release_then_free() {\n"
          "    __asm {\n"
          "        push esi\n"
          "        mov esi, [ecx]\n"
          "        test esi, esi\n"
          "        jz no_call\n"
          "        mov ecx, esi\n"
          "        call release\n"
          "        push esi\n"
          "        call free_resource\n"
          "    no_call:\n"
          "        pop esi\n"
          "        ret\n"
          "    }\n"
          "}\n"
    )
    return (src, "release-then-free 22B")


def try_seh_catch_call_call_17b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 17B SEH catch: load local; call; PUSH 0; PUSH 0; call (no RET).
    #   8b 4d ec              MOV ECX, [EBP-0x14]
    #   e8 RR RR RR RR        CALL func1
    #   6a 00 6a 00           PUSH 0; PUSH 0
    #   e8 RR RR RR RR        CALL func2     (terminator — falls through)
    if len(body) != 17:
        return None
    expected = [
        (0x8b,), (0x4d,), None,                     # MOV ECX, [EBP+disp8]
        (0xe8,), None, None, None, None,
        (0x6a,), (0x00,), (0x6a,), (0x00,),
        (0xe8,), None, None, None, None,
    ]
    if not all(exp is None or body[i] == exp[0] for i, exp in enumerate(expected)):
        return None
    disp_u = body[2]
    disp_s = disp_u - 256 if disp_u >= 0x80 else disp_u
    sign = "-" if disp_s < 0 else "+"
    mag = abs(disp_s)
    src = (
        _header(va, f"SEH catch (MOV ECX, [EBP{sign}0x{mag:x}]; CALL; PUSH 0,0; CALL)",
                f"8b 4d {disp_u:02x} e8 RR RR RR RR 6a 00 6a 00 e8 RR RR RR RR", n)
        + "\nextern \"C\" int target1();\nextern \"C\" int target2();\n\n"
          "extern \"C\" __declspec(naked) void seh_catch() {\n"
          "    __asm {\n"
        + f"        mov ecx, [ebp {sign} {mag}]\n"
          "        call target1\n"
          "        push 0\n"
          "        push 0\n"
          "        call target2\n"
          "    }\n"
          "}\n"
    )
    return (src, f"seh-catch [EBP{sign}{mag}]+call+push00+call")


def try_push_str_then_call_14b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 14B "push fixed pointer; call; cleanup":
    #   68 GG GG GG GG        PUSH offset arg1
    #   e8 RR RR RR RR        CALL extern
    #   83 c4 04              ADD ESP, 4
    #   c3                    RET
    if len(body) != 14:
        return None
    expected = [
        (0x68,), None, None, None, None,
        (0xe8,), None, None, None, None,
        (0x83,), (0xc4,), (0x04,),
        (0xc3,),
    ]
    if not all(exp is None or body[i] == exp[0] for i, exp in enumerate(expected)):
        return None
    src = (
        _header(va, "1-arg fixed-pointer call (PUSH offset; CALL; ADD ESP,4; RET)",
                "68 GG GG GG GG e8 RR RR RR RR 83 c4 04 c3", n)
        + "\nextern \"C\" int the_arg;\nextern \"C\" int target();\n\n"
          "extern \"C\" __declspec(naked) void push_str_call() {\n"
          "    __asm {\n"
          "        push offset the_arg\n"
          "        call target\n"
          "        add esp, 4\n"
          "        ret\n"
          "    }\n"
          "}\n"
    )
    return (src, "push-fixed-call 14B")


def try_push_arg_str_call_19b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 19B "load arg1; push fixed; push arg1; call; cleanup":
    #   8b 44 24 04           MOV EAX, [ESP+4]
    #   68 GG GG GG GG        PUSH offset arg1_fixed
    #   50                    PUSH EAX        (caller's arg1)
    #   e8 RR RR RR RR        CALL extern
    #   83 c4 08              ADD ESP, 8
    #   c3                    RET
    if len(body) != 19:
        return None
    expected = [
        (0x8b,), (0x44,), (0x24,), (0x04,),
        (0x68,), None, None, None, None,
        (0x50,),
        (0xe8,), None, None, None, None,
        (0x83,), (0xc4,), (0x08,),
        (0xc3,),
    ]
    if not all(exp is None or body[i] == exp[0] for i, exp in enumerate(expected)):
        return None
    src = (
        _header(va, "wrapper (PUSH fixed; PUSH arg1; CALL; ADD ESP,8; RET)",
                "8b 44 24 04 68 GG GG GG GG 50 e8 RR RR RR RR 83 c4 08 c3", n)
        + "\nextern \"C\" int the_fixed_arg;\nextern \"C\" int target();\n\n"
          "extern \"C\" __declspec(naked) void wrapper_2arg() {\n"
          "    __asm {\n"
          "        mov eax, [esp + 4]\n"
          "        push offset the_fixed_arg\n"
          "        push eax\n"
          "        call target\n"
          "        add esp, 8\n"
          "        ret\n"
          "    }\n"
          "}\n"
    )
    return (src, "wrapper PUSH-fixed+arg1+call 19B")


def try_no_reloc_emit_fallback(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    """Universal fallback for clusters with NO reloc bytes — just emit
    every byte via `_emit`. Only fires when no specific deriver above
    matched, so it's the catch-all for shapes with constant bytes
    (constant stores, register shuffles, fixed sequences).

    Constraint: the body must NOT contain any opcode that *would* require
    a reloc (CALL/JMP/PUSH-imm32/MOV-moff32/etc.). Those need actual
    inline-asm forms; pure _emit can't produce a reloc. We approximate
    "no relocs needed" by reusing the cluster_relocs reloc_mask logic —
    if the mask is all zeros, all the bytes are constants and we can
    safely emit them raw.

    Caps body length at 256 bytes — this is the long tail of large
    constant-byte clusters (SSE/FPU register-shuffle blocks, fixed
    string-encoder loops, etc.). Beyond 256B the per-byte _emit list
    starts to dominate the .cpp file size; specific derivers are
    preferable for those.

    Also requires cluster size ≥ 10. Tiny clusters (1-9 members) often
    expose Ghidra-under-count bugs — e.g. a function with an `eb 03`
    short JMP over a `8d 49 00` 3-byte NOP gets reported as 90 bytes
    when it's really 93. The asm dump captures the 90 visible bytes
    but compare.py reads the symbol's reported size from orig
    (truncating just before the trailing instructions), so the 3-byte
    NOP alignment difference shows up as a structural diff. Bigger
    clusters self-validate (many members agreeing on bytes).
    """
    if len(body) > 256 or n < 10:
        return None
    # Late import to avoid circular at module load.
    try:
        from cluster_relocs import reloc_mask_for_body  # type: ignore
    except ImportError:
        sys.path.insert(0, str(REPO_ROOT / "tools"))
        from cluster_relocs import reloc_mask_for_body  # type: ignore
    mask = reloc_mask_for_body(body)
    if any(mask):
        return None
    # Last sanity: function must end with RET (c2/c3) or a clean tail
    # (e.g. ff e2 register-indirect JMP), otherwise it likely has a
    # reloc-bearing terminator we missed.
    if body[-1] not in (0xc3, 0xc2) and body[-2:] not in (b"\xff\xe2", b"\xff\xe0", b"\xff\xe1", b"\xff\xe3"):
        return None
    emit_lines = "\n".join(f"        _emit 0x{b:02x}" for b in body)
    src = (
        _header(va, f"no-reloc cluster member ({len(body)}B raw _emit)",
                " ".join(f"{b:02x}" for b in body), n)
        + f"\nextern \"C\" __declspec(naked) void no_reloc_member() {{\n"
          f"    __asm {{\n"
          f"{emit_lines}\n"
          f"    }}\n"
          f"}}\n"
    )
    return (src, f"no-reloc emit {len(body)}B")


# Order matters: most specific first.
DERIVERS = [
    try_empty_void,
    try_empty_n_arg,
    try_return_zero_int,
    try_return_false_bool,
    try_return_true_bool,
    try_return_this,
    try_int_getter,
    try_short_zero_ext_getter,
    try_byte_zero_ext_getter,
    try_chained_ptr_getter,
    try_adjustor_thunk_sub_imm8,
    try_adjustor_thunk_sub_imm32,
    try_unwind_mov_ebp_jmp,
    try_unwind_lea_ebp_jmp,
    try_unwind_lea_ebp_disp32_jmp,
    try_unwind_mov_ebp_disp32_jmp,
    try_unwind_mov_ebp_add_jmp,
    try_unwind_mov_ebp_add32_jmp,
    try_clear_flag_in_global,
    try_push_load_call,
    try_return_global_addr,
    try_scalar_deleting_dtor_30b,
    try_scalar_deleting_dtor_32b,
    try_array_deleting_dtor_34b,
    try_unwind_flag_check_jmp_25b,
    try_catch_all_push_call_9b,
    try_arg_shuffler_41b,
    try_unwind_2arg_call_17b,
    try_vtbl_dispatch_25b,
    try_return_global_value_6b,
    try_store_arg_to_global_10b,
    try_import_thunk_jmp_m32,
    try_load_this_jmp_indirect_7b,
    try_push_local_call_pop_11b,
    # try_release_then_free_22b — disabled. Cluster matches the asm-dump
    # shape but the asm dump is wrong: Ghidra under-counts these
    # functions by 3 bytes (drops `83 c4 04` ADD ESP,4 between CALL
    # and POP ESI). Re-enable after recompute_sizes fixes the size.
    try_seh_catch_call_call_17b,
    try_push_str_then_call_14b,
    try_push_arg_str_call_19b,
    try_thiscall_return_self_wrapper,
    try_singleton_tail_call,
    try_jmp_thunk,
    try_no_reloc_emit_fallback,  # last-resort catch-all (no relocs only)
]


def try_adjustor_thunk_add_imm8(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8B `83 c1 NN e9 RR RR RR RR` — ADD ECX, imm8; JMP rel32.
    # Mirror of try_adjustor_thunk_sub_imm8 but with ADD (used for
    # interface-dispatch adjustors that move `this` FORWARD to a
    # secondary-base subobject).
    if len(body) == 8 and body[0:2] == b"\x83\xc1" and body[3] == 0xe9:
        offset = body[2]
        if offset == 0:
            return None
        src = (
            _header(va, f"adjustor thunk (ADD ECX, 0x{offset:x}; JMP)",
                    f"83 c1 {offset:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void adjustor_add() {\n"
              "    __asm {\n"
            + f"        add ecx, {offset}\n"
              "        jmp target\n"
              "    }\n"
              "}\n"
        )
        return (src, f"adjustor ADD imm8 {offset}")
    return None


def try_seh_catch_arg_call_9b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 9B SEH catch: load arg from local; push; CALL (no RET).
    #   8b 55 NN              MOV EDX, [EBP+disp8]
    #   52                    PUSH EDX
    #   e8 RR RR RR RR        CALL extern
    if len(body) == 9 and body[0:2] == b"\x8b\x55" and body[3] == 0x52 and body[4] == 0xe8:
        disp_u = body[2]
        disp_s = disp_u - 256 if disp_u >= 0x80 else disp_u
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"SEH catch arg-push (MOV EDX, [EBP{sign}0x{mag:x}]; PUSH EDX; CALL)",
                    f"8b 55 {disp_u:02x} 52 e8 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void seh_catch_arg() {\n"
              "    __asm {\n"
            + f"        mov edx, [ebp {sign} {mag}]\n"
              "        push edx\n"
              "        call target\n"
              "    }\n"
              "}\n"
        )
        return (src, f"seh-catch arg [EBP{sign}{mag}]+call")
    return None


def try_thiscall_via_member_jmp_8b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8B `8b 49 NN e9 RR RR RR RR` — MOV ECX, [ECX+disp8]; JMP rel32.
    # `__thiscall` adjustor that re-bases `this` to a member field at
    # offset NN, then tail-jumps to a method on that member. Common in
    # delegate-style "forward to member" wrappers (e.g. m_pImpl pattern).
    if len(body) == 8 and body[0:2] == b"\x8b\x49" and body[3] == 0xe9:
        disp = body[2]
        if disp == 0:
            # disp=0 should encode as `8b 09` (no disp byte) — different
            # 7-byte cluster. Bail to be safe.
            return None
        src = (
            _header(va, f"thiscall member-delegate (MOV ECX, [ECX+0x{disp:x}]; JMP)",
                    f"8b 49 {disp:02x} e9 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void thunk_thiscall_member() {\n"
              "    __asm {\n"
            + f"        mov ecx, [ecx + {disp}]\n"
              "        jmp target\n"
              "    }\n"
              "}\n"
        )
        return (src, f"thiscall-via-member [+0x{disp:x}]")
    return None


def try_seh_push_local_disp32_call_12b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 12B `8b 85 NN NN NN NN 50 e8 RR RR RR RR` — MOV EAX,[EBP+disp32];
    # PUSH EAX; CALL rel32. SEH unwind helper that pushes a frame-local
    # destructor-target pointer and tail-calls into a cleanup routine
    # (no RET — the unwinder handles return).
    #
    # The 6-byte MOV form is forced when displacement is outside the
    # disp8 signed range (-128..+127). Skip when it WOULD fit in disp8:
    # MSVC would emit the 9-byte `8b 45 NN 50 e8 RR RR RR RR` form
    # instead (already handled by try_push_load_call).
    if (len(body) == 12 and body[0:2] == b"\x8b\x85" and body[6] == 0x50
            and body[7] == 0xe8):
        disp_u = int.from_bytes(body[2:6], "little", signed=False)
        disp_s = int.from_bytes(body[2:6], "little", signed=True)
        if -128 <= disp_s <= 127:
            return None
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"SEH unwind helper (MOV EAX, [EBP{sign}0x{mag:x}]; PUSH EAX; CALL — disp32)",
                    f"8b 85 NN NN NN NN 50 e8 RR RR RR RR  (disp={sign}0x{mag:x})", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void seh_push_local_disp32() {\n"
              "    __asm {\n"
            + f"        mov eax, [ebp {sign} {mag}]\n"
              "        push eax\n"
              "        call target\n"
              "    }\n"
              "}\n"
        )
        return (src, f"seh-push-local disp32 [EBP{sign}0x{mag:x}]")
    return None


def try_global_ptr_getter_ret4_8b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 8B `a1 GG GG GG GG c2 04 00` — MOV EAX, [global]; RET 4.
    # __thiscall getter that ignores `this` (passed in ECX) and returns
    # a global. The RET 4 pops a stale stack arg — likely the original
    # source signature was `T C::get(int) const` returning a global.
    if (len(body) == 8 and body[0] == 0xa1
            and body[5:8] == b"\xc2\x04\x00"):
        # Address bytes 1..5 are absolute and would be a relocation in
        # the cluster_relocs view. Cluster identity is on the rest.
        src = (
            _header(va, "global pointer getter (RET 4)",
                    "a1 GG GG GG GG c2 04 00", n)
            + "\nextern \"C\" int the_global;\n\n"
              "extern \"C\" __declspec(naked) void global_getter_ret4() {\n"
              "    __asm {\n"
              "        mov eax, dword ptr [the_global]\n"
              "        ret 4\n"
              "    }\n"
              "}\n"
        )
        return (src, "global getter (ret 4)")
    return None


def try_clear_global_dword_zero_11b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 11B `c7 05 GG GG GG GG 00 00 00 00 c3` — MOV [global], 0; RET.
    # Plain dword-write-to-zero setter (no read-modify-write — distinct
    # from try_clear_flag_in_global which AND-masks bits).
    if (len(body) == 11 and body[0:2] == b"\xc7\x05"
            and body[6:11] == b"\x00\x00\x00\x00\xc3"):
        src = (
            _header(va, "clear global dword (MOV [global], 0; RET)",
                    "c7 05 GG GG GG GG 00 00 00 00 c3", n)
            + "\nextern \"C\" int the_global;\n\n"
              "extern \"C\" __declspec(naked) void clear_global_dword() {\n"
              "    __asm {\n"
              "        mov dword ptr [the_global], 0\n"
              "        ret\n"
              "    }\n"
              "}\n"
        )
        return (src, "clear global dword")
    return None


def try_push_ebp_arg1_call_pop_ret_10b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 10B `ff 75 08 e8 RR RR RR RR 59 c3` —
    #   PUSH [EBP+8]; CALL rel32; POP ECX; RET.
    # Single-arg cdecl wrapper: forwards arg1 from the EBP-frame to a
    # cdecl callee, pops the pushed arg via POP ECX, and returns.
    if (len(body) == 10 and body[0:3] == b"\xff\x75\x08"
            and body[3] == 0xe8 and body[8:10] == b"\x59\xc3"):
        src = (
            _header(va, "single-arg cdecl wrapper (PUSH [EBP+8]; CALL; POP ECX; RET)",
                    "ff 75 08 e8 RR RR RR RR 59 c3", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void wrapper_1arg_ebp() {\n"
              "    __asm {\n"
              "        push [ebp + 8]\n"
              "        call target\n"
              "        pop ecx\n"
              "        ret\n"
              "    }\n"
              "}\n"
        )
        return (src, "1arg-wrapper [EBP+8]+pop-ret")
    return None


def try_push_esp_arg1_call_pop_ret4_14b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 14B `8b 44 24 04 50 e8 RR RR RR RR 59 c2 04 00` —
    #   MOV EAX, [ESP+4]; PUSH EAX; CALL rel32; POP ECX; RET 4.
    # __stdcall single-arg wrapper that forwards its arg to a cdecl
    # callee, pops the pushed arg, and returns 4 (per __stdcall).
    if (len(body) == 14 and body[0:4] == b"\x8b\x44\x24\x04"
            and body[4] == 0x50 and body[5] == 0xe8
            and body[10:14] == b"\x59\xc2\x04\x00"):
        src = (
            _header(va, "stdcall→cdecl 1-arg wrapper (MOV EAX,[ESP+4]; PUSH; CALL; POP ECX; RET 4)",
                    "8b 44 24 04 50 e8 RR RR RR RR 59 c2 04 00", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void __stdcall wrapper_stdcall_to_cdecl_1arg(int) {\n"
              "    __asm {\n"
              "        mov eax, [esp + 4]\n"
              "        push eax\n"
              "        call target\n"
              "        pop ecx\n"
              "        ret 4\n"
              "    }\n"
              "}\n"
        )
        return (src, "stdcall→cdecl 1arg wrapper")
    return None


def try_global_eq_arg_setcc_15b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 15B `a1 GG GG GG GG 3b 44 24 04 0f 94 c0 c2 04 00` —
    #   MOV EAX, [global]; CMP EAX, [ESP+4]; SETE AL; RET 4.
    # __stdcall predicate that compares a global pointer to an arg.
    # Returns AL = (the_global == arg). Note: high 24 bits of EAX
    # are NOT cleared (would need MOVZX before SETE), but the source
    # pattern in the binary doesn't clear them either — typical MSVC
    # 2005 output for `bool C::is_the_global(void *p)`.
    if (len(body) == 15 and body[0] == 0xa1
            and body[5:9] == b"\x3b\x44\x24\x04"
            and body[9:12] == b"\x0f\x94\xc0"
            and body[12:15] == b"\xc2\x04\x00"):
        src = (
            _header(va, "global == arg predicate (MOV EAX,[global]; CMP EAX,[ESP+4]; SETE AL; RET 4)",
                    "a1 GG GG GG GG 3b 44 24 04 0f 94 c0 c2 04 00", n)
            + "\nextern \"C\" void *the_global;\n\n"
              "extern \"C\" unsigned char __stdcall is_global(void *p);\n"
              "extern \"C\" __declspec(naked) unsigned char __stdcall is_global(void *p) {\n"
              "    __asm {\n"
              "        mov eax, dword ptr [the_global]\n"
              "        cmp eax, [esp + 4]\n"
              "        sete al\n"
              "        ret 4\n"
              "    }\n"
              "}\n"
        )
        return (src, "global==arg SETE pred")
    return None


def try_thiscall_vtable_slot_disp32_call_17b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 17B `8b 4c 24 04 8b 01 8b 90 NN NN NN NN ff d2 c2 04 00` —
    #   MOV ECX, [ESP+4]    (load arg = pointer)
    #   MOV EAX, [ECX]      (load arg's vtable)
    #   MOV EDX, [EAX+disp32] (load vtable slot)
    #   CALL EDX
    #   RET 4
    # Wrapper that forwards a single arg into a virtual call on it,
    # via a vtable slot with disp32 (so slot ≥ 0x80/4 = slot 32+).
    if (len(body) == 17 and body[0:4] == b"\x8b\x4c\x24\x04"
            and body[4:6] == b"\x8b\x01"
            and body[6:8] == b"\x8b\x90"
            and body[12:14] == b"\xff\xd2"
            and body[14:17] == b"\xc2\x04\x00"):
        slot_off = int.from_bytes(body[8:12], "little", signed=False)
        # MSVC will only emit the disp32 form when offset is > 127. If
        # we tried with offset ≤ 127 it would emit the disp8 form (3
        # bytes shorter). Bail to avoid mismatched encoding.
        if slot_off <= 0x7f:
            return None
        src = (
            _header(va, f"vtable-slot tail-call wrapper (slot disp32 = 0x{slot_off:x})",
                    "8b 4c 24 04 8b 01 8b 90 NN NN NN NN ff d2 c2 04 00", n)
            + "\nextern \"C\" __declspec(naked) void vtbl_slot_disp32_wrapper(void *) {\n"
              "    __asm {\n"
              "        mov ecx, [esp + 4]\n"
              "        mov eax, [ecx]\n"
            + f"        mov edx, [eax + 0x{slot_off:x}]\n"
              "        call edx\n"
              "        ret 4\n"
              "    }\n"
              "}\n"
        )
        return (src, f"vtbl-slot-disp32 call [+0x{slot_off:x}]")
    return None


def try_thiscall_advance_push_call_pop_ret_11b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 11B `83 c1 NN 51 e8 RR RR RR RR 59 c3` —
    #   ADD ECX, disp8; PUSH ECX; CALL rel32; POP ECX; RET
    # Wrapper that re-bases `this` to `this+disp8` and passes that as
    # the first cdecl arg. POP ECX cleans the pushed arg (1-arg cdecl).
    if (len(body) == 11 and body[0:2] == b"\x83\xc1"
            and body[3] == 0x51 and body[4] == 0xe8
            and body[9:11] == b"\x59\xc3"):
        disp = body[2]
        if disp == 0:
            return None
        src = (
            _header(va, f"thiscall→cdecl (this + 0x{disp:x}) wrapper (ADD ECX,N; PUSH; CALL; POP; RET)",
                    f"83 c1 {disp:02x} 51 e8 RR RR RR RR 59 c3", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void thiscall_advance_call() {\n"
              "    __asm {\n"
            + f"        add ecx, {disp}\n"
              "        push ecx\n"
              "        call target\n"
              "        pop ecx\n"
              "        ret\n"
              "    }\n"
              "}\n"
        )
        return (src, f"thiscall-advance+call+pop-ret [+0x{disp:x}]")
    return None


def try_thiscall_set_field0_ret_self_11b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 11B `8b c1 8b 4c 24 04 89 08 c2 04 00` —
    #   MOV EAX, ECX        (return *this in EAX — copy preserved across
    #                        the field load below since we use [ESP+4])
    #   MOV ECX, [ESP+4]    (load arg)
    #   MOV [EAX], ECX      (store at this+0)
    #   RET 4
    # `__thiscall` setter that writes its arg to `*this` (offset 0) and
    # returns `this`. Common in fluent-builder / pImpl assignment paths.
    if body == bytes.fromhex("8bc1 8b4c2404 8908 c20400".replace(" ", "")):
        src = (
            _header(va, "thiscall set-field0 returning *this",
                    "8b c1 8b 4c 24 04 89 08 c2 04 00", n)
            + "\nclass C { public: C *set_field0(void *p); };\n\n"
              "C *C::set_field0(void *p) {\n"
              "    *(void **)this = p;\n"
              "    return this;\n"
              "}\n"
        )
        return (src, "thiscall set-field0 ret-self")
    return None


def try_unwind_2arg_field_local_call_20b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 20B `8b 45 AA 8b 48 BB 51 8b 55 CC 52 e8 RR RR RR RR 83 c4 08 c3`
    #   MOV EAX, [EBP+arg1_disp8]      (load arg-on-frame)
    #   MOV ECX, [EAX+field_disp8]     (deref to struct field)
    #   PUSH ECX
    #   MOV EDX, [EBP+local_disp8]     (load second arg from frame)
    #   PUSH EDX
    #   CALL rel32
    #   ADD ESP, 8
    #   RET
    # Two-arg cdecl wrapper that loads one arg from a struct field
    # (one indirection through an EBP-local pointer), the other
    # directly from the EBP frame.
    if not (len(body) == 20
            and body[0:2] == b"\x8b\x45"
            and body[3:5] == b"\x8b\x48"
            and body[6] == 0x51
            and body[7:9] == b"\x8b\x55"
            and body[10] == 0x52
            and body[11] == 0xe8
            and body[16:20] == b"\x83\xc4\x08\xc3"):
        return None
    arg1_u = body[2]
    field_u = body[5]
    local_u = body[9]
    arg1_s = arg1_u - 256 if arg1_u >= 0x80 else arg1_u
    field_s = field_u - 256 if field_u >= 0x80 else field_u
    local_s = local_u - 256 if local_u >= 0x80 else local_u
    a1_sign, a1_mag = ("-" if arg1_s < 0 else "+", abs(arg1_s))
    fl_sign, fl_mag = ("-" if field_s < 0 else "+", abs(field_s))
    lc_sign, lc_mag = ("-" if local_s < 0 else "+", abs(local_s))
    src = (
        _header(va, f"2-arg call: deref [EBP{a1_sign}0x{a1_mag:x}]+0x{fl_mag:x} + [EBP{lc_sign}0x{lc_mag:x}]",
                f"8b 45 {arg1_u:02x} 8b 48 {field_u:02x} 51 8b 55 {local_u:02x} 52 e8 RR RR RR RR 83 c4 08 c3", n)
        + "\nextern \"C\" int target();\n\n"
          "extern \"C\" __declspec(naked) void wrapper_2arg_field_local() {\n"
          "    __asm {\n"
        + f"        mov eax, [ebp {a1_sign} {a1_mag}]\n"
          f"        mov ecx, [eax {fl_sign} {fl_mag}]\n"
          "        push ecx\n"
        + f"        mov edx, [ebp {lc_sign} {lc_mag}]\n"
          "        push edx\n"
          "        call target\n"
          "        add esp, 8\n"
          "        ret\n"
          "    }\n"
          "}\n"
    )
    return (src, f"2arg field+local call [EBP{a1_sign}0x{a1_mag:x}+0x{fl_mag:x}, EBP{lc_sign}0x{lc_mag:x}]")


def try_seh_push_ecx_local_call_9b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 9B `8b 4d NN 51 e8 RR RR RR RR` —
    #   MOV ECX, [EBP+disp8]; PUSH ECX; CALL rel32 (no RET — unwinder
    #   handles return). Sister of try_push_load_call (which uses
    #   PUSH EAX); this variant pushes ECX after loading it.
    if (len(body) == 9 and body[0:2] == b"\x8b\x4d"
            and body[3] == 0x51 and body[4] == 0xe8):
        disp_u = body[2]
        disp_s = disp_u - 256 if disp_u >= 0x80 else disp_u
        sign = "-" if disp_s < 0 else "+"
        mag = abs(disp_s)
        src = (
            _header(va, f"unwind helper (MOV ECX, [EBP{sign}0x{mag:x}]; PUSH ECX; CALL)",
                    f"8b 4d {disp_u:02x} 51 e8 RR RR RR RR", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void seh_push_ecx_local() {\n"
              "    __asm {\n"
            + f"        mov ecx, [ebp {sign} {mag}]\n"
              "        push ecx\n"
              "        call target\n"
              "    }\n"
              "}\n"
        )
        return (src, f"seh-push-ecx [EBP{sign}{mag}]")
    return None


def try_push_imm_call_addret_14b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 14B `68 II II II II e8 RR RR RR RR 83 c0 NN c3` —
    #   PUSH imm32           (push a constant — typically a string or
    #                         global pointer; the imm32 IS a relocation
    #                         in cluster-reloc view)
    #   CALL rel32
    #   ADD EAX, imm8
    #   RET
    # Common "call X then offset the returned pointer" pattern, e.g.
    # when X returns a struct and the wrapper exposes a pointer to a
    # specific field.
    if (len(body) == 14 and body[0] == 0x68 and body[5] == 0xe8
            and body[10:12] == b"\x83\xc0" and body[13] == 0xc3):
        adj = body[12]
        if adj == 0:
            return None
        src = (
            _header(va, f"push-imm32 + call + ADD EAX,0x{adj:x} + ret",
                    f"68 II II II II e8 RR RR RR RR 83 c0 {adj:02x} c3", n)
            + "\nextern \"C\" int target(int);\n"
              "extern \"C\" int the_imm;\n\n"
              "extern \"C\" __declspec(naked) void wrapper_push_call_addret() {\n"
              "    __asm {\n"
              "        push offset the_imm\n"
              "        call target\n"
            + f"        add eax, {adj}\n"
              "        ret\n"
              "    }\n"
              "}\n"
        )
        return (src, f"push-imm32+call+add 0x{adj:x}+ret")
    return None


def try_2arg_passthrough_wrapper_21b(body: bytes, va: int, n: int) -> tuple[str, str] | None:
    # 21B `__stdcall` 2-arg passthrough wrapper:
    #   8b 44 24 08              MOV EAX, [ESP+8]    (arg2)
    #   8b 4c 24 04              MOV ECX, [ESP+4]    (arg1)
    #   50                       PUSH EAX
    #   51                       PUSH ECX
    #   e8 RR RR RR RR           CALL extern
    #   83 c4 08                 ADD ESP, 8
    #   c2 08 00                 RET 8
    expected = bytes.fromhex(
        "8b442408 8b4c2404 5051 e8".replace(" ", "")
    )
    suffix = bytes.fromhex("83c408 c20800")
    if (len(body) == 21 and body[:len(expected)] == expected
            and body[15:] == suffix):
        src = (
            _header(va, "2-arg passthrough wrapper (PUSH arg2; PUSH arg1; CALL; ADD ESP,8; RET 8)",
                    "8b 44 24 08 8b 4c 24 04 50 51 e8 RR RR RR RR 83 c4 08 c2 08 00", n)
            + "\nextern \"C\" int target();\n\n"
              "extern \"C\" __declspec(naked) void wrapper_2arg_passthrough() {\n"
              "    __asm {\n"
              "        mov eax, [esp + 8]\n"
              "        mov ecx, [esp + 4]\n"
              "        push eax\n"
              "        push ecx\n"
              "        call target\n"
              "        add esp, 8\n"
              "        ret 8\n"
              "    }\n"
              "}\n"
        )
        return (src, "2arg-passthrough 21B")
    return None


# Splice the late-defined derivers into DERIVERS in front of the
# no-reloc fallback, so the more-specific patterns try first.
_late_idx = DERIVERS.index(try_no_reloc_emit_fallback)
DERIVERS[_late_idx:_late_idx] = [
    try_adjustor_thunk_add_imm8,
    try_seh_catch_arg_call_9b,
    try_2arg_passthrough_wrapper_21b,
    try_thiscall_via_member_jmp_8b,
    try_seh_push_local_disp32_call_12b,
    try_global_ptr_getter_ret4_8b,
    try_clear_global_dword_zero_11b,
    try_push_ebp_arg1_call_pop_ret_10b,
    try_push_esp_arg1_call_pop_ret4_14b,
    try_global_eq_arg_setcc_15b,
    try_thiscall_vtable_slot_disp32_call_17b,
    try_thiscall_advance_push_call_pop_ret_11b,
    try_thiscall_set_field0_ret_self_11b,
    try_unwind_2arg_field_local_call_20b,
    try_seh_push_ecx_local_call_9b,
    try_push_imm_call_addret_14b,
]


def derive_one(body: bytes, va: int, n_members: int) -> tuple[str, str] | None:
    for fn in DERIVERS:
        result = fn(body, va, n_members)
        if result is not None:
            return result
    return None


def process_binary(stem: str, dry_run: bool, image_base: int = 0x400000) -> dict:
    rosetta_dir = SRC_DIR / stem / "_rosetta"
    rosetta_dir.mkdir(parents=True, exist_ok=True)
    asm_dir = ASM_ROOT / stem

    # Read both clusters JSONs (exact-byte + reloc-aware), unioning members.
    clusters_paths = [
        EASY_WINS / f"{stem}.clusters.json",
        EASY_WINS / f"{stem}.clusters_reloc.json",
    ]
    seen_rva: set[int] = set()
    n_recognised = 0
    n_skipped_unrecognised = 0
    n_skipped_existing = 0
    by_idiom: dict[str, int] = {}

    for p in clusters_paths:
        if not p.exists():
            continue
        clusters = json.loads(p.read_text())
        for h, members in clusters.items():
            # Pick the smallest-RVA member as primary, deterministic per cluster.
            rep = min(members, key=lambda m: m["rva"])
            if rep["rva"] in seen_rva:
                continue
            seen_rva.add(rep["rva"])
            asm_path = asm_dir / rep["asm"]
            body = read_function_bytes(asm_path)
            if body is None:
                continue
            va = rep["rva"] + image_base
            target_path = rosetta_dir / f"FUN_{va:08x}.cpp"
            if target_path.exists():
                n_skipped_existing += 1
                continue
            result = derive_one(body, va, len(members))
            if result is None:
                n_skipped_unrecognised += 1
                continue
            src, idiom = result
            if not dry_run:
                target_path.write_text(src)
            n_recognised += 1
            by_idiom[idiom] = by_idiom.get(idiom, 0) + 1
    return {
        "binary": stem,
        "recognised": n_recognised,
        "skipped_existing": n_skipped_existing,
        "skipped_unrecognised": n_skipped_unrecognised,
        "by_idiom": by_idiom,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("binary", default="ffxivgame", nargs="?")
    ap.add_argument("--all", action="store_true", help="run on all 5 binaries")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    if args.all:
        targets = list(KNOWN_BINARIES)
    else:
        targets = [args.binary.replace(".exe", "")]

    grand_recognised = 0
    grand_idioms: dict[str, int] = {}
    for t in targets:
        report = process_binary(t, dry_run=args.dry_run)
        print(f"=== {t} ===")
        print(f"  recognised:           {report['recognised']:>5}{' (dry-run)' if args.dry_run else ''}")
        print(f"  skipped (existing):   {report['skipped_existing']:>5}")
        print(f"  skipped (unmatched):  {report['skipped_unrecognised']:>5}")
        if report["by_idiom"]:
            print(f"  by idiom:")
            for idiom, n in sorted(report["by_idiom"].items(), key=lambda kv: -kv[1]):
                print(f"    {idiom:<35}  {n}")
                grand_idioms[idiom] = grand_idioms.get(idiom, 0) + n
        grand_recognised += report["recognised"]

    if len(targets) > 1:
        print(f"\nGrand total recognised: {grand_recognised}{' (dry-run)' if args.dry_run else ''}")
        print(f"Top idioms across all binaries:")
        for idiom, n in sorted(grand_idioms.items(), key=lambda kv: -kv[1])[:15]:
            print(f"  {idiom:<35}  {n}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
