#!/usr/bin/env python3
# meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
# Copyright (C) 2026  Samuel Stegall
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Emit ONE giant naked-asm function whose body is `_emit` of every byte
in orig's `.text` section. Compiled to a single .obj, this lands the
entire `.text` content as a single CODE section (CNT_CODE / EXECUTE /
READ) — matching orig's section attributes byte-for-byte.

Why a separate tool from `emit_data_sections.py --include-text`:
that tool emits `.text` as `__declspec(allocate(".text")) const unsigned
char[]` which gets CNT_INITIALIZED_DATA characteristics (0x40), forcing
link.exe to create a second `.text` section. By using a NAKED
FUNCTION, we get CNT_CODE characteristics (0x20) which matches orig
exactly.

Trade-off: the entire .text is one opaque function blob. We can't
substitute individual functions with rosetta sources. For the first
working byte-identical link, that's fine; granularity comes later
once the link path is closed.

Reads:
  build/pe-layout/<binary>.json
  orig/<binary>.exe

Writes:
  src/<binary>/_passthrough/_section_text_blob.cpp

Usage:
  tools/emit_text_blob.py ffxivlogin
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
PE_LAYOUT = REPO_ROOT / "build" / "pe-layout"
ORIG = REPO_ROOT / "orig"
SRC = REPO_ROOT / "src"

LICENSE_HEADER = """\
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
"""


def emit(binary: str, dry_run: bool = False) -> dict:
    pe_path = PE_LAYOUT / f"{binary}.json"
    orig_path = ORIG / f"{binary}.exe"
    pe = json.loads(pe_path.read_text())
    text_sec = next(s for s in pe["sections"] if s["name"] == ".text")
    orig_bytes = orig_path.read_bytes()
    body = orig_bytes[text_sec["raw_pointer"]:text_sec["raw_pointer"] + text_sec["raw_size"]]

    out_dir = SRC / binary / "_passthrough"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "_section_text_blob.cpp"

    lines = [LICENSE_HEADER, ""]
    lines.append(f"// AUTO-GENERATED by tools/emit_text_blob.py — do not edit.")
    lines.append(f"// {binary}.exe `.text` section as one naked-asm function blob.")
    lines.append(f"//   raw_size: {len(body):,} bytes")
    lines.append(f"//   vaddr:    0x{text_sec['virtual_address']:08x}")
    lines.append("//")
    lines.append("// One giant function = one .obj section = no obj-file-boundary")
    lines.append("// alignment padding when link.exe lays it down. CNT_CODE +")
    lines.append("// MEM_EXECUTE + MEM_READ section characteristics match orig's")
    lines.append("// `.text` exactly.")
    lines.append("")
    lines.append('#pragma code_seg(".text$X00000000")')
    lines.append('#pragma comment(linker, "/INCLUDE:__text_blob")')
    lines.append('extern "C" __declspec(naked) void _text_blob() {')
    lines.append('    __asm {')
    for i, b in enumerate(body):
        if i and i % 16 == 0:
            lines.append("")
        lines.append(f'        _emit 0x{b:02x}')
    lines.append('    }')
    lines.append('}')
    lines.append('#pragma code_seg()')
    lines.append('')
    src = "\n".join(lines)
    if not dry_run:
        out_path.write_text(src)
    return {"binary": binary, "bytes": len(body), "out": str(out_path.relative_to(REPO_ROOT))}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("binary", help="binary stem")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()
    res = emit(args.binary, args.dry_run)
    print(f"=== emit_text_blob ===")
    for k, v in res.items():
        print(f"  {k}: {v}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
