#!/usr/bin/env python3
# meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
# Copyright (C) 2026  Samuel Stegall
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Extract a focused map of every net-relevant vtable in the binary,
listing each slot's function RVA + the asm/ filename. Output is a
markdown report that a contributor (or an agent) can pick up and
use to drive function-by-function decomp of the wire layer.

Reads:
  config/<binary>.rtti.json
  config/<binary>.vtable_slots.jsonl
  config/<binary>.symbols.json (for asm/ filename lookup)

Writes:
  build/wire/<binary>.net_handlers.md   markdown report
  build/wire/<binary>.net_handlers.json structured form

Selection: classes whose name contains any of these tokens
(case-insensitive):
  Network, Packet, Channel, Connection, Cipher, Crypt, Blowfish,
  Socket, RUDP, Lobby, Login, Auth, Sqex::Http, Sqex::Login,
  PollerImpl, ConsumerConnection, Service, Recv, Send, IpcChannel,
  IpcEntity, NetBuffer, GameAttribute

This is exactly the work-pool for Phase 3 (net layer): every entry
in the report is a candidate function that, decompiled, advances
the wire-protocol understanding.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG = REPO_ROOT / "config"
ASM_ROOT = REPO_ROOT / "asm"
OUT = REPO_ROOT / "build" / "wire"

NET_PATTERNS = re.compile(
    r"(Network|Packet|Channel|Connection|Cipher|Crypt|Blowfish|"
    r"Socket|RUDP|Lobby|Login|Auth|Http|PollerImpl|"
    r"ConsumerConnection|Service|Recv|Send|IpcChannel|IpcEntity|"
    r"NetBuffer|GameAttribute|MyGame)",
    re.IGNORECASE,
)

# Anti-patterns: things named "Connection" but not actually network.
ANTI_PATTERNS = re.compile(
    r"(SqwtInterface|TimerCallback|"  # UI controls named Connection*
    r"CDev::Engine::Cut)",  # cinematic scheduler
    re.IGNORECASE,
)


def short_class_name(cls: str) -> str:
    """For grouping: drop template params and the leading namespace
    fluff to get a stable bucket key."""
    cls = re.sub(r"<[^>]*>", "<...>", cls)
    return cls


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("binary", help="binary stem, e.g. ffxivgame")
    args = ap.parse_args()
    stem = args.binary.replace(".exe", "")

    rtti_path = CONFIG / f"{stem}.rtti.json"
    slots_path = CONFIG / f"{stem}.vtable_slots.jsonl"
    sym_path = CONFIG / f"{stem}.symbols.json"
    asm_dir = ASM_ROOT / stem
    if not all(p.exists() for p in (rtti_path, slots_path, sym_path)):
        print(f"error: missing dumps for {stem}; run import_to_ghidra.py first", file=sys.stderr)
        return 1

    rtti = json.loads(rtti_path.read_text())
    syms = {fn["rva"]: fn for fn in json.loads(sym_path.read_text())}

    # Build asm/ filename index by RVA prefix.
    asm_by_rva: dict[int, str] = {}
    if asm_dir.exists():
        for p in asm_dir.iterdir():
            if p.name.endswith(".s"):
                try:
                    asm_by_rva[int(p.name[:8], 16)] = p.name
                except ValueError:
                    pass

    # Net-relevant classes from RTTI.
    selected = [
        r for r in rtti
        if NET_PATTERNS.search(r["class"]) and not ANTI_PATTERNS.search(r["class"])
    ]
    print(f"selected {len(selected)} net-relevant classes (of {len(rtti)} total)")

    # Build per-class slot list from vtable_slots.jsonl.
    by_class: dict[str, list[dict]] = defaultdict(list)
    selected_names = {r["class"] for r in selected}
    for line in slots_path.read_text().splitlines():
        if not line.strip():
            continue
        e = json.loads(line)
        if e["class"] in selected_names:
            by_class[e["class"]].append(e)

    OUT.mkdir(parents=True, exist_ok=True)
    out_md = OUT / f"{stem}.net_handlers.md"
    out_json = OUT / f"{stem}.net_handlers.json"

    structured: list[dict] = []
    with out_md.open("w") as f:
        f.write(f"# {stem}.exe — net-relevant vtables\n\n")
        f.write("Auto-generated by `tools/extract_net_vtables.py`. Each section is\n")
        f.write("one RTTI vtable; each row is a slot in that vtable.\n\n")
        f.write("| col | meaning |\n")
        f.write("|---|---|\n")
        f.write("| `slot` | vtable slot index (matches MSVC layout) |\n")
        f.write("| `fn_rva` | function entry-point RVA |\n")
        f.write("| `fn_name` | Ghidra-named function |\n")
        f.write("| `asm` | per-function disassembly under `asm/<binary>/` |\n")
        f.write(f"\nClasses are grouped by the leading namespace prefix.\n\n")

        # Group by leading namespace (top 3 path segments).
        groups: dict[str, list[str]] = defaultdict(list)
        for cls in selected_names:
            parts = cls.split("::")
            key = "::".join(parts[:3]) if len(parts) >= 3 else "::".join(parts)
            groups[key].append(cls)

        for ns_key in sorted(groups):
            f.write(f"## `{ns_key}`\n\n")
            for cls in sorted(groups[ns_key]):
                slots = by_class.get(cls, [])
                if not slots:
                    f.write(f"### `{short_class_name(cls)}`\n\n")
                    f.write(f"_(no vtable slots recovered — class has only constructors / destructors / abstract slots)_\n\n")
                    continue
                f.write(f"### `{short_class_name(cls)}` — {len(slots)} slots\n\n")
                f.write("| slot | fn_rva | fn_name | asm |\n")
                f.write("|---:|:---|:---|:---|\n")
                slots.sort(key=lambda s: s["slot"])
                for s in slots:
                    rva = s["fn_rva"]
                    asm = asm_by_rva.get(rva, "—")
                    asm_link = f"[`{asm}`](../../asm/{stem}/{asm})" if asm != "—" else "—"
                    f.write(f"| {s['slot']} | `0x{rva:08x}` | `{s['fn_name']}` | {asm_link} |\n")
                    structured.append({
                        "class": cls,
                        "slot": s["slot"],
                        "fn_rva": rva,
                        "fn_name": s["fn_name"],
                        "asm": asm if asm != "—" else None,
                    })
                f.write("\n")

    out_json.write_text(json.dumps(structured, indent=2))
    print(f"wrote: {out_md.relative_to(REPO_ROOT)}")
    print(f"wrote: {out_json.relative_to(REPO_ROOT)}  ({len(structured)} slot entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
