#!/usr/bin/env python3
# meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
# Copyright (C) 2026  Samuel Stegall
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Compute project progress from `config/<binary>.yaml` work pool files.

Reports:
  - per-binary  : matched / functional / wip / unmatched / middleware
  - per-module  : same breakdown, sorted descending by total size
  - overall     : matched-byte percentage, contributor-claimed count

Until Phase 1 generates the YAML files, this script reports zero.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from functools import lru_cache
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_DIR = REPO_ROOT / "config"
SRC_DIR = REPO_ROOT / "src"

IMAGE_BASE = 0x400000

ALL_BINARIES = ("ffxivboot", "ffxivconfig", "ffxivgame", "ffxivlogin", "ffxivupdater")

STATUSES = ("matched", "functional", "passthrough", "wip", "unmatched")
MIDDLEWARE = ("middleware-crt", "middleware-miles", "middleware-dx9", "middleware-stl")

RE_FUN_NAME = re.compile(r"^FUN_([0-9a-fA-F]+)\.cpp$")


def try_yaml():
    try:
        import yaml  # type: ignore
        return yaml
    except ImportError:
        return None


@lru_cache(maxsize=None)
def _rva_to_size(binary_stem: str) -> dict[int, int]:
    """rva → effective size for a binary, from the committed sizes manifest.

    Sources, in priority order:
      1. `config/<bin>.func_sizes.json` — the COMMITTED, toolchain-free
         per-function size manifest (override already applied), keyed by
         decimal-rva strings. This is the source that works in a clean
         CI checkout where no `symbols.json` is present.
      2. `config/<bin>.symbols.json` — the gitignored Ghidra dump, used
         only as a fallback when the frozen manifest is absent. Sizes
         here are raw (no override correction).

    Returns an empty dict when neither source exists.
    """
    sizes_path = CONFIG_DIR / f"{binary_stem}.func_sizes.json"
    if sizes_path.exists():
        manifest = json.loads(sizes_path.read_text())
        return {int(k): int(v) for k, v in manifest.items()}

    sym_path = CONFIG_DIR / f"{binary_stem}.symbols.json"
    if sym_path.exists():
        syms = json.loads(sym_path.read_text())
        return {int(s["rva"]): int(s.get("size", 0)) for s in syms}

    return {}


def _total_bytes(binary_stem: str) -> int:
    """Sum of every function's effective size for a binary (0 if no manifest)."""
    return sum(_rva_to_size(binary_stem).values())


def _rosetta_overlay(binary_stem: str, image_base: int = IMAGE_BASE) -> tuple[int, int]:
    """Count `_rosetta/*.cpp` files for a binary as additional matches.

    The YAML is regenerated by `build_split_yaml.py` and resets all
    statuses to `unmatched`/`middleware-*`, so per-function status
    edits in the YAML don't survive a re-split. The durable artifact
    is the .cpp file under `src/<binary>/_rosetta/` — its presence
    plus `make rosetta` GREEN is the real "matched" signal.

    Returns (count, total_size_bytes) by parsing FUN_<va>.cpp filenames
    and looking up sizes in the committed `config/<binary>.func_sizes.json`
    (falling back to the gitignored `symbols.json` only if absent).

    The COUNT is the committed `_rosetta` tree — every well-formed
    `FUN_<va>.cpp` is a durable solved signal and counts, independent of
    whether its size is currently resolvable. (A handful of solved RVAs
    predate the latest `symbols.json` regeneration and aren't in the
    sizes manifest; they still count as solved.) Only the BYTE total
    depends on the sizes manifest — an unknown size contributes 0 bytes
    but never drops the file from the count.
    """
    rosetta_dir = SRC_DIR / binary_stem / "_rosetta"
    if not rosetta_dir.is_dir():
        return (0, 0)
    rva_to_size = _rva_to_size(binary_stem)

    count = 0
    total_size = 0
    for cpp in rosetta_dir.glob("FUN_*.cpp"):
        m = RE_FUN_NAME.match(cpp.name)
        if not m:
            continue
        va = int(m.group(1), 16)
        rva = va - image_base
        count += 1
        total_size += rva_to_size.get(rva, 0)
    return (count, total_size)


def _binary_stems() -> list[str]:
    """The binaries to report on: every stem with a _rosetta tree or a
    committed sizes manifest (so `--json` works even with no *.yaml)."""
    stems: set[str] = set()
    for cfg in CONFIG_DIR.glob("*.func_sizes.json"):
        stems.add(cfg.name[: -len(".func_sizes.json")])
    for cfg in CONFIG_DIR.glob("*.yaml"):
        stems.add(cfg.stem)
    if SRC_DIR.is_dir():
        for child in SRC_DIR.iterdir():
            if (child / "_rosetta").is_dir():
                stems.add(child.name)
    # Keep deterministic order; prefer the canonical roster ordering.
    ordered = [b for b in ALL_BINARIES if b in stems]
    ordered += sorted(s for s in stems if s not in ALL_BINARIES)
    return ordered


def collect_json() -> dict:
    """Stable machine-readable progress schema driven by the durable
    `_rosetta/*.cpp` overlay + the committed func_sizes.json manifest."""
    per_binary: dict[str, dict] = {}
    tot_count = tot_rbytes = tot_tbytes = 0
    for stem in _binary_stems():
        rcount, rbytes = _rosetta_overlay(stem)
        tbytes = _total_bytes(stem)
        per_binary[stem] = {
            "rosetta_count": rcount,
            "rosetta_bytes": rbytes,
            "total_bytes": tbytes,
        }
        tot_count += rcount
        tot_rbytes += rbytes
        tot_tbytes += tbytes
    pct = (100.0 * tot_rbytes / tot_tbytes) if tot_tbytes else 0.0
    return {
        "binaries": per_binary,
        "totals": {
            "rosetta_count": tot_count,
            "rosetta_bytes": tot_rbytes,
            "total_bytes": tot_tbytes,
            "pct_bytes": round(pct, 4),
        },
    }


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--json",
        action="store_true",
        help="emit a stable machine-readable progress schema (no YAML needed)",
    )
    args = ap.parse_args()

    if args.json:
        print(json.dumps(collect_json(), indent=2, sort_keys=True))
        return 0

    yaml = try_yaml()
    if yaml is None:
        print("note: PyYAML not installed (`pip install pyyaml`)", file=sys.stderr)
        # Soft-fail; print the placeholder so make doesn't abort.

    yamls = sorted(CONFIG_DIR.glob("*.yaml")) if CONFIG_DIR.exists() else []
    if not yamls:
        print("(no work-pool yaml found yet — Phase 1 deliverable)")
        return 0

    if yaml is None:
        print("(install PyYAML to summarise)", file=sys.stderr)
        return 0

    grand = {s: {"count": 0, "bytes": 0} for s in (*STATUSES, *MIDDLEWARE)}
    for path in yamls:
        rows = yaml.safe_load(path.read_text()) or []
        if not isinstance(rows, list):
            continue
        per = {s: {"count": 0, "bytes": 0} for s in (*STATUSES, *MIDDLEWARE)}
        for r in rows:
            status = r.get("status", "unmatched")
            size = int(r.get("size", 0))
            tier = r.get("type", "matching")
            key = tier if tier in MIDDLEWARE else status
            if key in per:
                per[key]["count"] += 1
                per[key]["bytes"] += size
                grand[key]["count"] += 1
                grand[key]["bytes"] += size

        print(f"=== {path.name} ===")
        for k, v in per.items():
            if v["count"]:
                print(f"  {k:18s}  count={v['count']:>6d}  bytes={v['bytes']:>10,}")

        # _rosetta/ overlay — durable count of matched .cpp files
        # (survives YAML regeneration). Subtract the YAML's matched
        # count to get the "additional" landed via _rosetta/*.cpp,
        # since some YAML matches (middleware-*) are also auto-tagged
        # without a corresponding .cpp.
        binary_stem = path.stem
        rosetta_count, rosetta_bytes = _rosetta_overlay(binary_stem)
        if rosetta_count:
            print(f"  {'_rosetta/*.cpp':18s}  count={rosetta_count:>6d}  bytes={rosetta_bytes:>10,}  "
                  f"(durable, may overlap with YAML 'matched')")

    total_bytes = sum(v["bytes"] for v in grand.values())
    matched_bytes = grand["matched"]["bytes"] + grand["functional"]["bytes"]
    passthrough_bytes = grand["passthrough"]["bytes"]
    covered_bytes = matched_bytes + passthrough_bytes
    if total_bytes:
        pct_m = 100.0 * matched_bytes / total_bytes
        pct_p = 100.0 * passthrough_bytes / total_bytes
        pct_total = 100.0 * covered_bytes / total_bytes
        print(f"\noverall (YAML status):  matched/functional = {matched_bytes:,} / {total_bytes:,} bytes  ({pct_m:.2f}%)")
        if passthrough_bytes:
            print(f"                        passthrough        = {passthrough_bytes:,} bytes  ({pct_p:.2f}%)")
            print(f"                        relinkable cover   = {covered_bytes:,} / {total_bytes:,} bytes  ({pct_total:.2f}%)")

    # Cross-binary _rosetta overlay totals — the durable artifact.
    overlay_total_count = 0
    overlay_total_bytes = 0
    for path in yamls:
        c, b = _rosetta_overlay(path.stem)
        overlay_total_count += c
        overlay_total_bytes += b
    if overlay_total_count:
        pct = 100.0 * overlay_total_bytes / total_bytes if total_bytes else 0.0
        print(f"overall (_rosetta/*.cpp): {overlay_total_count:,} files = {overlay_total_bytes:,} bytes  ({pct:.2f}%)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
