#!/usr/bin/env python3
# meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
# Copyright (C) 2026  Samuel Stegall
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Reconcile the durable solved set into a committed aggregate index.

Pure-tree, toolchain-free: scans the committed
`src/<bin>/_rosetta/FUN_*.cpp` files across all five binaries — which
ARE the per-VA solved set — and writes the cross-binary aggregate
`docs/reconcile-state.json` (per-binary + cross-binary totals only, NOT
a 67k-element per-VA list; the tree itself is that list).

Sizes come from the committed `config/<bin>.func_sizes.json` manifest
(`tools/freeze_sizes.py`), so this runs in a clean CI checkout with no
Ghidra dump and no original binary. The output is deterministic and
byte-stable across identical runs (no timestamps, fixed key order), so
CI doesn't churn the committed file on no-op reconciles.

Usage:
  tools/reconcile.py            # regenerate docs/reconcile-state.json
  tools/reconcile.py --check    # verify the committed file is current
                                # (non-zero exit if it would change)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

# Reuse the durable-overlay + sizes logic from progress.py so the two
# tools can never disagree on what "solved" or "bytes" means.
sys.path.insert(0, str(Path(__file__).resolve().parent))
from progress import (  # noqa: E402
    ALL_BINARIES,
    _rosetta_overlay,
    _total_bytes,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "docs" / "reconcile-state.json"

GENERATED_NOTE = "auto-generated by tools/reconcile.py — do not hand-edit"


def build_state() -> dict:
    """Deterministic aggregate index of the committed _rosetta solved set."""
    binaries: dict[str, dict] = {}
    tot_count = tot_rbytes = tot_tbytes = 0
    for stem in ALL_BINARIES:
        rcount, rbytes = _rosetta_overlay(stem)
        tbytes = _total_bytes(stem)
        binaries[stem] = {
            "rosetta_count": rcount,
            "rosetta_bytes": rbytes,
            "total_bytes": tbytes,
        }
        tot_count += rcount
        tot_rbytes += rbytes
        tot_tbytes += tbytes

    pct = (100.0 * tot_rbytes / tot_tbytes) if tot_tbytes else 0.0
    return {
        "generated": GENERATED_NOTE,
        "binaries": binaries,
        "totals": {
            "rosetta_count": tot_count,
            "rosetta_bytes": tot_rbytes,
            "total_bytes": tot_tbytes,
            "pct_bytes": round(pct, 4),
        },
    }


def render(state: dict) -> str:
    """Stable, sorted, two-space-indented JSON with a trailing newline.

    `ensure_ascii=False` keeps the em-dash in the `generated` note as a
    literal UTF-8 character rather than a `\\u2014` escape — still fully
    deterministic, just more readable.
    """
    return json.dumps(state, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if docs/reconcile-state.json is stale (no write)",
    )
    args = ap.parse_args()

    state = build_state()
    text = render(state)
    totals = state["totals"]

    if args.check:
        current = OUT_PATH.read_text() if OUT_PATH.exists() else ""
        if current != text:
            print("reconcile: docs/reconcile-state.json is STALE — run 'make reconcile'", file=sys.stderr)
            return 1
        print(f"reconcile: up to date  (rosetta_count={totals['rosetta_count']})")
        return 0

    changed = (not OUT_PATH.exists()) or OUT_PATH.read_text() != text
    if changed:
        OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
        OUT_PATH.write_text(text)

    print("=== reconcile ===")
    for stem in ALL_BINARIES:
        b = state["binaries"][stem]
        print(f"  {stem:14s}  rosetta_count={b['rosetta_count']:>6d}  "
              f"rosetta_bytes={b['rosetta_bytes']:>9,}  total_bytes={b['total_bytes']:>11,}")
    print(f"  {'TOTAL':14s}  rosetta_count={totals['rosetta_count']:>6d}  "
          f"rosetta_bytes={totals['rosetta_bytes']:>9,}  total_bytes={totals['total_bytes']:>11,}  "
          f"({totals['pct_bytes']:.2f}%)")
    print(f"  {'wrote' if changed else 'unchanged'}: {OUT_PATH.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
