#!/usr/bin/env python3
# meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
# Copyright (C) 2026  Samuel Stegall
# SPDX-License-Identifier: AGPL-3.0-or-later
"""
Regenerate `asm/<binary>/*.s` files for functions whose size has been
corrected by `recompute_sizes.py`.

When recompute_sizes detects a Ghidra-under-counted function, it
writes the corrected size to `config/<binary>.size_overrides.json`,
and `compare.py` honours that override when reading bytes from orig.
But `asm/<binary>/*.s` was generated by `import_to_ghidra.py` with
the original (under-counted) size, so the byte stream there is
short. cluster_relocs.py and derive_templates.py read bytes from
the .s file, not from orig, so they see the OLD size.

This tool re-reads the bytes from `orig/<binary>` at the function's
RVA for the corrected size and rewrites the .s file. The disassembly
text portion of the .s file is replaced with a single
"size-overridden — raw bytes" line per 16-byte chunk, since
cluster_relocs only matches byte runs via regex. No disassembler is
needed.

Usage:
  tools/regenerate_overridden_asm.py [binary]   # default: all 5
  tools/regenerate_overridden_asm.py ffxivgame --dry-run

Idempotent. Safe to re-run.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG = REPO_ROOT / "config"
ASM_ROOT = REPO_ROOT / "asm"
ORIG = REPO_ROOT / "orig"

ALL_BINARIES = ("ffxivgame", "ffxivboot", "ffxivconfig", "ffxivlogin", "ffxivupdater")

RE_HEADER_RVA = re.compile(r"^# rva\s+0x([0-9a-fA-F]+)", re.MULTILINE)
RE_HEADER_SIZE = re.compile(r"^# size\s+0x([0-9a-fA-F]+)", re.MULTILINE)
RE_HEADER_NAME = re.compile(r"^# function\s+(\S+)", re.MULTILINE)


def regenerate_for_binary(stem: str, dry_run: bool) -> tuple[int, int]:
    overrides_path = CONFIG / f"{stem}.size_overrides.json"
    if not overrides_path.exists():
        print(f"  {stem}: no size_overrides — skipping")
        return (0, 0)
    overrides = json.loads(overrides_path.read_text())

    asm_dir = ASM_ROOT / stem
    orig_path = ORIG / f"{stem}.exe"
    if not orig_path.exists():
        print(f"  {stem}: missing orig binary — skipping")
        return (0, 0)
    orig_bytes = orig_path.read_bytes()

    # Build a one-shot RVA-prefix → path index. The asm dir can hold tens
    # of thousands of files (ffxivgame: ~94k); per-entry `glob` makes the
    # whole pass O(N×M) and unusable. One scandir is O(N).
    rva_index: dict[str, Path] = {}
    for p in asm_dir.iterdir():
        if not p.suffix == ".s":
            continue
        # Filename: <8-hex-rva>_FUN_<8-hex-va>.s OR similar.
        underscore = p.name.find("_")
        if underscore == 8:
            rva_index[p.name[:8]] = p

    rewrote = skipped = 0
    for entry in overrides:
        rva = entry["rva"] if isinstance(entry, dict) else entry[0]
        new_size = entry["new_size"] if isinstance(entry, dict) else entry[2]

        asm_path = rva_index.get(f"{rva:08x}")
        if asm_path is None:
            skipped += 1
            continue

        # Read existing header to confirm rva and old size.
        text = asm_path.read_text(errors="replace")
        m_size = RE_HEADER_SIZE.search(text)
        m_name = RE_HEADER_NAME.search(text)
        if not (m_size and m_name):
            skipped += 1
            continue
        old_size = int(m_size.group(1), 16)
        if old_size >= new_size:
            # Already at or beyond the corrected size — no rewrite needed.
            skipped += 1
            continue

        # Read new bytes from orig.
        new_bytes = orig_bytes[rva : rva + new_size]
        if len(new_bytes) != new_size:
            skipped += 1
            continue

        # Rewrite the .s file with a regenerated byte dump.
        new_text = (
            f"# function {m_name.group(1)}\n"
            f"# rva     0x{rva:08x}\n"
            f"# size    0x{new_size:x} ({new_size} bytes) — regenerated from size_overrides\n"
            f"# section .text\n\n"
        )
        # Emit instruction-line format that cluster_relocs.py's
        # RE_INSTR_LINE accepts: `    HEXOFF: HEX_BYTES   <pseudo-mnem>\n`
        for off in range(0, new_size, 16):
            chunk = new_bytes[off : off + 16]
            hex_str = " ".join(f"{b:02x}" for b in chunk)
            new_text += f"    {rva + off:08x}:  {hex_str}    BYTES\n"

        if dry_run:
            rewrote += 1
            continue
        asm_path.write_text(new_text)
        rewrote += 1

    print(f"  {stem}: rewrote {rewrote}, skipped {skipped}")
    return (rewrote, skipped)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("binary", nargs="?")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    binaries = (args.binary,) if args.binary else ALL_BINARIES
    print(f"=== regenerate_overridden_asm (dry-run={args.dry_run}) ===")
    total_r = total_s = 0
    for stem in binaries:
        r, s = regenerate_for_binary(stem, args.dry_run)
        total_r += r
        total_s += s
    print(f"\ntotal: rewrote={total_r}  skipped={total_s}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
