// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// AUTO-GENERATED by tools/emit_gam_header.py — DO NOT EDIT BY HAND.
//
// The GAM (Game Attribute Manager) registry: the binary's compile-time
// schema for wire-serializable game-state Data classes used by the
// FFXIV 1.x client's *lobby* protocol (CharaMakeData / ClientSelectData
// / Player / PlayerPlayer / ZoneInitData).
//
// IMPORTANT: this is a *different* wire system from the in-game
// SetActorPropertyPacket (which uses Murmur2(name) hashes as 32-bit
// wire ids). GAM uses small ordinal ids (100-345 + 579-595) within
// each Data class's namespace. See `docs/wire-protocol.md` for the
// architectural distinction.
//
// Source: ffxivgame.exe RTTI .rdata strings parsed by
// tools/extract_gam_params.py. 192 unique (id, namespace) entries
// recovered as of the 2026-04-30 Phase-1 dump. Counts here may drift
// slightly across rebuilds — re-run `make extract-gam` to refresh.

#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace meteor_decomp::gam {

enum class TypeKind : std::uint8_t {
    ARRAY_BLOB,
    ARRAY_BOOL,
    ARRAY_F32,
    ARRAY_I16,
    ARRAY_I32,
    ARRAY_I8,
    ARRAY_U32,
    BLOB,
    BOOL,
    I16,
    I32,
    I8,
    U64,
    UTF8_STRING,
};

constexpr std::string_view type_kind_name(TypeKind k) {
    switch (k) {
        case TypeKind::ARRAY_BLOB: return "ARRAY_BLOB";
        case TypeKind::ARRAY_BOOL: return "ARRAY_BOOL";
        case TypeKind::ARRAY_F32: return "ARRAY_F32";
        case TypeKind::ARRAY_I16: return "ARRAY_I16";
        case TypeKind::ARRAY_I32: return "ARRAY_I32";
        case TypeKind::ARRAY_I8: return "ARRAY_I8";
        case TypeKind::ARRAY_U32: return "ARRAY_U32";
        case TypeKind::BLOB: return "BLOB";
        case TypeKind::BOOL: return "BOOL";
        case TypeKind::I16: return "I16";
        case TypeKind::I32: return "I32";
        case TypeKind::I8: return "I8";
        case TypeKind::U64: return "U64";
        case TypeKind::UTF8_STRING: return "UTF8_STRING";
        default: return "?";
    }
}

struct ParamDescriptor {
    std::uint16_t id;        // ordinal within the Data class
    TypeKind      kind;
    std::uint16_t element_size;  // bytes per element (0 for variable-length Utf8String)
    std::uint32_t total_bytes;   // wire footprint (0 for variable-length)
    std::string_view name;       // property name from the binary
    std::string_view raw_type;   // raw type token (incl. unhandled templates)
};

// Application::Network::GameAttributeManager::Data::CharaMakeData — 26 parameters (26 named).
namespace charamakedata_params {

constexpr std::array<ParamDescriptor, 26> kRegistry {{
    { 100, TypeKind::I8, 1, 1, "tribe", "signed char" },
    { 101, TypeKind::I8, 1, 1, "size", "signed char" },
    { 102, TypeKind::I16, 2, 2, "hair", "short" },
    { 103, TypeKind::I8, 1, 1, "hairOption1", "signed char" },
    { 104, TypeKind::I8, 1, 1, "hairOption2", "signed char" },
    { 105, TypeKind::I8, 1, 1, "face", "signed char" },
    { 106, TypeKind::I8, 1, 1, "faceOption1", "signed char" },
    { 107, TypeKind::I8, 1, 1, "faceOption2", "signed char" },
    { 108, TypeKind::I8, 1, 1, "faceBrow", "signed char" },
    { 109, TypeKind::I8, 1, 1, "faceIris", "signed char" },
    { 110, TypeKind::I8, 1, 1, "faceEye", "signed char" },
    { 111, TypeKind::I8, 1, 1, "faceNose", "signed char" },
    { 112, TypeKind::I8, 1, 1, "faceCheek", "signed char" },
    { 113, TypeKind::I8, 1, 1, "faceMouth", "signed char" },
    { 114, TypeKind::I8, 1, 1, "faceJaw", "signed char" },
    { 115, TypeKind::I16, 2, 2, "haircolor", "short" },
    { 116, TypeKind::I16, 2, 2, "skintone", "short" },
    { 117, TypeKind::I16, 2, 2, "eyes", "short" },
    { 118, TypeKind::I8, 1, 1, "voice", "signed char" },
    { 119, TypeKind::I8, 1, 1, "guardian", "signed char" },
    { 120, TypeKind::I8, 1, 1, "birthdayMonth", "signed char" },
    { 121, TypeKind::I8, 1, 1, "birthdayDay", "signed char" },
    { 122, TypeKind::I8, 1, 1, "initialMainSkill", "signed char" },
    { 123, TypeKind::I8, 1, 1, "initialEquipSet", "signed char" },
    { 124, TypeKind::ARRAY_I32, 4, 12, "initialBonusItem", "int[3]" },
    { 125, TypeKind::I8, 1, 1, "initialTown", "signed char" },
}};

}  // namespace charamakedata_params

// Application::Network::GameAttributeManager::Data::ClientSelectData — 17 parameters (17 named).
namespace clientselectdata_params {

constexpr std::array<ParamDescriptor, 17> kRegistry {{
    { 100, TypeKind::UTF8_STRING, 0, 0, "PARAMNAME_100", "Sqex::Misc::Utf8String" },
    { 102, TypeKind::ARRAY_I32, 4, 0, "PARAMNAME_102", "int[0]" },
    { 103, TypeKind::U64, 8, 8, "PARAMNAME_103", "unsigned __int64" },
    { 104, TypeKind::I8, 1, 1, "PARAMNAME_104", "signed char" },
    { 107, TypeKind::I8, 1, 1, "PARAMNAME_107", "signed char" },
    { 108, TypeKind::UTF8_STRING, 0, 0, "PARAMNAME_108", "Sqex::Misc::Utf8String" },
    { 109, TypeKind::UTF8_STRING, 0, 0, "PARAMNAME_109", "Sqex::Misc::Utf8String" },
    { 110, TypeKind::I8, 1, 1, "PARAMNAME_110", "signed char" },
    { 111, TypeKind::I8, 1, 1, "PARAMNAME_111", "signed char" },
    { 112, TypeKind::I8, 1, 1, "PARAMNAME_112", "signed char" },
    { 113, TypeKind::I8, 1, 1, "PARAMNAME_113", "signed char" },
    { 114, TypeKind::I8, 1, 1, "PARAMNAME_114", "signed char" },
    { 115, TypeKind::ARRAY_I32, 4, 12, "PARAMNAME_115", "int[3]" },
    { 116, TypeKind::I8, 1, 1, "PARAMNAME_116", "signed char" },
    { 117, TypeKind::I16, 2, 2, "PARAMNAME_117", "short" },
    { 118, TypeKind::I16, 2, 2, "PARAMNAME_118", "short" },
    { 119, TypeKind::I8, 1, 1, "PARAMNAME_119", "signed char" },
}};

}  // namespace clientselectdata_params

// Application::Network::GameAttributeManager::Data::ClientSelectDataN — 17 parameters (17 named).
namespace clientselectdatan_params {

constexpr std::array<ParamDescriptor, 17> kRegistry {{
    { 100, TypeKind::UTF8_STRING, 0, 0, "PARAMNAME_100", "Sqex::Misc::Utf8String" },
    { 101, TypeKind::ARRAY_I32, 4, 0, "PARAMNAME_101", "int[0]" },
    { 102, TypeKind::U64, 8, 8, "PARAMNAME_102", "unsigned __int64" },
    { 103, TypeKind::I8, 1, 1, "PARAMNAME_103", "signed char" },
    { 104, TypeKind::I16, 2, 2, "PARAMNAME_104", "short" },
    { 105, TypeKind::I8, 1, 1, "PARAMNAME_105", "signed char" },
    { 106, TypeKind::I16, 2, 2, "PARAMNAME_106", "short" },
    { 107, TypeKind::I8, 1, 1, "PARAMNAME_107", "signed char" },
    { 108, TypeKind::UTF8_STRING, 0, 0, "PARAMNAME_108", "Sqex::Misc::Utf8String" },
    { 109, TypeKind::UTF8_STRING, 0, 0, "PARAMNAME_109", "Sqex::Misc::Utf8String" },
    { 110, TypeKind::I8, 1, 1, "PARAMNAME_110", "signed char" },
    { 111, TypeKind::I8, 1, 1, "PARAMNAME_111", "signed char" },
    { 112, TypeKind::I8, 1, 1, "PARAMNAME_112", "signed char" },
    { 113, TypeKind::I8, 1, 1, "PARAMNAME_113", "signed char" },
    { 114, TypeKind::I8, 1, 1, "PARAMNAME_114", "signed char" },
    { 115, TypeKind::ARRAY_I32, 4, 12, "PARAMNAME_115", "int[3]" },
    { 116, TypeKind::I8, 1, 1, "PARAMNAME_116", "signed char" },
}};

}  // namespace clientselectdatan_params

// Application::Network::GameAttributeManager::Data::Player — 92 parameters (92 named).
namespace player_params {

constexpr std::array<ParamDescriptor, 92> kRegistry {{
    { 135, TypeKind::I8, 1, 1, "craft_assist_buff_type", "signed char" },
    { 136, TypeKind::I8, 1, 1, "craft_assist_buff_level", "signed char" },
    { 137, TypeKind::ARRAY_I32, 4, 36, "craftPointDeliverTotal", "int[9]" },
    { 138, TypeKind::ARRAY_I32, 4, 36, "craftPointCollaborationTotal", "int[9]" },
    { 139, TypeKind::ARRAY_I16, 2, 80, "craftDeliverQuantity", "short[40]" },
    { 140, TypeKind::I8, 1, 1, "craftCollaborationEntrySkill", "signed char" },
    { 141, TypeKind::ARRAY_I16, 2, 18, "craftCollaborationEntryID", "short[9]" },
    { 142, TypeKind::ARRAY_I16, 2, 600, "craftCollaborationQuantity", "short[300]" },
    { 143, TypeKind::ARRAY_I32, 4, 1200, "craftPointCollaborationNow", "int[300]" },
    { 144, TypeKind::ARRAY_I16, 2, 32, "guildleveId", "short[16]" },
    { 145, TypeKind::ARRAY_BOOL, 1, 16, "guildleveDone", "bool[16]" },
    { 146, TypeKind::ARRAY_BOOL, 1, 16, "guildleveChecked", "bool[16]" },
    { 147, TypeKind::ARRAY_BOOL, 1, 16, "guildleveStopRetry", "bool[16]" },
    { 148, TypeKind::ARRAY_I8, 1, 16, "guildleveBoostPoint", "signed char[16]" },
    { 149, TypeKind::ARRAY_I8, 1, 16, "guildleveMark", "signed char[16]" },
    { 150, TypeKind::ARRAY_I32, 4, 64, "guildleveRewardItem", "int[16]" },
    { 152, TypeKind::ARRAY_I32, 4, 64, "guildleveRewardMainNumber", "int[16]" },
    { 153, TypeKind::ARRAY_I8, 1, 16, "guildleveRewardSubItem", "signed char[16]" },
    { 155, TypeKind::I32, 4, 4, "guildleveRewardSubNumber", "int" },
    { 156, TypeKind::I16, 2, 2, "guildleveBonusRewardStock", "short" },
    { 157, TypeKind::ARRAY_I16, 2, 14, "guildleveTerm", "short[7]" },
    { 159, TypeKind::ARRAY_BOOL, 1, 4096, "guildleveSeed", "bool[4096]" },
    { 160, TypeKind::ARRAY_I32, 4, 28, "guildleveFaction", "int[7]" },
    { 161, TypeKind::ARRAY_BOOL, 1, 512, "guildleveComplete", "bool[512]" },
    { 162, TypeKind::ARRAY_BOOL, 1, 1024, "guildleveClearCount", "bool[1024]" },
    { 163, TypeKind::ARRAY_BOOL, 1, 1024, "guildlevePassiveClearCount", "bool[1024]" },
    { 164, TypeKind::ARRAY_BOOL, 1, 1024, "guildleveMaxRewardMoney", "bool[1024]" },
    { 165, TypeKind::ARRAY_BOOL, 1, 16384, "passiveGuildleveStopRetry", "bool[16384]" },
    { 166, TypeKind::ARRAY_BOOL, 1, 16384, "event_achieve_aetheryte", "bool[16384]" },
    { 167, TypeKind::ARRAY_BOOL, 1, 512, "profile_item_know", "bool[512]" },
    { 168, TypeKind::ARRAY_BOOL, 1, 256, "profile_item_get", "bool[256]" },
    { 169, TypeKind::ARRAY_BOOL, 1, 256, "profile_item_experience", "bool[256]" },
    { 170, TypeKind::ARRAY_BOOL, 1, 2560, "profile_monster_encount", "bool[2560]" },
    { 172, TypeKind::I32, 4, 4, "profile_monster_kill", "int" },
    { 173, TypeKind::I32, 4, 4, "profile_monster_new", "int" },
    { 174, TypeKind::ARRAY_I16, 2, 14, "profile_raremonster_encount", "short[7]" },
    { 175, TypeKind::ARRAY_I8, 1, 7, "profile_raremonster_new", "signed char[7]" },
    { 176, TypeKind::I32, 4, 4, "craft_learning_recipe", "int" },
    { 177, TypeKind::I8, 1, 1, "tutorial_done", "signed char" },
    { 178, TypeKind::I8, 1, 1, "raremonster_notorious", "signed char" },
    { 179, TypeKind::ARRAY_I8, 1, 7, "raremonster_guild", "signed char[7]" },
    { 180, TypeKind::ARRAY_BOOL, 1, 256, "harvest_history", "bool[256]" },
    { 181, TypeKind::ARRAY_I8, 1, 16, "harvest_history_support", "signed char[16]" },
    { 182, TypeKind::ARRAY_I8, 1, 32, "harvest_latest_time", "signed char[32]" },
    { 183, TypeKind::I32, 4, 4, "harvest_latest_count", "int" },
    { 184, TypeKind::ARRAY_I8, 1, 64, "harvest_limit_rate_array", "signed char[64]" },
    { 185, TypeKind::I8, 1, 1, "harvest_limit_term_array", "signed char" },
    { 186, TypeKind::UTF8_STRING, 0, 0, "event_boost_point", "Sqex::Misc::Utf8String" },
    { 187, TypeKind::I8, 1, 1, "event_rave_etc", "signed char" },
    { 188, TypeKind::I8, 1, 1, "event_colosseum_etc", "signed char" },
    { 189, TypeKind::I16, 2, 2, "event_guild_battle", "short" },
    { 190, TypeKind::I8, 1, 1, "event_special_etc", "signed char" },
    { 191, TypeKind::I8, 1, 1, "latest_aetheryte", "signed char" },
    { 192, TypeKind::I8, 1, 1, "npcLinkshellBlob", "signed char" },
    { 193, TypeKind::I8, 1, 1, "npcLinkshellBlobCount", "signed char" },
    { 194, TypeKind::I8, 1, 1, "snpcNickname", "signed char" },
    { 195, TypeKind::I32, 4, 4, "snpcSkin", "int" },
    { 196, TypeKind::BOOL, 1, 1, "snpcSexual", "bool" },
    { 197, TypeKind::ARRAY_I16, 2, 18, "snpcCoordinate", "short[9]" },
    { 198, TypeKind::ARRAY_I8, 1, 9, "snpcMainSkillType", "signed char[9]" },
    { 199, TypeKind::ARRAY_U32, 4, 36, "snpcSubSkillType", "unsigned int[9]" },
    { 200, TypeKind::ARRAY_F32, 4, 36, "snpcPersonality", "float[9]" },
    { 201, TypeKind::ARRAY_I8, 1, 9, "gnpcType", "signed char[9]" },
    { 202, TypeKind::ARRAY_I32, 4, 80, "anima", "int[20]" },
    { 203, TypeKind::ARRAY_I32, 4, 64, "animaTerm", "int[16]" },
    { 204, TypeKind::ARRAY_I8, 1, 7, "betacheck", "signed char[7]" },
    { 205, TypeKind::ARRAY_F32, 4, 28, "postItemCageNo", "float[7]" },
    { 206, TypeKind::ARRAY_F32, 4, 28, "postItemStacks", "float[7]" },
    { 207, TypeKind::ARRAY_I32, 4, 28, "postFromActorId", "int[7]" },
    { 208, TypeKind::ARRAY_I32, 4, 28, "postArrivalTime", "int[7]" },
    { 209, TypeKind::ARRAY_I16, 2, 14, "postDeliveryStatus", "short[7]" },
    { 210, TypeKind::ARRAY_I16, 2, 14, "postAppendix", "short[7]" },
    { 211, TypeKind::ARRAY_I32, 4, 28, "companyId", "int[7]" },
    { 212, TypeKind::ARRAY_I32, 4, 28, "companyMemberRank", "int[7]" },
    { 213, TypeKind::ARRAY_I32, 4, 28, "companyAdmissionDate", "int[7]" },
    { 214, TypeKind::ARRAY_U32, 4, 28, "company_last_access_date", "unsigned int[7]" },
    { 215, TypeKind::ARRAY_U32, 4, 256, "companyCurrentMemberPoint", "unsigned int[64]" },
    { 216, TypeKind::ARRAY_I8, 1, 64, "companyTotalMemberPoint", "signed char[64]" },
    { 217, TypeKind::I32, 4, 4, "companyTotalContributionCurrentLevel", "int" },
    { 218, TypeKind::I32, 4, 4, "companyTotalContributionCurrentOnWeek", "int" },
    { 222, TypeKind::ARRAY_I32, 4, 64, "companyTotalContributionTotal", "int[16]" },
    { 223, TypeKind::I32, 4, 4, "companySelfContributionTotal", "int" },
    { 224, TypeKind::I32, 4, 4, "companyPupilContributionTotal", "int" },
    { 225, TypeKind::ARRAY_I16, 2, 6, "companyInvitedPlayer", "short[3]" },
    { 226, TypeKind::ARRAY_I32, 4, 12, "companyInvitingCharacter", "int[3]" },
    { 227, TypeKind::ARRAY_BOOL, 1, 16, "companyInvitingCharacterRank", "bool[16]" },
    { 228, TypeKind::ARRAY_I32, 4, 28, "craftMakingRecipeHistory", "int[7]" },
    { 229, TypeKind::ARRAY_I32, 4, 28, "craftRewardRecipeHistory", "int[7]" },
    { 230, TypeKind::ARRAY_I32, 4, 12, "favoriteAetheryte", "int[3]" },
    { 231, TypeKind::I16, 2, 2, "specialEventNumber", "short" },
    { 232, TypeKind::I16, 2, 2, "specialEventCounter", "short" },
    { 233, TypeKind::I8, 1, 1, "guildleveOfferLimit", "signed char" },
}};

}  // namespace player_params

// Application::Network::GameAttributeManager::Data::PlayerPlayer — 37 parameters (37 named).
namespace playerplayer_params {

constexpr std::array<ParamDescriptor, 37> kRegistry {{
    { 203, TypeKind::I8, 1, 1, "PARAMNAME_203", "signed char" },
    { 321, TypeKind::I8, 1, 1, "PARAMNAME_321", "signed char" },
    { 322, TypeKind::I16, 2, 2, "PARAMNAME_322", "short" },
    { 323, TypeKind::I8, 1, 1, "PARAMNAME_323", "signed char" },
    { 324, TypeKind::I8, 1, 1, "PARAMNAME_324", "signed char" },
    { 325, TypeKind::I8, 1, 1, "PARAMNAME_325", "signed char" },
    { 326, TypeKind::I8, 1, 1, "PARAMNAME_326", "signed char" },
    { 327, TypeKind::I8, 1, 1, "PARAMNAME_327", "signed char" },
    { 328, TypeKind::I8, 1, 1, "PARAMNAME_328", "signed char" },
    { 329, TypeKind::I8, 1, 1, "PARAMNAME_329", "signed char" },
    { 330, TypeKind::I8, 1, 1, "PARAMNAME_330", "signed char" },
    { 331, TypeKind::I8, 1, 1, "PARAMNAME_331", "signed char" },
    { 332, TypeKind::I8, 1, 1, "PARAMNAME_332", "signed char" },
    { 333, TypeKind::I8, 1, 1, "PARAMNAME_333", "signed char" },
    { 334, TypeKind::I8, 1, 1, "PARAMNAME_334", "signed char" },
    { 335, TypeKind::I16, 2, 2, "PARAMNAME_335", "short" },
    { 336, TypeKind::I16, 2, 2, "PARAMNAME_336", "short" },
    { 337, TypeKind::I16, 2, 2, "PARAMNAME_337", "short" },
    { 338, TypeKind::I8, 1, 1, "PARAMNAME_338", "signed char" },
    { 339, TypeKind::I32, 4, 4, "PARAMNAME_339", "int" },
    { 340, TypeKind::ARRAY_U32, 4, 64, "PARAMNAME_340", "unsigned int[16]" },
    { 341, TypeKind::ARRAY_BLOB, 128, 2048, "PARAMNAME_341", "Blob<128>[16]" },
    { 342, TypeKind::ARRAY_BOOL, 1, 2048, "PARAMNAME_342", "bool[2048]" },
    { 343, TypeKind::ARRAY_U32, 4, 28, "PARAMNAME_343", "unsigned int[7]" },
    { 344, TypeKind::ARRAY_BLOB, 128, 896, "PARAMNAME_344", "Blob<128>[7]" },
    { 345, TypeKind::ARRAY_BOOL, 1, 2048, "PARAMNAME_345", "bool[2048]" },
    { 579, TypeKind::ARRAY_U32, 4, 64, "PARAMNAME_579", "unsigned int[16]" },
    { 580, TypeKind::ARRAY_BOOL, 1, 64, "PARAMNAME_580", "bool[64]" },
    { 581, TypeKind::ARRAY_BOOL, 1, 64, "PARAMNAME_581", "bool[64]" },
    { 583, TypeKind::I8, 1, 1, "PARAMNAME_583", "signed char" },
    { 584, TypeKind::I8, 1, 1, "PARAMNAME_584", "signed char" },
    { 585, TypeKind::I8, 1, 1, "PARAMNAME_585", "signed char" },
    { 586, TypeKind::I8, 1, 1, "PARAMNAME_586", "signed char" },
    { 587, TypeKind::I8, 1, 1, "PARAMNAME_587", "signed char" },
    { 588, TypeKind::ARRAY_I32, 4, 12, "PARAMNAME_588", "int[3]" },
    { 589, TypeKind::I8, 1, 1, "PARAMNAME_589", "signed char" },
    { 595, TypeKind::BLOB, 1, 2500, "PARAMNAME_595", "Blob<2500>" },
}};

}  // namespace playerplayer_params

// Application::Network::GameAttributeManager::Data::ZoneInitData — 3 parameters (3 named).
namespace zoneinitdata_params {

constexpr std::array<ParamDescriptor, 3> kRegistry {{
    { 100, TypeKind::I32, 4, 4, "PARAMNAME_100", "int" },
    { 101, TypeKind::UTF8_STRING, 0, 0, "PARAMNAME_101", "Sqex::Misc::Utf8String" },
    { 102, TypeKind::I8, 1, 1, "PARAMNAME_102", "signed char" },
}};

}  // namespace zoneinitdata_params

}  // namespace meteor_decomp::gam
