// [STAMPED] from FUN_0040de20.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0000de90 (VA 0x0040de90)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x40de20 — no-reloc cluster member (36B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 2 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 8b 44 24 04 8b 54 24 08 3b c2 74 17 8b 4c 24 0c 56 8b 31 89 30 8b 71 04 89 70 04 83 c0 08 3b c2 75 ef 5e c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x8b
        _emit 0x44
        _emit 0x24
        _emit 0x04
        _emit 0x8b
        _emit 0x54
        _emit 0x24
        _emit 0x08
        _emit 0x3b
        _emit 0xc2
        _emit 0x74
        _emit 0x17
        _emit 0x8b
        _emit 0x4c
        _emit 0x24
        _emit 0x0c
        _emit 0x56
        _emit 0x8b
        _emit 0x31
        _emit 0x89
        _emit 0x30
        _emit 0x8b
        _emit 0x71
        _emit 0x04
        _emit 0x89
        _emit 0x70
        _emit 0x04
        _emit 0x83
        _emit 0xc0
        _emit 0x08
        _emit 0x3b
        _emit 0xc2
        _emit 0x75
        _emit 0xef
        _emit 0x5e
        _emit 0xc3
    }
}
