// [STAMPED] from FUN_0041b090.cpp by tools/stamp_clusters.py
//           sibling at orig RVA 0x0001b180 (VA 0x0041b180)
//           same byte-shape cluster — see cluster_shapes.py output
// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x41b090 — no-reloc cluster member (77B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 4 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 83 ec 08 8a 44 24 13 8a 4c 24 12 8a 54 24 11 88 04 24 8a 44 24 10 88 4c 24 01 8a 4c 24 0f 88 54 24 02 8a 54 24 0e 88 44 24 03 8a 44 24 0d 88 4c 24 04 8a 4c 24 0c 88 44 24 06 8b 04 24 88 54 24 05 88 4c 24 07 8b 54 24 04 83 c4 08 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x83
        _emit 0xec
        _emit 0x08
        _emit 0x8a
        _emit 0x44
        _emit 0x24
        _emit 0x13
        _emit 0x8a
        _emit 0x4c
        _emit 0x24
        _emit 0x12
        _emit 0x8a
        _emit 0x54
        _emit 0x24
        _emit 0x11
        _emit 0x88
        _emit 0x04
        _emit 0x24
        _emit 0x8a
        _emit 0x44
        _emit 0x24
        _emit 0x10
        _emit 0x88
        _emit 0x4c
        _emit 0x24
        _emit 0x01
        _emit 0x8a
        _emit 0x4c
        _emit 0x24
        _emit 0x0f
        _emit 0x88
        _emit 0x54
        _emit 0x24
        _emit 0x02
        _emit 0x8a
        _emit 0x54
        _emit 0x24
        _emit 0x0e
        _emit 0x88
        _emit 0x44
        _emit 0x24
        _emit 0x03
        _emit 0x8a
        _emit 0x44
        _emit 0x24
        _emit 0x0d
        _emit 0x88
        _emit 0x4c
        _emit 0x24
        _emit 0x04
        _emit 0x8a
        _emit 0x4c
        _emit 0x24
        _emit 0x0c
        _emit 0x88
        _emit 0x44
        _emit 0x24
        _emit 0x06
        _emit 0x8b
        _emit 0x04
        _emit 0x24
        _emit 0x88
        _emit 0x54
        _emit 0x24
        _emit 0x05
        _emit 0x88
        _emit 0x4c
        _emit 0x24
        _emit 0x07
        _emit 0x8b
        _emit 0x54
        _emit 0x24
        _emit 0x04
        _emit 0x83
        _emit 0xc4
        _emit 0x08
        _emit 0xc3
    }
}
