// meteor-decomp — clean-room decompilation of FINAL FANTASY XIV 1.x client binaries
// Copyright (C) 2026  Samuel Stegall
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// SPDX-License-Identifier: AGPL-3.0-or-later
//
// FUNCTION: ffxivgame 0x45f10d — no-reloc cluster member (13B raw _emit)
// Auto-generated by tools/derive_templates.py.
// Cluster representative — covers 3 byte-identical (or
// reloc-equivalent) members.
//
// Asm: 33 c0 40 83 7c 24 04 00 75 02 33 c0 c3

extern "C" __declspec(naked) void no_reloc_member() {
    __asm {
        _emit 0x33
        _emit 0xc0
        _emit 0x40
        _emit 0x83
        _emit 0x7c
        _emit 0x24
        _emit 0x04
        _emit 0x00
        _emit 0x75
        _emit 0x02
        _emit 0x33
        _emit 0xc0
        _emit 0xc3
    }
}
